### ISSUE TITLE
Jekyll breaks when URIs contain a colon

### ISSUE THREAD

**Issue by dret** [jekyll/jekyll#5480] opened 2016-10-12 18:44 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

i am generating pages locally, and then use jekyll to process them. now that i have started generating pages where the file names contains colons, jekyll simply breaks. the error message is:

```
Configuration file: /Users/dret/Desktop/github/webconcepts/_config.yml
            Source: /Users/dret/Desktop/github/webconcepts
       Destination: /Users/dret/Desktop/github/webconcepts/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    The URL /concepts/oauth-uri/urn:ietf:params:oauth:client-assertion-type:jwt-bearer.html is invalid because it contains a colon.
```

this obviously makes no sense because there is no problem with colons in filenames or in URIs. is there a way around this bug?

not yet pushing to github, since i want to avoid a broken page. https://github.com/dret/webconcepts is where the repo lives, but the version there is one that works because the files with colons are not yet added.

## The Output I Wanted

really nothing but jekyll working as expected, building the site for file names that contain colons.

**Comment by pathawks** [comment] 2016-10-12 19:18
Duplicate of #5284

**Closed by pathawks** 2016-10-12 19:18 UTC
