### ISSUE TITLE
Modifying _config.yml while running `jekyll serve` will not load the new configuration

### ISSUE THREAD

**Issue by fulldecent** [jekyll/jekyll#3373] opened 2015-01-28 23:24 UTC
TEST CASE:
 - Run `jekyll serve`
 - `echo '@INVALID=yourmom' > _config.yml`
 - Reload browser

EXPECTED
Served page will reflect updated

ACTUAL
Page does not reflect updated `_config.yml`

**Comment by pathawks** [comment] 2015-01-28 23:58
Duplicate of #2302

**Comment by parkr** [comment] 2015-01-29 03:08
This is a limitation of the design of the system. The confuguration is only ever loaded once. Doing so aids incremental regeneration and reduces the pressure on the garbage collector (calling site.process instead of essentially running the build command every time).

**Comment by parkr** [comment] 2015-01-29 03:09
If you want content-like data, I'd recommend a data file. Thanks!

**Closed by parkr** 2015-01-29 03:09 UTC
