### ISSUE TITLE
site.baseurl not able to set to string.empty

### ISSUE THREAD

**Issue by jwillmer** [jekyll/jekyll#5908] opened 2017-02-27 12:53 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

I have a jekyll theme in my repository that runs without any problem on GitHub since I devloped it but today I noticed that the links to the [generated blog](http://jwillmer.github.io/jekyllDecent/) are all broken. Did something in the engine changed?

This is how I define a link:
```
<link rel="stylesheet" href="{{ "/css/screen.css" | prepend: site.github.url | prepend: site.baseurl }}">
```

and this is in my `_config`:
```
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "http://jwillmer.github.io/jekyllDecent" # the base hostname & protocol for your site. Have a look at robots.txt as well!
```

Currently the links look like this:
```
http://jwillmer.github.io/jekyllDecenthttp://jwillmer.github.io/jekyllDecent/css/screen.css
```

You can find the project at: [jwillmer/jekyllDecent](https://github.com/jwillmer/jekyllDecent)

**Comment by pathawks** [comment] 2017-02-27 13:12
Right off the bat, your `baseurl` should be `/jekyllDecent` and you should not include that part in `site.url`.
Is there a reason you are using `site.github.url` to generate your link instead of `site.url`? I don't know much about how the GitHub metadata gem works, but that isn't a Jekyll core feature.

I would suggest you try moving to the new `absolute_url` filter, instead of prepending.

**Comment by pathawks** [comment] 2017-02-27 13:19
I've figured it out.

Your report is not accurate. Jekyll is not generating `http://jwillmer.github.io/jekyllDecenthttp://jwillmer.github.io/jekyllDecent/css/screen.css`, but is generating `/jekyllDecenthttp://jwillmer.github.io/jekyllDecent/css/screen.css`. This is because you are prepending in the wrong order. You should prepend `baseurl` _first_, and then prepend `site.url`. This doesn't matter if you have an empty `baseurl`, but it broke with jekyll/github-metadata#76

I guess `site.github.url` contains both `site.url` and `site.baseurl`?

There are three potential solutions to your problem:

 1. If you don't intend to use `site.baseurl` as intended, just drop it from the template and only prepend `site.github.url`
 2. Change `site.baseurl` as described above, and change the filter to _first_ prepend `site.baseurl` and _then_ prepend `site.url`
 3. Just use the new `absolute_url` filter.

**Closed by pathawks** 2017-02-27 13:19 UTC
