### ISSUE TITLE
Jekyll inserting extra code when generating blog posts

### ISSUE THREAD

**Issue by mozgbrasil** [jekyll/jekyll#7178] opened 2018-08-08 19:08 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [x] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## The Output I Wanted

Good afternoon

I just updated a post, but an error is occurring with the use of code comment, the comment being opened and not finalized

The following is the page where the error occurs

http://mozg.com.br/ubuntu/ubuntu-after-install

The following is the page code

https://github.com/mozgbrasil/mozgbrasil.github.io/blob/master/_posts/2016-04-25-ubuntu-after-install.markdown

**Comment by pathawks** [comment] 2018-08-08 19:16
Are you using a plugin to obscure email addresses in your code?

Inside the codeblock, something is treating `marcio@192.168.0.6` as an email address and messing with the HTML. I wonder if it is somehow removing the closing `</code>` tag?

**Comment by pathawks** [comment] 2018-08-08 19:41
The issue is with the [`compress` layout](https://github.com/mozgbrasil/mozgbrasil.github.io/blob/master/_layouts/compress.html). If you stop using that, the code blocks display as intended.

![screenshot - 1](https://user-images.githubusercontent.com/251545/43860341-030b4bda-9b19-11e8-98bc-e26ce3f37934.png)

**Comment by ashmaroli** [comment] 2018-08-08 19:44
> The issue is with the compress layout. If you stop using that, the code blocks display as intended.

The issue is with `jekyll-mentions`.
Requires patch similar to `jekyll/jemoji:82`

**Closed** 2018-08-08 19:54 UTC
Labels: downstream-issue :arrow_down:, support

**Comment by DirtyF** [comment] 2018-08-08 19:59
@mozgbrasil A new version of the `jekyll-mentions` plugin is available, please upgrade.
