### ISSUE TITLE
Header falls out of div

### ISSUE THREAD

**Issue by Krazov** [jekyll/jekyll#3786] opened 2015-06-14 14:20 UTC
I have a code like that in my `default.html`:

```
<!DOCTYPE html>
<html>
  {% include head.html %}
  <body>
    <div class="page">
        {% include header.html %}
        <main class="content">
            {{ content }}
        </main>
    </div>
    {% include footer.html %}
  </body>
</html>
```

The result is:

```
<!DOCTYPE html>
<head>...</head>
<body>
    <div class="page">
        <header class="site-header">...</header>
        <main class="container">...</main>
    </div>
    <footer class="site-footer">...</footer>
</body>
```

And that is okay. But when I make:

```
<!DOCTYPE html>
<html>
  {% include head.html %}
  <body>
    <div class="page">
        <main class="content">
            {{ content }}
        </main>
        {% include header.html %}
    </div>
    {% include footer.html %}
  </body>
</html>
```

(Header under the main, not the other way around.) I get:

```
<!DOCTYPE html>
<head>...</head>
<body>
    <div class="page">
        <main class="container">...</main>
    </div>
    <header class="site-header">...</header>
    <footer class="site-footer">...</footer>
</body>
```

Header is not contained in `<div class="page">`.

For clarity, my `header.html` is:

```
<header class="site-header">
   <nav class="site-nav">
        <a class="site-title" href="{{ site.baseurl }}/">Start</a>
        {% for page in site.pages %}
            {% if page.title %}<a class="page-link" href="{{ page.url | prepend: site.baseurl }}">{{ page.title }}</a>{% endif %}
        {% endfor %}
    </nav>
</header>
```

It seems strange that it does not allow me to use header not as a first element. Is that intentional? Or maybe I’m doing something wrong?

**Comment by envygeeks** [comment] 2015-06-14 14:22
Hello, this is not a bug in Jekyll so I must close this ticket and ask that you ask your question at https://talk.jekyllrb.com because this ticket system is for Jekyll bugs only and not for generic HTML help.

**Closed by envygeeks** 2015-06-14 14:22 UTC
