### ISSUE TITLE
[jekyll 3.2.0]static_file.rb 149 `utime': No such file or directory

### ISSUE THREAD

**Issue by jnozsc** [jekyll/jekyll#5144] opened 2016-07-28 02:59 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps
```
2016-07-28T02:51:37.297835+00:00 app[web.1]: Generating site: /app -> /app/_site
2016-07-28T02:51:37.371747+00:00 heroku[web.1]: Process exited with status 1
2016-07-28T02:51:37.386510+00:00 heroku[web.1]: State changed from starting to crashed
2016-07-28T02:51:37.387493+00:00 heroku[web.1]: State changed from crashed to starting
2016-07-28T02:51:39.161559+00:00 heroku[web.1]: Starting process with command `bundle exec rackup config.ru -p 30370`
2016-07-28T02:51:52.026687+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/static_file.rb:149:in `utime': No such file or directory @ utime_internal - /app/_site/bin/erb (Errno::ENOENT)
2016-07-28T02:51:52.026709+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/static_file.rb:149:in `copy_file'
2016-07-28T02:51:52.026711+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/static_file.rb:93:in `write'
2016-07-28T02:51:52.026712+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:212:in `block in write'
2016-07-28T02:51:52.026721+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:211:in `write'
2016-07-28T02:51:52.026719+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:332:in `block in each_site_file'
2016-07-28T02:51:52.026721+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:331:in `each_site_file'
2016-07-28T02:51:52.026722+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:71:in `process'
2016-07-28T02:51:52.026714+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:332:in `each'
2016-07-28T02:51:52.026724+00:00 app[web.1]: 	from /app/config.ru:3:in `new'
2016-07-28T02:51:52.026713+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:333:in `block (2 levels) in each_site_file'
2016-07-28T02:51:52.026723+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-jekyll-0.4.5/lib/rack/jekyll.rb:44:in `initialize'
2016-07-28T02:51:52.026726+00:00 app[web.1]: 	from /app/config.ru:in `new'
2016-07-28T02:51:52.026725+00:00 app[web.1]: 	from /app/config.ru:3:in `block in <main>'
2016-07-28T02:51:52.026726+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
2016-07-28T02:51:52.026729+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
2016-07-28T02:51:52.026720+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:331:in `each'
2016-07-28T02:51:52.026729+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
2016-07-28T02:51:52.026725+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
2016-07-28T02:51:52.026723+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-jekyll-0.4.5/lib/rack/jekyll.rb:110:in `process'
2016-07-28T02:51:52.026727+00:00 app[web.1]: 	from /app/config.ru:in `<main>'
2016-07-28T02:51:52.026732+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
2016-07-28T02:51:52.026734+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
2016-07-28T02:51:52.026731+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
2016-07-28T02:51:52.026731+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
2016-07-28T02:51:52.026735+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
2016-07-28T02:51:52.026730+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
2016-07-28T02:51:52.038753+00:00 app[web.1]: Generating site: /app -> /app/_site
2016-07-28T02:51:52.026739+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/bin/rackup:23:in `load'
2016-07-28T02:51:52.026736+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
2016-07-28T02:51:52.038751+00:00 app[web.1]: Configuration file: /app/_config.yml
2016-07-28T02:51:52.026740+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/bin/rackup:23:in `<main>'
2016-07-28T02:51:52.158547+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by envygeeks** [comment] 2016-07-28 05:01
Caused by: https://github.com/jekyll/jekyll/commit/0f74db413110ae7cb435bbd2d7f21a2918dd9cfe /cc @ayastreb

**Comment by ayastreb** [comment] 2016-07-28 09:06
@envygeeks I can not reproduce it. Were you able to reproduce the error?

**Comment by jnozsc** [comment] 2016-08-04 06:51
After I re-verify this issue, I notice this maybe a `rack-jekyll` issue, not jekyll-self issue

https://github.com/adaoraul/rack-jekyll/issues/49

**Comment by stomar** [comment] 2016-08-04 17:51
Please reopen, this is **not** a problem specific to rack-jekyll (which has not changed for quite some time).

For Jekyll 3.2.0 we observe the same behaviour on Heroku while trying to deploy www.ruby-lang.org using [lanyon](https://github.com/stomar/lanyon), which --- just like rack-jekyll --- relies on Jekyll::Site#process to build the site. Jekyll versions before 3.2.0 worked just fine.

**Comment by jnozsc** [comment] 2016-08-04 17:53
@stomar ok.

maybe an issue on both side, reopen for further invesitgate

**Comment by Crunch09** [comment] 2016-09-01 17:51
@jnozsc Are you still experiencing this issue and do you have a link to the repo where you are experiencing this issue?

I could only reproduce it (with my own page ) on heroku if i created a `Procfile` and called `jekyll serve` within there but this also worked fine after i excluded the `bin` directory in my `_config.yml`.

**Comment by jnozsc** [comment] 2016-09-03 07:27
sorry for late response, busy on my daytime job

Thanks @Crunch09 's suggestion.

I modify my `_config.yml`

with `exclude: [vendor, bin]`

and then I update my Gemfile and push to heroku, it works fine.

here is my `Gemfile.lock`

```
GEM
  remote: https://rubygems.org/
  specs:
    colorator (1.1.0)
    ffi (1.9.14)
    forwardable-extended (2.6.0)
    jekyll (3.2.1)
      colorator (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-sass-converter (1.4.0)
      sass (~> 3.4)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    kramdown (1.12.0)
    liquid (3.0.6)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    mercenary (0.3.6)
    pathutil (0.14.0)
      forwardable-extended (~> 2.6)
    rack (1.6.4)
    rack-jekyll (0.5.0)
      jekyll (>= 1.3)
      listen (>= 1.3)
      rack (~> 1.5)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    rouge (1.11.1)
    safe_yaml (1.0.4)
    sass (3.4.22)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll (~> 3.2.0)
  rack
  rack-jekyll (~> 0.5.0)

RUBY VERSION
   ruby 2.3.1p112

BUNDLED WITH
   1.12.5
```

I think this issue can be fixed by modify `_config.yml`

I hope others can confirm it as well, so we can close this issue

Thanks

**Comment by stomar** [comment] 2016-09-03 08:49
That's only a workaround... and one that would not be applicable for sites that happen to include a `bin` dir in their directory structure.

The problem lies elsewhere, namely in changing the mtimes instance variable to a class instance variable (all worked fine before 0f74db413110ae7cb435bbd2d7f21a2918dd9cfe), which obviously changes the behaviour in an as of yet not really understood way.

So, I would strongly suggest to revert that commit unless there is a very good reason to keep it---and code style (rubocop) IMO is not a good enough reason here.

**Comment by xuanxu** [comment] 2016-09-05 09:39
Thanks @Crunch09 
I've updated the Gemfile to use the latest Jekyll version and still experiencing the issue when pushing to Heroku. Previous commit worked well,  [82ad008afcd](https://github.com/xuanxu/spaceup_bcn/commit/82ad008afcd3cf5ba77d63c1e336a0d887c51eb7) (current master) fails. This is part of the backtrace from the Heroku's log:

````
Bundle complete! 3 Gemfile dependencies, 19 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into ./vendor/bundle.
Bundle completed (0.28s)

Cleaning up the bundler cache.

Building jekyll site
Setting up jekyll environment variables

Configuration file: /tmp/build_8f7855ad60566729b1df6d252a638e1e/xuanxu-spaceup_bcn-82ad008/_config.yml

Source: /tmp/build_8f7855ad60566729b1df6d252a638e1e/xuanxu-spaceup_bcn-82ad008

Destination: /tmp/build_8f7855ad60566729b1df6d252a638e1e/xuanxu-spaceup_bcn-82ad008/_site

Incremental build: disabled. Enable with --incremental

Generating...

bundler: failed to load command: jekyll (/tmp/build_8f7855ad60566729b1df6d252a638e1e/xuanxu-spaceup_bcn-82ad008/vendor/bundle/ruby/2.3.0/bin/jekyll)

Errno::ENOENT: No such file or directory @ utime_internal - /tmp/build_8f7855ad60566729b1df6d252a638e1e/xuanxu-spaceup_bcn-825ad008/_site/bin/erb
/tmp/build_8f7855ad60566729b1df6d252a638e1e/xuanxu-spaceup_bcn-85ad008/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.1/lib/jekyll/static_file.rb:149:in `utime'
````

**Comment by smithtimmytim** [comment] 2016-09-06 04:31
I'm also having this issue on Heroku.

**Comment by parkr** [comment] 2016-09-08 17:28
@smithtimmytim Were you able to fix this particular problem by adding `bin` to your `exclude` in `_config.yml`/

**Comment by smithtimmytim** [comment] 2016-09-08 17:44
@parkr Yep. That was the fix for me.

**Comment by stomar** [comment] 2016-09-08 17:51
As @Crunch09 pointed out in #5334, this problem is caused by #4640.

More specifically, it's caused by a changed handling of symlinks in non-production JEKYLL_ENV environments (namely keeping them now as symlinks in the generated `_site` instead of copying the target file as before), and the fact that Heroku seems to add some(?) symlinks to the site (in `bin`) that break when copied to the `_site` dir.

Besides by excluding the `bin` dir (see above), the problem can also be solved by setting JEKYLL_ENV to `production` for the build (see #5334):

```
JEKYLL_ENV=production jekyll build
```

In production, symlinks are "converted" to proper files (as also in development before), and broken symlinks will not occur.

**Comment by parkr** [comment] 2016-09-09 21:14
@envygeeks The offending code from 0f74db413110ae7cb435bbd2d7f21a2918dd9cfe is:

```ruby
File.utime(self.class.mtimes[path], self.class.mtimes[path], dest_path)
```

Could this issue be fixed by just checking whether it's a symlink?

```ruby
File.utime(self.class.mtimes[path], self.class.mtimes[path], dest_path) unless File.symlink?(dest_path)
```

**Comment by envygeeks** [comment] 2016-09-09 21:21
@parkr Yes, and on top of that touching the symlink will update it's times as well.  Should I ship a pull?

**Comment by parkr** [comment] 2016-09-16 20:30
> @parkr Yes, and on top of that touching the symlink will update it's times as well. Should I ship a pull?

@envygeeks Yes please!

**Comment by parkr** [comment] 2016-09-28 23:58
If you are still having this problem, please try #5427 to see if that fixes it.

**Closed** 2016-09-29 20:26 UTC
Labels: bug
