### ISSUE TITLE
[Discussion] The Jekyll-Bundler marriage

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#5684] opened 2016-12-24 03:03 UTC
Hi Guys.
I've been seeing numerous instances of users having issues with Bundler and Jekyll in our support-forum and Issues here. All of those arise from having to install Bundler separately and prepend jekyll commands with bundle exec.
So this discussion is about resolving this hurdler to an extent.

I propose:
- add 'Bundler' as a dependency
- internally prepend 'bundle exec' to all jekyll commands

### Add 'Bundler' as a dependency
By adding Bundler as a `runtime_dependency` it will be installed automatically along with Jekyll gem.  
So no more `cannot load: "bundler"` errors..  
(I already opened a PR to this effect)

### Rewire Jekyll Executable
In theory, it would be better if we add `bundle exec` to `exe/jekyll` so that all jekyll commands will be thenceforth automatically run as `bundle exec jekyll [command] [...]` even if the user enters `jekyll [command] [...]` in their console.  
We could additionally check for Gemfile's absence and fallback to legacy execution to support older sites.

I hope this is not major enough to be put off till `v4.0`

--
/cc @jekyll/core, @jekyll/ecosystem, @jekyll/stability

**Comment by DirtyF** [comment] 2016-12-24 10:06
Isn't this a duplicate of https://github.com/jekyll/jekyll/pull/5660 ?

**Comment by ashmaroli** [comment] 2016-12-24 10:11
not a duplicate.. but rather a superset of the same.. I forgot to reference that PR when I added the section on "Add Bundler as a dependency" in the first comment..

**Comment by evolve2k** [comment] 2016-12-26 23:05
Sounds good to me. Should make things simpler for people coming to the ecosystem.
👍

**Comment by nickmccurdy** [comment] 2016-12-30 03:09
Doesn't Rails do something similar with its executable?

**Comment by envygeeks** [comment] 2016-12-30 03:39
AFAIW Rails only shims your local executables within your bin directory, and also within a configuration file, of which I think you can disable entirely.  I've not tried in years but you used to be able to do it.

**Comment by parkr** [comment] 2017-03-31 05:06
We need to be able to support running Jekyll without a `Gemfile`, so I don't think we can rely on Bundler here, which has a strict reliance on the existence of a `Gemfile`. Thanks for starting the discussion!

**Closed by parkr** 2017-03-31 05:06 UTC
Labels: discussion
