### ISSUE TITLE
github-pages ProTip doesn't format code

### ISSUE THREAD

**Issue by gagern** [jekyll/jekyll#5506] opened 2016-10-22 01:52 UTC
The documentation at https://jekyllrb.com/docs/github-pages/#deploying-jekyll-to-github-pages looks fairly broken, since the ```` ```ruby … ``` ```` block doesn't get formatted as code. In particular, it doesn't get rendered across multiple lines, so knowing where the line breaks are supposed to be is tricky. I guess that's because of the mix between HTML and Markdown, but I'm not sure.

/cc @jekyll/documentation

**Comment by pathawks** [comment] 2016-10-22 01:59
Thank you for bringing this up. :+1:
This is a known issue that we are currently working to fix.

Duplicate of #5435

**Closed by pathawks** 2016-10-22 01:59 UTC
