### ISSUE TITLE
Content of a file under css/ copied incorrectly

### ISSUE THREAD

**Issue by jleeothon** [jekyll/jekyll#5296] opened 2016-08-28 11:02 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

**Note** working on a trusty-64 Ubuntu vagrant machine.

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

Using Jekyll 3.2.1, I have my site with two dummy posts, my own layout. No plugins except minima.

Created a css directory ([documentation](https://jekyllrb.com/docs/structure/) says that files under other directories e.g. css, are copied verbatim). Created one file `style.css`.

Built site using:

```
jekyll build --source blog --destination etc/everywhere --baseurl /blog
```

Checked `etc/everywhere/css`. The expected file is found there.

Changed `css/style.css`. Rebuilt using the same command.

(Note however that `etc/everything` is *not* under `/etc`. It's a directory structure used by another project.)

## The Output I Wanted

I would expect that the new version of `css/style.css` is copied into the destination directory. However, it hasn't changed.

If I change the filename to e.g. `css/style2.css`, we effectively find the expected output file `etc/everywhere/css/style2.css`.

**This might be important to find the issue:**

0. if I delete the output file `etc/everywhere/css/style.css`
0. make a change to the source `css/style.css`
0. rebuild using the command above,
0. *then we see the old version* of style.css (before changes in the previous step) in `etc/everywhere/css/style.css`.

I suppose that the content is being cached somewhere and regenerated with the cache instead of the newer file.

**Comment by ayastreb** [comment] 2016-08-29 13:58
Hi @jleeothon
do you have your blog source code available somewhere?
I've tried to reproduce it locally with a new jekyll setup and it works correctly, updating the file each time.

what happens if you run `jekyll serve --source blog --destination etc/everywhere --baseurl /blog` and change the file? Is it re-generated?

**Comment by jleeothon** [comment] 2016-08-30 07:37
It's a private repo although it doesn't have anything sensitive at all yet so it's okay if I'll share it with you temporarily. Please find an invitation within the next minutes.

**Comment by jleeothon** [comment] 2016-08-30 07:53
Additionally, there's something funky that I notice about the resulting response of `localhost:4000/blog/css/some-file.css` after it's (manually) rebuilt.

- Create a file `style-new.css` under `css`.
- Build with `jekyll build --source blog --destination etc/everywhere --baseurl /blog`
- Serve with `jekyll serve --source blog --destination etc/everywhere --baseurl /blog --host 0.0.0.0` (the `--host` parameter is apparently necessary since I work in a VM (according to [this SO link](http://stackoverflow.com/questions/27617217/cannot-reach-jekyll-server-on-vagrant-from-outside))
- Check `localhost:4000/blog/css/style-new.css` in the browser. It looks as expected:

<img width="417" alt="screenshot 2016-08-30 09 41 20" src="https://cloud.githubusercontent.com/assets/6202537/18080764/162d38b4-6e97-11e6-91f0-3867ab9b8219.png">


- Change the file (i.e. change the list-style from the example).
- Generate the file again with the same command (`jekyll build --source blog --destination etc/everywhere --baseurl /blog`).
- Check the file again in the browser. Looks off:

<img width="425" alt="screenshot 2016-08-30 09 45 52" src="https://cloud.githubusercontent.com/assets/6202537/18080776/272592f6-6e97-11e6-9cbc-0414d8aaa694.png">


I tried figuring out what the funky symbols at the end are, e.g. by doing:

```sh
curl http://localhost:4000/blog/css/style2.css > response.txt
```

Then I checked my text editor, with non-printable characters shown, but it doesn't show anything weird at first sight:

<img width="258" alt="screenshot 2016-08-30 09 51 11" src="https://cloud.githubusercontent.com/assets/6202537/18080818/502d7998-6e97-11e6-988b-bfcfb892958d.png">

**Comment by ayastreb** [comment] 2016-08-30 08:57
Hi @jleeothon 
thanks for sharing the code! I've checked it out and tried to build locally (macOS) and it works ok, the files are updated and no extra characters.
So I'd guess the problem is somewhere in the VM.
What is your host OS? And how do you update the files - from host system or from inside the VM?

**Comment by jleeothon** [comment] 2016-08-30 22:02
AHA. Seems that if I modify the file directly in the VM, it is regenerated correctly.

**Some details about the environment**

It's a Vagrant / Virtualbox VM with `ubuntu/trusty64 (virtualbox, 20160816.0.0)`, .

I have a directory shared from my host VM (OS X 10.11.6) and I edit the files from the host system (with Atom).

**Steps with more detail**

- Run `jekyll serve --source blog --destination etc/everywhere --baseurl /blog`.
- Change the css/style.css file with vim inside the VM.
- Notice that the file has been automatically regenerated (`jekyll serve` logs `Regenerating: 1 file(s) changed at 2016-08-30 21:47:39 ...done in 0.08118072 seconds.`) (Wait, I thought one had to use `jekyll build --watch` for this..?—anyway, I hadn't been using it for simplicity).
- Run `curl http://localhost:4000/blog/css/style.css`. See the right version of the file (yay!).

Repeat the steps from above, modifying the file from the host machine + Atom. Two differences:

- The `jekyll serve` log does not show the `Regenerating: 1 file(s)...` line.
- In the last step, the response doesn't match what the file now has (a consequence of the above, safe to say).

The modified date seems okay...

```sh
$ ls -l --time-style=full-iso  blog/css/style.css 
-rw-r--r-- 1 vagrant vagrant 125 2016-08-30 21:56:53.000000000 +0000 blog/css/style.css

$ touch blog/css/style-new.css 
$ ls -l --time-style=full-iso  blog/css/style.css 
-rw-r--r-- 1 vagrant vagrant 125 2016-08-30 21:57:09.000000000 +0000 blog/css/style.css

$ # Now modify the file from Atom
$ ls -l --time-style=full-iso  blog/css/style.css 
-rw-r--r-- 1 vagrant vagrant 122 2016-08-30 21:57:25.000000000 +0000 blog/css/style.css
```

**Comment by ayastreb** [comment] 2016-08-30 22:17
That looks like VM/host file system synchronization issue.
Do you use Vagrant only for Jekyll? Jekyll works perfectly on MacOS, you can just build/serve it from you local system.

**Comment by jleeothon** [comment] 2016-08-30 22:22
Indeed it could be!... I don't use any other project that requires monitoring files. (Also, I don't use `jekyll serve` for this particular project.)

THANKS!

If you deem right, we can close this issue, unless you may want to ask me to try anything out, for purpose of collecting some information...

**Comment by ayastreb** [comment] 2016-08-30 22:28
If it works for you - you can close the issue!
I don't think we can get any more information, file sharing between host and VM is always tricky and definitely not related to the Jekyll project 😄

**Closed** 2016-08-30 22:30 UTC
