### ISSUE TITLE
Needlessly Inconsistent Plugin Syntax for Collections vs Posts

### ISSUE THREAD

**Issue by Lewiscowles1986** [jekyll/jekyll#3806] opened 2015-06-20 16:50 UTC
Hi, probably a feature request / modification request. 

Firstly, I have only just started with Jekyll, I have read the docs, and even tried to contrib my own additions, but I found the pagination to be too limited to be useful in any context I can imagine. Also indexing of the site needs improvements, so I wrote my own plugins, and will continue to work on that, releasing what I can GPL. 

For pagination, my plugin is cool, and it works, which is amazing; but I noticed that collections are a bit of a pain to work with from plugins, and liquid (why can't they be aliased like posts and pages are?). I also know I have read they are not "complete" or release ready, or whatever the terminology was, so I would like to throw a suggestion into the mix to simplify the generation / inner-workings. I looked through the Jekyll source code, and it looks like pages, posts and collections are all very different, and I cannot think why.

Anyway. Aside from this grumble, which I have worked around; there are other issues, such as `date` needing to be called `pub_date` to be receivable in the lquid template when looping over collections, and I cannot generate an excerpt (literally it gives me the entire contents of the collection item)... I have read several issues, but none seem to tackle any of my issues directly...

I would really love to be able to work with this build system, as the static output of Jekyll is hard to hack, easy to scale, it's fast etc, but I think consistency could be a great way to make this easier to work with, extend and contribute towards.

Happy to receive any advices, links to guides etc, and critique on my plugins.

**Comment by envygeeks** [comment] 2015-06-20 17:01
1. Pretty sure they are aliased, _albums would be site.albums, if that's not an alias and easy way to get at a collection then the issue is not really on our end, the docs actually clearly state that:  http://jekyllrb.com/docs/collections/#liquid-attributes

2. They are different because they were built at 2 different times and one does not just break working code to add in new not battle tested code.  That's a horrible way to approach programming.  That is in the works to be fixed now that collections have taken their stance and a quick search would find: https://github.com/jekyll/jekyll/pull/3690

**Comment by Lewiscowles1986** [comment] 2015-06-20 21:05
Hi again @envygeeks,

Thanks for your response. I think perhaps my post was not clear enough, so I will use the numbered bullet points you produced to answer, hopefully clarify...

1) I think maybe I wasn't clear on this. The liquid and API for plugins, should have a similar syntax! There is a lot of cross-over, but some areas there is none. Accessing site.albums is useless in the liquid front-matter; in fact it's worse than useless. It means we (Jekyll site dev's, which I accept I am new to) need to create more pages to use, and link to collections, rather than use our smarts to craft plugins which use a single template to leverage generation. To argue against this, is simply to argue for more effort. I get it, managers love the effort givers, except they don't... They love the achievers, which has nothing to do with effort. It's fantastic to be able to loop through different collections in different files, but actually, using an include to a single loop which takes information from a pages front-matter, means you can create the same pages faster!

As an example the incredibly poor pagination that currently exists, is programmed into a corner using posts; requires a special setting for the first page, and for the template page to be called index.html... Personally I thought the built-in pagination was bugged, but as I realized my use-case was different, I thought I'd craft something everyone could use, and I've linked it in my issue / complaint / suggestion to gather feedback on ways to improve it.

Even looking at standard post-only pagination, it has numerous online complaints, some how-to guides, and a few issues on here, which could more easily be avoided by having a common, more abstract pagination provider, which I have written as a plugin, in less lines, which is less restricted, but I accept needs work. This accomplishes a lot of the things I wanted to do. It can do exactly the same as I was doing with the paginator plugin, and saw others complaining about, but it fixes some of the bugs / undesirable work-flow.

Again happy to take advice on this, if there is a way to use less code than I am using, or to work more efficiently, I am all ears; as I was with the Ubuntu guide; but I am not willing to do more work than is necessary, because of a poor design. I am an experienced programmer; I can craft an alternative if Jekyll is insufficient, but as with all experienced programmers, I'd rather learn about someone elses and adjust my workflow, so long as it represents less effort than rolling my own...

2) Lets address point two on a few fronts. 

Firstly

 > They are different because they were built at 2 different times

That is the worlds worst excuse for having two things with shared concerns, not sharing a common code-base. While I accept Jekyll is an open-source project, and probably millions of people are happy with simple blog functionality, which it provides; this is also the area it has the most competition in, and Jekyll is not the most mature for. In terms of static site generators, from my research `Jekyll is the best out there right now!`, mainly because of the ease with which we can bring solutions from other projects. It has a huge user-base, but there are still people jumping back to non-static platforms, and trying competitors, blogging against Jekyll because some basic patterns don't exist YET (I have a list, some of which I have developed for in Jekyll by porting existing code, some of which are ongoing concerns). 

As you say, pages, posts and collections were implemented separately, I recognized that, I even mentioned it, but at some point, it will be too much effort to continue with, or Jekyll will suffer as a result of not standardizing... I Believe to follow your lead on #3690, #3169 attempts to approach this, and was the original to take the approach of documents as replacements for posts (No idea why 3690 was linked, as my complaint is about documents within collections being different to posts, which work fine, so it is literally the worst choice that could have been made to solve the problem).

Secondly

 > one does not just break working code to add in new not battle tested code.

Whilst I appreciate the dedication to not breaking your project, this is quite frankly nonsense, and besides the point of using base classes, which actually reduce the necessary tests, and increase code-base stability because of the shared code... 

WordPress dev's try this all the time to promote their clique-ish behavior. They push bland, poorly engineered solutions to inflate features, whilst ignoring their users, safe in the knowledge that some businesses feel stuck with them, and can download free, often poorly written, or pay a third party for bespoke or off-the-shelf plugins. They broke their DB a few months ago, because their `battle testing` was insufficient, they had too much spread and lacked the spinal column to tell users to simply use UTF8! 

Just the same as Jekyll has many reported bugs, some because these separate, yet similar areas do not share a common base; and because they are so similar; good programmers, and even logical thinkers, cannot work out why there are such inconsistencies that are not documented; other than a smattering of issues on github!

> There should be a huge Notice on collections, you have to use `pub_date` instead of `date` to use in liquid... Why? Oh because we thought we would become needlessly specific over what `date` meant, and ensure you write code for both collections and posts. 

Some helpful reading...

[Semantic versions](http://semver.org/) and [DRY] https://en.wikipedia.org/wiki/Don't_repeat_yourself), both cover changing code, and some basic best-practices that fit into what I am advocating and explain the complaint. Not all changes break, and there are good ways to communicate to developers and users which ones will. Basically, `IT IS ABSOLUTELY IS OKAY TO BREAK A THIRD PARTIES CODE, AND EVEN YOUR OWN CODE FOR PROGRESS!!!`. Of course you should do your best to manage changes and expectations from users; maintain a well-tested release cycle. As long as functionality is not lost; you document the changes, and communicate them clearly. Merged code blocks, and building from base-classes, as long as they are an improvement in terms of code maintainability, new features, or improved work-flow, and / or any abstract benefits specific projects may define is perfectly acceptable... 

I Hope you don't think I am targeting any of this at you, or being petulant, but none of the follow-up comment seemed related to the issue I raised, and the two points of point two seemed really bad. 

Thanks so much for bearing with me, and hopefully we can find a mutual understanding

**Comment by envygeeks** [comment] 2015-06-20 21:47
Come back when you can be constructive, we are not required to take your abuse.

**Closed** 2015-06-20 21:47 UTC

**Comment by Lewiscowles1986** [comment] 2015-06-20 21:57
Really? I'd be interested to know who `we` refers to, and what you specifically find abusive.

**Comment by envygeeks** [comment] 2015-06-20 22:08
You have a mother and father to teach you what is right and wrong, I am not either one of them.

**Comment by Lewiscowles1986** [comment] 2015-06-20 22:15
I ask because every time, when I have read your comments I have found them rude, needlessly pedantic, childish, and technically lacking. You fail to recognize any viewpoint but your own as valid. 

As mentioned in my rather large response, the work I am trying to advance is not just my own use-case, it is backed by issues, blog-posts and complaints against a project we both would like to help.

My list of `issues` with your interaction with me via GitHub, because I am interested in solving this little problem you are having!

Despite Jekyll 3.0 not being released you advised me to modify the guide I wrote, targeting the unreleased Jekyll 3.0; referencing potential dependencies, which won't work until 3 is released, and are problematic with the current build (see issues for complaints around not using node-js).

You also took issue with a guide specifically aimed at long-term-support software, for reasons it was only compatible with that long-term release, and you felt people may wish to add-in additional software which was not the remit of the guide, or any of the current Jekyll guides. Despite me giving my reasons for targeting LTS, one of which being it is what a lot of businesses use because of their perceived `Long-term` stability, you offered little more than the petulance you display here.

Now in this issue, you either have not read, or understood what I was posting, which I attempted to offer further insight into, because I realize I sometimes get over-excited and ramble... Instead of asking "what do you mean" you guesstimated some advice based upon an incorrect assumption; which my further post attempts to resolve...

Along with this you posted two pieces of utter nonsense, which yes I called you on, because developers posting nonsense do cause real damage in communities, propagating myths that hold software back.

Now be a grown up, and either point out what I have said that is `abuse`, rebut my points, or remove yourself from the conversation. Personally I don't want to have to make time for your tantrums, or places your parents should have educated you out of, which if your twitter feed is anything to go by are a sustained state that you persist in.

**Comment by envygeeks** [comment] 2015-06-20 22:28
You're trying too hard and I'm not new to the internet, thanks for playing the game but you lost.
