### ISSUE TITLE
[Docs]: Ruby version 2.5 doesn't work for Bash on Windows

### ISSUE THREAD

**Issue by wolf271bertelsmann** [jekyll/jekyll#9160] opened 2022-10-18 10:22 UTC
## Motivation

I think I found a part in the documentation that isn't correct. On the page "docs/installation/windows/#installation-via-bash-on-windows-10" it says that you should install ruby2.5. But after that on my machine the command `gem install jekyll bundler` crashed.

## Suggestion

I could solve the problem by using ruby2.6.

**Comment by ashmaroli** [comment] 2022-10-18 13:11
Hello @wolf271bertelsmann,
Do you have any error reports from the crash?

I would like to know what the cause was..?

**Comment by wolf271bertelsmann** [comment] 2022-10-19 07:00
Hello @ashmaroli,
thank you for your quick answer. You can reproduce the error with docker. 

Run the container: `docker run -it ubuntu:focal`

And do the following:

```bash
apt-get update -y && apt-get upgrade -y

# install packages that are missing in the image
apt-get install -y software-properties-common

# as from here we follow the documentation
apt-add-repository ppa:brightbox/ruby-ng
apt-get update
apt-get install ruby2.5 ruby2.5-dev build-essential dh-autoreconf

gem update

gem install jekyll bundler
```

The error message from the last command is the following 

```plain
Fetching: public_suffix-5.0.0.gem (100%)
ERROR:  While executing gem ... (ArgumentError)
    wrong number of arguments (given 4, expected 1)
```

This was nearly the same message, that I received when I installed jekyll on my Bash on Windows. And if you look at the output of the command `gem update`, you will often find the output `... requires Ruby version >= 2.6.0. The current ruby version is 2.5.0`.

**Comment by ashmaroli** [comment] 2022-10-19 07:15
@wolf271bertelsmann Thank you for getting back to this.
The reason behind this issue is technically not with Jekyll but with *a second-order* dependency.
Gem "public-suffix-5.0.0" requires Ruby 2.6 at minimum. But Jekyll doesn't need public suffix  v5 per se. v4.x will do fine. Jekyll depends on gem "addressable" which in turn depends on "public-suffix".

**Comment by wolf271bertelsmann** [comment] 2022-10-19 13:45
Hello @ashmaroli, 

I also think that this is not a problem of Jekyll as a software, but it is a problem of the published documentation. The reason is that the installation via bash on Windows 10 doesn't work as currently described. The web page says that the user should install ruby2.5, but with that you can't install Jekyll on a Windows 10 using the Ubuntu Subsystem. In my opinion it is necessary that someone updates the documentation and describes a way that really works.

And as I mentioned in the ticket description; It would be sufficient, if you use ruby2.6 instead of 2.5. So, you don’t have to rewrite the entire documentation.

**Comment by mohits** [comment] 2022-10-20 01:12
With Ruby 2.5 and Ruby 2.6 already marked as EOL and Ruby 2.7 reaching EOL in April 2023, do you think it's time to say that at least 2.5 isn't supported any more?

(I will also need to upgrade my Ruby for Jekyll which I am also a bit hesitant about 😆 for some reason)

**Comment by sc68cal** [comment] 2022-12-21 00:00
I have a windows machine and am using Ruby version `3.1.3` - via `rvm` and `cygwin` for Jekyll. I doubt recommending `cygwin` is a sane default, but we should at least recommend using `rvm` and give a ruby version of 3.1. Ruby 3.2 has some breaking changes that requires Liquid 5.x series so 3.1 is the latest we can go

**Comment by ashmaroli** [comment] 2022-12-21 12:21
> Ruby 3.2 has some breaking changes that requires Liquid 5.x series...

@sc68cal This statement doesn't make enough sense. Why do you think only Liquid 5.x will work on Ruby 3.2?

**Comment by sc68cal** [comment] 2022-12-21 19:32
> > Ruby 3.2 has some breaking changes that requires Liquid 5.x series...
> 
> @sc68cal This statement doesn't make enough sense. Why do you think only Liquid 5.x will work on Ruby 3.2?

https://github.com/jekyll/jekyll/issues/9094

**Comment by sc68cal** [comment] 2022-12-21 19:35
Specifically, Ruby 3.2 series removed a `untaint` method - https://github.com/Shopify/liquid/pull/1268 - running Jekyll with Ruby 3.2 blows up on that method being missing

**Comment by ashmaroli** [comment] 2022-12-22 05:42
@sc68cal Thanks for the context. This means we need to bundle a shim that defines the `taint`, `untaint` methods for compatibility.

**Comment by ashmaroli** [comment] 2022-12-22 05:47
@mattr-, @parkr Pinging you for inputs regarding handling missing `Object#taint` in Ruby 3.2.

**Comment by parkr** [comment] 2022-12-25 22:07
We should move the Object#taint question to another issue since this one seems to be about Ruby 2.5 vs 2.6/7 in the windows documentation?

**Closed** 2024-01-13 02:48 UTC
Labels: has-pull-request, documentation
