### ISSUE TITLE
Unquoted language code "no" not recognized in _config.yml

### ISSUE THREAD

**Issue by VikingKing** [jekyll/jekyll#9571] opened 2024-03-28 14:11 UTC
### Operating System

Debian 12

### Ruby Version

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]

### Jekyll Version

jekyll 4.3.3

### Expected Behavior

'lang: no' in _config.yml should sent the language to Norwegian.
Thus the html header should be
```
<!DOCTYPE html>
<html lang="no"><head>
  <meta charset="utf-8">
```
 

### Current Behavior

When setting the lang parameter in _config.yml, Jekyll seems to interpret the unquoted language code "no" (for Norwegian) as the English word "no" rather than a valid language code and uses the default of "en" instead.
```
<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
```

This unexpected behavior requires workarounds and suggests a potential bug.

### Code Sample

1. Create a new Jekyll project or modify an existing one.

2. In the _config.yml file, set the following:
`lang: no  # Unquoted language code does not work as expected 
`

3. Build or serve the Jekyll site. Observe the resulting language settings shown as:
```
<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
```
4. Change the _config.yml setting to:
`lang: "no" # Quoted language code works correctly`

5. Rebuild or reserve the site. The Norwegian language setting should now be applied.

```
<!DOCTYPE html>
<html lang="no"><head>
  <meta charset="utf-8">
```

Workaround is to use quotes around the language code. 
However this is not according to the documented syntax and does not seem to be needed with other language codes like french (fr).
 
 Please investigate whether this is a bug in Jekyll's handling of language codes or if this behavior is documented and requires a specific syntax.

**Comment by mkasberg** [comment] 2024-03-29 02:22
While perhaps surprising, this is [documented behavior of YAML](https://yaml.org/type/bool.html). `no` is treated as boolean false by YAML. As you've already found, quotes are the correct way to represent the string `"no"`.

So definitely not a bug in Jekyll itself, but were there any specific Jekyll docs that led you astray?

**Comment by mattr-** [comment] 2024-05-23 16:36
Closing since this is documented behavior in YAML.

**Closed by mattr-** 2024-05-23 16:36 UTC
