### ISSUE TITLE
How do I use absolute_url/relative_url in combination with link?

### ISSUE THREAD

**Issue by jameshfisher** [jekyll/jekyll#6521] opened 2017-11-05 18:53 UTC
# Steps to reproduce

```
{% link /assets/some_asset.png | absolute_url %}
```

# Expected behavior

It embeds an absolute link to `/assets/some_asset.png`.

# Actual behavior

```
Liquid Exception: Could not find document '/assets/some_asset.png | absolute_url' in tag 'link'. Make sure the document exists and the path is correct. in /_layouts/default.html
...error:
             Error: Could not find document '/assets/some_asset.png | absolute_url' in tag 'link'. Make sure the document exists and the path is correct.
             Error: Run jekyll build --trace for more information.
```

**Comment by DirtyF** [comment] 2017-11-05 18:56
duplicate of #5682

**Comment by ashmaroli** [comment] 2017-11-06 03:24
@jameshfisher As mentioned in our [docs for this filter](https://jekyllrb.com/docs/templates/#link), one cannot use liquid filters with this tag (as of current releases.)

**Comment by ashmaroli** [comment] 2017-11-06 10:17
## Workaround

Simply `capture` the path before-hand using the `link`  tag and then proceed to using Jekyll's URL Filters
```
{% capture page_link %}{% link assets/some_asset.png %}{% endcapture %}
{{ page_link | absolute_url }}
```
#### Notes:
- Variables created through `{% capture %}` are always strings.
- `link` is a sensitive tag. It'll abort processing the site if the requested file doesn't exist.
- the `link` tag is not very forgiving regarding leading slashes. To it, `assets/some_asset.png` is not equivalent to `/assets/some_asset.png`

**Closed** 2017-11-21 13:56 UTC
Labels: duplicate
