### ISSUE TITLE
Jekyll is not watching for changes on macOS High Sierra

### ISSUE THREAD

**Issue by pranavpr** [jekyll/jekyll#6392] opened 2017-09-28 08:10 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

1. Start Jekyll is watch mode
`bundle exec jekyll serve --force_polling`
2. Modify any post
3. Refresh the page in browser

## The Output I Wanted
Changes should reflect in browser automatically. It appears only when I restart the server. 

## Environment
* Jekyll 3.6.0
* ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
* macOS High Sierra

**Comment by DirtyF** [comment] 2017-09-28 08:30
Hi @pranavpr, 

Does it work without the `--force_polling` option?

**Comment by pranavpr** [comment] 2017-09-28 08:35
No, it doesn't. It used to work on macOS Sierra though. I updated my OS and it stopped working.

**Comment by DirtyF** [comment] 2017-09-28 08:46
Thanks for letting us know, anyone else having the same issue?

**Comment by perryprog** [comment] 2017-09-28 11:44
Working fine for me.

**Comment by ashmaroli** [comment] 2017-09-28 15:45
@pranavpr Are you using any plugins? Notably `jekyll-admin` older than `v0.6.0`?

**Comment by pathawks** [comment] 2017-09-28 16:14
Cannot reproduce.

**Comment by pranavpr** [comment] 2017-09-28 16:23
Well I created another site and it's working fine. I am not using any extra plugins. Not sure what's the issue. I'll investigate more and update with my results here.

**Comment by pathawks** [comment] 2017-09-28 17:26
I am going to close this for now, but please do reopen if you can isolate the problem.

**Closed by pathawks** 2017-09-28 17:26 UTC
Labels: not-reproduced

**Comment by camwiegert** [comment] 2017-10-10 20:51
@pathawks I'm having the same issue on High Sierra after nuking my setup and starting from scratch several times:

- My Jekyll config is very vanilla. No plugins and all defaults.
- The issue occurs both with bare `jekyll serve` and using the `--force_polling` flag.
- Rebuilds happen correctly everywhere except in my `_sass/` dir. (i.e. posts and pages still trigger a rebuild like normal)
- Some SASS modules trigger a rebuild while some do not. As far as I can tell, rebuilds aren't triggered on files named with a leading underscore and containing a dash. (e.g. `_site-header.scss`)

I assume this has [something to do with APFS](https://mjtsai.com/blog/2017/03/24/apfss-bag-of-bytes-filenames/)?

**My Environment**
- MacOS 10.13
- jekyll 3.6.0
- ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]

**Comment by pathawks** [comment] 2017-10-10 21:11
> * Some SASS modules trigger a rebuild while some do not. As far as I can tell, rebuilds aren't triggered on files named with a leading underscore and containing a dash. (e.g. _site-header.scss) The issue stopped when I removed the leading underscore. (site-header.scss)

OH! I suspect APFS is a Red Herring. I wonder if our SASS generator isn't setting its dependencies correctly.

@camwiegert This is a _very_ different issue from Jekyll not watching for changes. The very limited scope says to me that this is likely an issue with [**jekyll-sass-converter**](https://github.com/jekyll/jekyll-sass-converter)

**Comment by camwiegert** [comment] 2017-10-10 21:48
@pathawks I'd be surprised if this had nothing to do with High Sierra, considering that it wasn't an issue at all until I updated and [jekyll-sass-converter](https://github.com/jekyll/jekyll-sass-converter) hasn't had a release in ~1yr. You'd suggest I open an issue over there? Thanks for your input!

**Comment by pathawks** [comment] 2017-10-10 21:55
@camwiegert It would be easier for others to diagnose if you could provide a minimal repo that reproduces the issue.

Let's get a repo that reproduces this issue, open an issue at [**jekyll-sass-converter**](https://github.com/jekyll/jekyll-sass-converter) (feel free to assign me), and let's try to reproduce this with and without APFS.

**Comment by camwiegert** [comment] 2017-10-10 22:01
@pathawks Will do. Should be up shortly.
