### ISSUE TITLE
Front matter custom settings are not working

### ISSUE THREAD

**Issue by lhf-leo** [jekyll/jekyll#4076] opened 2015-10-29 18:33 UTC
I'm not sure about others, but the settings represent boolean are not working, for instance:
comments: true

It worked in 2.5, just updated to 3.0 and then it's down.

**Comment by envygeeks** [comment] 2015-10-29 18:42
Possibly related to: https://github.com/jekyll/jekyll/issues/4064 /cc @jekyll/core

**Comment by lhf-leo** [comment] 2015-10-29 18:56
https://help.disqus.com/customer/portal/articles/472138-jekyll-installation-instructions

following this instruction from disqus, and it was working great in 2.5,  but now is not. I think it might be different from 4064

**Comment by lhf-leo** [comment] 2015-10-29 19:42
ok, I don't know how to fix that, but I try out a way to cover it, add the settings you need in configure file(like comments and show_excerpt):

    defaults:
      -
        scope:
          path: "" # an empty string here means all files in the project
          type: "posts" 
        values:
          layout: post
          categories: Learning
          show_excerpt: true
          comments: true

**Comment by parkr** [comment] 2015-10-29 20:24
@envygeeks I think this is a dupe of #4064.

**Comment by aviaryan** [comment] 2015-11-04 04:43
+1 for this issue.
For me, all custom front-matter variables are ignored. I declare a variable `rtype: post` in all my posts but they are null when called from *default* layout as `page.rtype` .

**Comment by envygeeks** [comment] 2015-11-04 06:49
Closing this as a dup of #4064 please continue commenting there.

**Closed by envygeeks** 2015-11-04 06:49 UTC
