### ISSUE TITLE
Jekyll is stripping <html> and <head> tags

### ISSUE THREAD

**Issue by rohit01** [jekyll/jekyll#4648] opened 2016-03-10 21:56 UTC
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.1.2

###### What operating system are you using?

ubuntu 14.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Created a simple layout and a proper HTML page. The generated content is modified content. I find <html> and <head> tags are being deleted. I am presenting a simple scenario to replicate the issue.

**Layout File:**

```
$ cat _layouts/blank.html
{{ content }}
$
```

**Test HTML file:**

```
$ cat test.html
---
layout: blank
---
<!DOCTYPE html>
<html>
<head>
  <title>Hello World!</title>
</head>
<body>
<h1>Hello World!</h1>
<h1>Hello Paragraph!</h1>
</body>
</html>
$
```

###### What did you expect to see?

I expected to see the following content:

```
$ cat _site/test.html
<!DOCTYPE html>
<html>
<head>
  <title>Hello World!</title>
</head>
<body>
<h1>Hello World!</h1>
<h1>Hello Paragraph!</h1>
</body>
</html>
$
```

###### What did you see instead?

**Generated HTML file - test.html:**

```
$ cat _site/test.html
<body>


  <title>Hello World!</title>


<h1>Hello World!</h1>
<h1>Hello Paragraph!</h1>




</body>$
```

Jekyll should not delete tags automatically. CSS is breaking due to that.

**Comment by rohit01** [comment] 2016-03-10 22:57
It's a regression bug. I just downgraded to Jekyll 2.5.3 for my blog and it worked. Not using github builds anymore..

**Comment by aulneau** [comment] 2016-03-11 02:33
I'm encountering the same error currently on 3.1.2.

**Comment by parkr** [comment] 2016-03-11 03:09
Have you tried not using those plugins? We recently changed jemoji and jekyll-mentions.

**Comment by rubicus** [comment] 2016-03-11 07:48
I'm encountering the same thing. It works fine when I run jekyll locally on 3.1.2, but uploading to github pages causes it to just ignore the html and head tags and directly include a body tag instead. The page is based on the Jekyll documentation website, and the default layout includes top.html as the first thing it does. Default.html contains

`<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <title>{{ page.title }}</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="generator" content="Jekyll v{{ jekyll.version }}">
  {% feed_meta %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato:300,300italic,400,400italic,700,700italic,900">
  <link rel="stylesheet" href="/css/screen.css">
  <link rel="icon" type="image/x-icon" href="/icon2.ico">
  

  
  <script type="text/javascript">
   window.cookieconsent_options = {"message":"This website uses cookies to track you and get interesting google statistics!","dismiss":"Got it!","learnMore":"Tell me more!","link":"/cookies.html","theme":"dark-bottom"};
  </script>

  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
  

</head>
`

Whereas the corresponding generated html (on github pages) is
`body>


  <meta charset="UTF-8">
  <title>Blog home</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="generator" content="Jekyll v3.0.3">
  <link type="application/atom+xml" rel="alternate" href="rubicus.github.io/feed.xml" title="Rubicus' blog">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato:300,300italic,400,400italic,700,700italic,900">
  <link rel="stylesheet" href="/css/screen.css">
  <link rel="icon" type="image/x-icon" href="/icon2.ico">
  

  
  <script type="text/javascript">
   window.cookieconsent_options = {"message":"This website uses cookies to track you and get interesting google statistics!","dismiss":"Got it!","learnMore":"Tell me more!","link":"/cookies.html","theme":"dark-bottom"};
  </script>

  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
  
`

The entire codebase is available [here](https://github.com/rubicus/rubicus.github.io).

Running bundle update from the jekyll Gemfile (I don't have any gemfile in my project) updated:
`Installing addressable 2.4.0 (was 2.3.8)
Installing coderay 1.1.1 (was 1.1.0)
Installing kramdown 1.10.0 (was 1.9.0)
Installing mime-types-data 3.2016.0221 (was 3.2015.1120)
Installing unicode-display_width 1.0.2 (was 0.3.1)
Installing minitest-reporters 1.1.8 (was 1.1.7)
Installing rspec-core 3.4.4 (was 3.4.3)
Installing activesupport 4.2.6 (was 4.2.5.1)
Installing codeclimate-test-reporter 0.5.0 (was 0.4.8)
Installing sawyer 0.7.0 (was 0.6.0)
Installing octokit 4.3.0 (was 4.2.0)
Installing jemoji 0.6.1 (was 0.5.1)`

and after this, I also run into this program when running locally.

**Comment by rubicus** [comment] 2016-03-11 08:14
This certainly seems to be an issue with jemoji. I realized it was in my _config.yml, so I removed the jemoji-gem from there and everything worked perfectly again.

**Comment by mcomisso** [comment] 2016-03-11 09:02
The same error occurs also by activating **jekyll-mentions** plugin.

**Comment by benbalter** [comment] 2016-03-11 15:55
Working on a fix over in https://github.com/jekyll/jemoji/pull/37. The problem is that nokigiri, via HTML pipeline, expects a HTML fragment, but we're giving it a full HTML document.

**Comment by parkr** [comment] 2016-03-11 23:42
Closing as this is a problem with jemoji and jekyll-mentions. :cry:

**Closed by parkr** 2016-03-11 23:42 UTC
Labels: bug, has-pull-request, plugin-feature

**Comment by parkr** [comment] 2016-03-19 17:45
jemoji v0.6.2 and jekyll-mentions v1.1.2 have fixed this problem. Thanks for your patience!
