### ISSUE TITLE
The where filter fails on values with spaces in them

### ISSUE THREAD

**Issue by dominikwilkowski** [jekyll/jekyll#5586] opened 2016-11-17 03:06 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***macOS*** 10.11.6

---

- [x] It was another bug.

## My Reproduction Steps

Using Jekyll 3.2.1 with no error output.

I got a json file in the `_data` folder named `test.json` with the following content

```json
[
  {
    "name": "one"
  },
  {
    "name": "two-with-dashes"
  },
  {
    "name": "three with spaces"
  },
  {
    "name": "four_with_underscore"
  },
  {
    "name": "five+with%special#characters"
  }
]
```

Now when I try to use the `where` filter with each of those values via this liquid code:

```liquid
{% assign one = site.data.test | where: "name", "one" %}
one: {{ one }}<br>
{% assign two = site.data.test | where: "name", "two-with-dashes" %}
two: {{ two }}<br>
{% assign three = site.data.test | where: "name", "three with spaces" %}
three: {{ three }}<br>
{% assign four = site.data.test | where: "name", "four_with_underscore" %}
four: {{ four }}<br>
{% assign five = site.data.test | where: "name", "five+with%special#characters" %}
five: {{ five }}
```

I get this output:

```html
one: {"name"=>"one"}
two: {"name"=>"two-with-dashes"}
three: 
four: {"name"=>"four_with_underscore"}
five: {"name"=>"five+with%special#characters"}
```

Please note the key `three` with value `three with spaces` is not found by the where filter.

## The Output I Wanted

```html
one: {"name"=>"one"}
two: {"name"=>"two-with-dashes"}
three: {"name"=>"three with spaces"}
four: {"name"=>"four_with_underscore"}
five: {"name"=>"five+with%special#characters"}
```

**Comment by ashmaroli** [comment] 2016-11-23 10:47
I tested this on **Windows 7** and was able to obtain below on **both** `Jekyll 3.2.1 + Minima 1.2.0` & `J 3.3.1 + M 2.1.0`

![test](https://cloud.githubusercontent.com/assets/12479464/20558873/4bd8c520-b198-11e6-8443-25b182fe999d.png)

**Comment by ashmaroli** [comment] 2016-11-23 12:12
This is either a `macOS` specific bug, or no bug at all.. @dominikwilkowski have you tried upgrading to Jekyll `v3.3.1`

**Comment by dominikwilkowski** [comment] 2016-11-23 22:27
Thanks for testing this @ashmaroli.
I just updated to the latest version `3.3.1` and got the same issue.
My output for the above code is:

```
one: {"name"=>"one"}
two: {"name"=>"two-with-dashes"}
three: 
four: {"name"=>"four_with_underscore"}
five: {"name"=>"five+with%special#characters"}
```

That is macOS 10.11.6 with jekyll `3.3.1`.

**Comment by ashmaroli** [comment] 2016-11-24 04:18
@dominikwilkowski you're welcome. What version of Ruby are you running?

**Comment by dominikwilkowski** [comment] 2016-11-24 05:16
```
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

**Comment by Crunch09** [comment] 2016-12-06 20:50
I'm on macOS 10.12 and have the same ruby version but also couldn't reproduce this. @dominikwilkowski Are you still expierencing this? And if so could you share an example app or at least the JSON file? Maybe there is some sort of encoding issue going on?

**Comment by dominikwilkowski** [comment] 2016-12-07 22:32
Thanks everyone for following up.

I created a test repo: https://github.com/dominikwilkowski/jekyll-test

It turns out when I straight up make a very simple jekyll project, everything works well and I get no bugs. So I started drilling down and one by one eliminating the settings I have in my repo until I found the issue.

`jekyll-assets` screws with the data object.

I created two jekyll test in my repo above to show the bug. Now since this is a bug in the assets pipeline I opened [an issue](https://github.com/jekyll/jekyll-assets/issues/352) in that repo referring to this one too. Happy for you to close this now assuming it is purely an `jekyll-assets` bug.

**Comment by envygeeks** [comment] 2016-12-07 22:41
We don't "screw" with any of your data, matter of factly we go out of our way to avoid messing with Jekyll's objects to the point that we even store our own copy of the configuration.

**Comment by dominikwilkowski** [comment] 2016-12-07 22:42
Sorry for the wording :) No disrespect meant :)

**Comment by envygeeks** [comment] 2016-12-07 22:47
I wasn't offended, I always sound angry (even when I'm not, I'm weird) I was just pointing out what we try to do with Jekyll-Assets, though I will be looking into the issue because we don't go anywhere near Jekyll's filters, and we try to stay clear of Jekyll's data to the point we 1.) Isolate and 2.) Copy and alter our own objects.  We do add Jekyll#Configuration["assets"] but that's about it.  We do utilize Jekyll's filters for one of our internal plugins (to the point that we create a Liquid context with those filters inline) but we don't go anywhere near Jekyll's stuff.

I am absolutely intrigued as to how we could be triggering this, though based on the way I know my source works (unless there is a circumstance where I made a mistake -- which is a possibility) we'll probably end up back here as a Jekyll bug.

**Comment by ashmaroli** [comment] 2016-12-08 11:54
@envygeeks perhaps you could start [here](https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/processors/liquid.rb#L18-L22)
Its (perhaps one of many) where `:data` meets `Jekyll::Filters`

**Comment by envygeeks** [comment] 2016-12-08 12:02
@ashmaroli I already said that could be the spot that's causing the problem and like I said, if that is the problem, I won't be fixing it, because that makes this a bug in Jekyll or Liquid... there really isn't anything I can do about it, because Jekyll didn't start doing global stuff until I sent a pull a while back, and that was done ***before*** that was enabled which means I can't remove it until we have another major release.

The only way I will fix that... if it's the problem is if I'm using renderer wrong (but at the time that source was implemented it wasn't a problem, which means I might consider this a regression in Jekyll because it changed behavior in the middle of a minor release)

**Comment by dominikwilkowski** [comment] 2016-12-08 23:51
BTW can we remove the tag `not-reproduced` from this issue? Just makes me nervous that it might get overlooked by others.

**Comment by pathawks** [comment] 2016-12-09 01:38
According to `git bisect`, the commit that introduced this regression is 6245ddb14d0291ff7b581a937e804f871f792c30 which was introduced in #4555 by @timwis

**Comment by pathawks** [comment] 2016-12-09 04:27
The problem is with one of the dependencies of Jekyll-Assets.

https://github.com/jekyll/jekyll-assets/issues/352#issuecomment-265930822

**Comment by timwis** [comment] 2016-12-09 11:12
Shoot, did I screw up? Not a ruby guy but that PR seemed pretty simple and tested :-/

**Comment by ashmaroli** [comment] 2016-12-09 11:18
@timwis, you did not screw up.. vanilla Jekyll works fine with that PR incorporated.
PR #5649 reinforces your code to make it more robust..

**Comment by pathawks** [comment] 2016-12-09 13:07
@timwis Nope! You did not screw up.

This only breaks when `String.to_a` is redefined, which you have no control over.

I was only trying to provide context, not blame :+1:

**Comment by pathawks** [comment] 2016-12-22 21:20
This is [a problem with the **extras** gem](https://github.com/envygeeks/extras/blob/d5da6d59e63c002c48a164384687270be8252587/lib/extras/string.rb#L25-L30), not with Jekyll.

**Closed by pathawks** 2016-12-22 21:20 UTC
Labels: bug, upstream:issue

**Comment by dominikwilkowski** [comment] 2017-01-08 21:36
Filed upstream. Seeing that @envygeeks was part of this discussions I hope the gathered the issue didn't need much description :)

https://github.com/envygeeks/extras/issues/1

**Comment by envygeeks** [comment] 2017-01-09 00:38
It doesn't, I'll see if I can carve out time to figure fix it this week.
