### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by mslinn** [jekyll/jekyll#9050] opened 2022-05-02 13:46 UTC
## Summary
Enhance debug-level log output so identifying problem pages is easier. 

## Motivation
When log level `debug` is active, the following is output for every page:

```
  Logging at level: debug
    Jekyll Version: 4.2.2
Configuration file: /var/sitesUbuntu/www.mslinn.com/_config.yml
  Logging at level: debug
    Jekyll Version: 4.2.2
Configuration file: /var/sitesUbuntu/www.mslinn.com/_config.yml
  Logging at level: debug
    Jekyll Version: 4.2.2
Configuration file: /var/sitesUbuntu/www.mslinn.com/_config.yml
         Rendering: index.html
  Pre-Render Hooks: index.html
  Rendering Liquid: index.html
  Rendering Markup: index.html
Post-Convert Hooks: index.html
  Rendering Layout: index.html
```
The following information is redundant and should only be shown once per site:
 - configuration file 
 - log level
 - Jekyll version

When a file starts to be processed, its path should be output, then the rest of the information pertaining to that file should be indented, so it is apparent that it is all related.

Timing information per file should be shown, so pages that take a long time can be identified.

The time to perform each step for each page should be displayed, so steps that take a long time can be identified.

The following is output, with a timestamp, many times:
```
[2022-05-02 09:52:11] DEBUG Jekyll::Commands::Serve::Servlet is invoked.
```
The above is the only log output with a timestamp. 

Time intervals are much more useful than timestamps.

**Comment by ashmaroli** [comment] 2022-05-02 15:21
```
  Logging at level: debug
    Jekyll Version: 4.2.2
Configuration file: /var/sitesUbuntu/www.mslinn.com/_config.yml
  Logging at level: debug
    Jekyll Version: 4.2.2
Configuration file: /var/sitesUbuntu/www.mslinn.com/_config.yml
  Logging at level: debug
    Jekyll Version: 4.2.2
Configuration file: /var/sitesUbuntu/www.mslinn.com/_config.yml
```
The above repetition isn't Jekyll's default behavior but most definitely due to multiple plugins invoking the same trigger.
Will you be able to provide an accessible URL to the source repository?

**Comment by mslinn** [comment] 2022-05-02 15:25
It is a private repo on GitHub. Dozens of custom plugins. What trigger should I look for?

**Comment by ashmaroli** [comment] 2022-05-02 15:32
> What trigger should I look for?

Difficult to speculate but it could be as benign as calling `Jekyll.configuration(config)` multiple times.

**Comment by mslinn** [comment] 2022-05-02 15:50
I wonder if my [`jekyll_plugin_logger` plugin](https://github.com/mslinn/jekyll_plugin_logger) might cause the spurious output when it creates a new Ruby logger, like this:

```ruby
@logger = PluginMetaLogger.instance.new_logger(self, PluginMetaLogger.instance.config)
```

[This is the code](https://github.com/mslinn/jekyll_plugin_logger/blob/master/lib/jekyll_plugin_logger.rb) that implements `PluginMetaLogger`.

**Comment by ashmaroli** [comment] 2022-05-02 16:29
Regardless, the following method outputs log_level and Jekyll version:
https://github.com/jekyll/jekyll/blob/6855200ebda6c0e33f487da69e4e02ec3d8286b7/lib/jekyll/log_adapter.rb#L38-L47

Therefore, your predicament can be reproduced by the following code:
```ruby
Jekyll::Hooks.register :site, :post_read do |site|
  options = site.config
  site.pages.each do |page|
    Jekyll.logger.adjust_verbosity(options)
    Jekyll.configuration(options)
  end
end
```

---

I'm closing this ticket since it doesn't seem to be actionable.

**Closed by ashmaroli** 2022-05-02 16:29 UTC
Labels: feature
