### ISSUE TITLE
Collections break if "[" in path.

### ISSUE THREAD

**Issue by Yarn** [jekyll/jekyll#4067] opened 2015-10-28 00:00 UTC
### Steps to reproduce
jekyll b or jekyll serve a project that uses collections located at a path containing a left square bracket "[".
### Expected behaviour
Jekyll will function as it does with projects located at paths not containing a "[".
### Actual behaviour
No files or data corresponding to files in collections are generated.
### Notes
```{{ collections[0] }}``` results in something like
```{"output"=>true, "label"=>"things", "docs"=>[], "files"=>[], "directory"=>"/path/aa[/_things", "relative_directory"=>"_things"}``` even if files are present in ```/path/aa[/_things```
Tested on arch linux and windows with same results.

**Comment by parkr** [comment] 2015-10-28 00:02
Tangential question: when is a `[` used in a directory? Never seen that before, actually.

**Comment by envygeeks** [comment] 2015-10-28 00:03
I think this is a case for needing to pass around Pathname everywhere.  This is exactly why every one of my apps use Pathname for everything.

**Comment by parkr** [comment] 2015-10-28 00:04
How does Pathname fix this issue?

**Comment by envygeeks** [comment] 2015-10-28 00:05
Without seeing more data and testing it myself the assumption here is that there is a hiccup in the read and write because there is no escaping. Not that it should matter.  Pathname will escape everything for you and make it literal.

**Comment by Yarn** [comment] 2015-10-28 00:08
I had one at the start of the directory name for sorting, it's not something that normally happens. It took a good while to figure out why it wasn't working though.
Also of note, ], =, -, %, @ and # don't seem to cause issues.

**Comment by BlockWorld** [comment] 2015-10-28 00:40
That's very strange that "[" would cause issues but not "]"...

**Comment by envygeeks** [comment] 2015-10-28 11:59
I thought that too but it's a bug none-the-less if we can reproduce it.

**Comment by envygeeks** [comment] 2015-11-01 05:34
I am unable to reproduce this on my system (Ubuntu 14.04), can anybody else reproduce this?

**Comment by ducktyper** [comment] 2015-11-17 14:14
I found that using absolute path in Dir.glob was the problem.
Dir.glob identifies '[' as character set matching and I tested that it returns an empty array without ']'.
Having '{', '?', '*' in the absolute path also causes the similar issue.

Also tested that the results mentioned in Notes happen if entries are an empty set.

I fixed the issue here #4150 and also fixed one more similar case in cleaner.rb
I don't know how to add tests for this case so I didn't do it.

Let me know if there is any feedback to this commit.

**Closed** 2016-01-29 01:07 UTC
Labels: bug, help-wanted
