### ISSUE TITLE
HTML Canvas tag converted to <div>&lt;canvas id=canvas&gt;&lt;/canvas&gt;</div>

### ISSUE THREAD

**Issue by goktug97** [jekyll/jekyll#7962] opened 2020-01-05 11:21 UTC
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  Arch Linux    |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

```html
<div><canvas id=canvas></canvas></div>
```
Should be converted to canvas element

## Current Behavior
In page source it is converted as
```
<div>&lt;canvas id=canvas&gt;&lt;/canvas&gt;</div>
```

## Code Sample

Page is live at
https://goktug97.github.io/jekyll/update/2020/01/04/welcome-to-jekyll.html

``` yaml
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM

theme: minima
plugins:
  - jekyll-feed
```

EDIT:  Rendered correctly locally `bundle exec jekyll serve --watch`

**Comment by ashmaroli** [comment] 2020-01-05 12:07
This is probably an issue with `kramdown-1.17.0` which GitHub Pages uses.
Since this is not reproduced with Jekyll 4.0 (which uses `kramdown-2.1.0`), I'm closing this.

*TIP: When using GitHub Pages to build and host your site, always use the [`github-pages`](https://github.com/github/pages-gem) gem to develop your site locally so that you get the same output locally and remotely.*

## Workarounds
1. Build site locally with Jekyll 4.0 and upload **just contents of directory `_site`** to GitHub. (or)
2. Try using a different Markdown parser (e.g. [`jekyll-commonmark-ghpages`](https://github.com/github/jekyll-commonmark-ghpages))

**Closed** 2020-01-05 12:08 UTC

**Comment by goktug97** [comment] 2020-01-05 17:12
> Try using a different Markdown parser (e.g. jekyll-commonmark-ghpages)

This works
