### ISSUE TITLE
Getting Error: "Conflict: The following destination is shared by multiple files."

### ISSUE THREAD

**Issue by tamouse** [jekyll/jekyll#8522] opened 2020-12-25 02:14 UTC
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | MacOS 11.0.1           |
| `jekyll`         | Latest     |
| `github-pages`   | No     |
| `jekyll-category-pages` | 1.1.1 |

---

## Expected Behaviour

Expecting no conflict errors.

## Current Behavior

This is a terminal window log:

```
$ bin/jekyll s
Configuration file: /Users/tamara/Projects/Sites/recipes/_config.yml
            Source: /Users/tamara/Projects/Sites/recipes/source
       Destination: /Users/tamara/Projects/Sites/recipes/docs
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /Users/tamara/Projects/Sites/recipes/docs/category/salads/index.html
                     - _layouts/category_index.html
                     - _layouts/category_index.html
                    
                    done in 8.757 seconds.
 Auto-regeneration: enabled for 'source'
    Server address: http://127.0.0.1:4000/recipes/
  Server running... press ctrl-c to stop.
^C
```

Beyond this, I've little understanding of why or how this is happening.

The issue #8461 has the same error pattern, but the file listed is not in the site.includes.

## Code Sample

Repo: <https://github.com/field-theory/jekyll-category-pages>

**Comment by ashmaroli** [comment] 2020-12-25 07:22
@tamouse Thank you for reaching out to us.
The output you are seeing is not an error, but a warning.
You would see similar warnings if you were to run `bundle exec jekyll doctor` with an older version of Jekyll 4.

Coming to the topic on focus, my preliminary diagnosis is that the issue is with the category-pages plugin (*like you suspected as well*).
The primary issue according to the warning is that **two category pages generated by the plugin** have the same destination path **`docs/category/salads/index.html`**. Ideally, Jekyll would be able tell you which two source files are in conflict. That brings us to a secondary issue with the plugin.

The secondary issue is that the generated category pages have `_layouts/category_index.html` as their `relative_path` and therefore `path` attributes, which is not only *non-idiomatic* but also *non-intuitive*. Jekyll has a `--verbose` CLI switch that provides additional build output. From it the following would throw a user off-track:
```
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
         Rendering: _layouts/category_index.html
  Pre-Render Hooks: _layouts/category_index.html
  Rendering Liquid: _layouts/category_index.html
  Rendering Markup: _layouts/category_index.html
Post-Convert Hooks: _layouts/category_index.html
  Rendering Layout: _layouts/category_index.html
```

**Comment by ashmaroli** [comment] 2020-12-25 07:22
Closing as this is not a Jekyll bug.

**Closed by ashmaroli** 2020-12-25 07:22 UTC
