### ISSUE TITLE
Custom directory for includes

### ISSUE THREAD

**Issue by fniephaus** [jekyll/jekyll#3780] opened 2015-06-10 23:26 UTC
Hi folks,

I'd like to use a custom directory for `includes` like I can with `plugins`, `layouts` and `data_source`. Unfortunately, the `includes` directory is currently [hard-coded](https://github.com/jekyll/jekyll/blob/581dee7ba975e05622548fdfc785631dcff824f3/lib/jekyll/tags/include.rb#L104).
Do you mind if I'd hand in a PR for this?

Regards,
Fabio

**Comment by envygeeks** [comment] 2015-06-10 23:35
Hi; this is a duplicate of #2684 a more general issue on this topic.  I am going to close this in favor of that.

**Closed by envygeeks** 2015-06-10 23:35 UTC

**Comment by fniephaus** [comment] 2015-06-11 01:02
Thanks!
