### ISSUE TITLE
Error running Joomla import

### ISSUE THREAD

**Issue by darkedge3** [jekyll/jekyll#5447] opened 2016-10-05 10:30 UTC
Hi, I'm really keen to use this for some old sites, but getting the following error:

```
 syntax error, unexpected unary-, expecting keyword_do or '{' or '('
ruby -rubygems -e 'require "jekyll-import";
                ^

```

Any help much appreciated!

**Comment by parkr** [comment] 2016-10-05 21:58
Duplicate of https://github.com/jekyll/jekyll-import/issues/275.

**Closed by parkr** 2016-10-05 21:58 UTC
