### ISSUE TITLE
Jekyll error when starting - error in psych?

### ISSUE THREAD

**Issue by Behinder** [jekyll/jekyll#3281] opened 2015-01-10 15:41 UTC
This is output
```
/Users/sebastian/.rvm/gems/ruby-2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:4:in `<class:PsychResolver>': uninitialized constant Psych::Nodes (NameError)
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:2:in `<module:SafeYAML>'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:1:in `<top (required)>'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:131:in `<module:SafeYAML>'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:26:in `<top (required)>'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll.rb:26:in `<top (required)>'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/bin/jekyll:6:in `<top (required)>'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `load'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `<main>'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by parkr** [comment] 2015-01-10 20:41
Duplicate of https://github.com/dtao/safe_yaml/issues/72

**Closed by parkr** 2015-01-10 20:41 UTC
