### ISSUE TITLE
How can I set rouge theme to sublime monokai?

### ISSUE THREAD

**Issue by kasperdevs** [jekyll/jekyll#4536] opened 2016-02-17 19:34 UTC

**Comment by envygeeks** [comment] 2016-02-17 19:35
This is out of scope as it's not a bug in Jekyll. Please ask your question at https://talk.jekyllrb.com

**Closed by envygeeks** 2016-02-17 19:35 UTC

**Comment by parkr** [comment] 2016-02-17 19:43
@kasperdevs Agreed with @envygeeks – the answer to your question is that you have to add the `.css` to your site. You can't set it through Jekyll directly, you have to [install it via `rougify style monokai.sublime > css/monokai-rouge.css`](https://github.com/jneen/rouge#css-theme-options)
