### ISSUE TITLE
Incremental serve runs too many times (on scss changes?)

### ISSUE THREAD

**Issue by davethegr8** [jekyll/jekyll#4744] opened 2016-04-01 19:12 UTC
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.1

###### What operating system are you using?

OSX

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I've been seeing incremental generation cause changes to scss files cause many regenerations, sometimes even seeming to be infinite. There seems to be some correlation between the size of the css file and the number of times regeneration runs. The out of the box `main.scss` file causes 2-3 generation runs to happen, while importing bootstrap from source can cause the loop to seem to be infinite. Using `serve --watch` seems to not cause the issue.

* Setup new jekyll site `jekyll new test`
* Started the incremental server `jekyll serve --incremental -V`
* Opened `/css/main.scss`, saved file (no changes)
* `main.css` is (re)generated > 1 times

###### What did you expect to see?

Only 1 regeneration for each css file changed

###### What did you see instead?

Many more, and inconsistently as well.

**Comment by parkr** [comment] 2016-04-14 03:35
Duplicate of #4213. i believe this is a behaviour quirk in the incremental regenerator for now. /cc @alfredxing

**Closed by parkr** 2016-04-14 03:35 UTC
