### ISSUE TITLE
Add a way to override file extension

### ISSUE THREAD

**Issue by SoniEx2** [jekyll/jekyll#4193] opened 2015-11-27 21:35 UTC
I wanna turn .js files into .html files. A way to override the file extension would let me.

**Comment by parkr** [comment] 2015-11-28 02:19
Duplicate of #4182.

**Closed by parkr** 2015-11-28 02:19 UTC

**Comment by SoniEx2** [comment] 2015-11-28 02:28
Not quite. This one is less, uhh, specific. That one focuses on the .php extension, this one focuses on any extensions.

I don't want a config option but rather a frontmatter option. More flexibility that way.

**Comment by rebornix** [comment] 2015-11-28 02:57
@SoniEx2 I suppose what you are saying is you want to write content in JS and Jekyll helps you transform them into HTML like what it does for Markdown files? If so, Jekyll actually provides the ability to customise converters, check the [document](http://jekyllrb.com/docs/plugins/#converters).

**Comment by SoniEx2** [comment] 2015-11-28 03:01
Can't use plugins. I just need to shove the JS into an HTML layout really.

**Comment by envygeeks** [comment] 2015-11-28 05:11
".php" is the case example, it was later expanded to handle all cases, it's a duplicate.
