### ISSUE TITLE
Blank new blog generated with Jekyll-3.2.1 on Windows

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#5192] opened 2016-08-03 04:38 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll 3.2.1

---

- [x] I am on (or have tested on) ***Windows*** 7
- [x] I am running Ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]

---

- [x] I was trying to create a new blog.

## My Reproduction Steps

```
$ jekyll new my_blog
$ cd my_blog
$ bundle install
$ bundle exec jekyll s
(--redacted--)
generating...
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/default.html: No such file or directory @ rb_sysopen - /RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/default.html
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/page.html: No such file or directory @ rb_sysopen - /RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/page.html
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/post.html: No such file or directory @ rb_sysopen - /RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/post.html
  done in 0.702 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
(--redacted--)
  Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```
When I point my browser to http://localhost:4000/, all I see is a blank page

## The Output I Wanted

http://localhost:4000/ to show my_blog/index.html rendered with minima-1.0.1 theme

**Comment by parkr** [comment] 2016-08-03 04:50
Where are your gems installed to? What permissions are those directories? It's possible that you installed with `sudo` and Jekyll doesn't have permissions to read those files.

/cc @benbalter

**Comment by ashmaroli** [comment] 2016-08-03 06:21
My gems are set to path, so they can be accessed from anywhere on the windows machine.
I'm on an Administrator account, so full access to all files/folders.
`sudo` doesn't exist in windows. Just `Run as Administrator`

Why I think this is a version-specific bug:

- The files said to be missing in my first post above actually exists within the minima gem files.
- I had earlier successfully created a blog using **Jekyll 3.1.6**

The issue-4677 present in J3.2.0 was fixed in 3.2.1

**Comment by ashmaroli** [comment] 2016-08-03 06:23
If at least one other windows user reports the same problem, please assign this issue a `bug` label and `windows` label.

**Comment by envygeeks** [comment] 2016-08-03 08:11
Windows is reported yet those are very specific and common Linux paths in the log.  Regardless of the "/" that is clearly something looking in a Linux path.  There is a bigger problem somewhere if this can be replicated and it might not originate in Jekyll?

**Comment by sasivarnan** [comment] 2016-08-03 08:28
I am also facing the same issue, in command prompt (windows 10 - 64 bit )
I already tried `gem cleanup` and `bundle install`.
I am getting the same error when I try to do `jekyll serve` or `bundle exec jekyll serve`.

**Comment by ashmaroli** [comment] 2016-08-03 08:28
I've updated my original post to include the entire path as shown in the logs. Now, it should be easier to troubleshoot..

Specifically, the absence of the drive letter  after @rb_sysopen   

**D:**/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/default.html: No such file or directory @ rb_sysopen - /RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/default.html

**Comment by ashmaroli** [comment] 2016-08-03 13:46
Update: 
_If I copy the _layouts folder from minima gem to the root of the blog, I get the Output I wanted. Everything works like with Jekyll 3.1.6_

**Comment by benbalter** [comment] 2016-08-03 14:43
I suspect this is going to be traced to [this line](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/theme.rb#L46), either `File.realpath` (used to resolve symlinks) or the subsequent `Jekyll.sanitized_path` call.

**Comment by ashmaroli** [comment] 2016-08-03 14:52
But whats puzzling is why is it a bug for only `_layouts` instead of also `_includes`, and `_sass`

**Comment by mmistakes** [comment] 2016-08-03 15:25
Hitting something similar with `3.2.1` on Windows.

```
jekyll new test-site
cd test-site
bundle install

bundle exec jekyll build

Error reading file C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/minima-1.0.1/_layouts/default.html: No such file or directory
 - /Ruby200-x64/lib/ruby/gems/2.0.0/gems/minima-1.0.1/_layouts/default.html
Error reading file C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/minima-1.0.1/_layouts/page.html: No such file or directory -
/Ruby200-x64/lib/ruby/gems/2.0.0/gems/minima-1.0.1/_layouts/page.html
Error reading file C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/minima-1.0.1/_layouts/post.html: No such file or directory -
/Ruby200-x64/lib/ruby/gems/2.0.0/gems/minima-1.0.1/_layouts/post.html
```

Because the paths can't resolve the generated `_site` has no layouts, includes, or css applied and pages are blank.

**Comment by ashmaroli** [comment] 2016-08-03 15:50
@mmistakes, The solution may lie in solving the mystery behind the missing drive letter after `@ rb_sysopen - ` in the raises.

**Comment by parkr** [comment] 2016-08-03 17:54
@ashmaroli I think you're right – it's the missing drive letter. IIRC, `Jekyll.sanitized_path` removes the drive letter. We have a test for this on AppVeyor I think (`script/default-site`), so we should be able to replicate the issue there (I hope).

**Comment by ashmaroli** [comment] 2016-08-04 04:38
I added some changes to my local copy of Jekyll 3.2.1 based on #5195 and ran `bundle exec jekyll s --verbose` to check if the layouts_path had the drive letter dropped..


```
$ bundle exec jekyll s --verbose

  Logging at level: debug
Configuration file: C:/Jekyll Sites/my_blog/_config.yml
             Theme: minima
      Theme Source: D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1
    Layouts Source: D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts
         Requiring: kramdown
            Source: C:/Jekyll Sites/my_blog
       Destination: C:/Jekyll Sites/my_blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Error reading file D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/default.html: 
No such file or directory @ rb_sysopen - /RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/default.html
Error reading file D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/page.html: 
No such file or directory @ rb_sysopen - /RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/page.html
Error reading file D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/post.html: 
No such file or directory @ rb_sysopen - /RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layouts/post.html
... ...
```

So, I suspect the bug lies within `layout_reader.rb` bcoz the blog renders properly if the _layouts folder is additionally copied to blog root (debug still shows the layout sourced from minima, though)

**Comment by ashmaroli** [comment] 2016-08-04 08:15
I have traced that missing drive letter to `site.in_theme_dir(base, name)` in _layouts.rb_
In light of that I've come up with a rudimentary workaround to this issue:

```ruby
# lib/jekyll/layout.rb
# Replace Line 38 with:

@path = base + "/" + name
```

**Comment by sasivarnan** [comment] 2016-08-07 04:32
@ashmaroli Thanks for the workaround.

**Comment by ashmaroli** [comment] 2016-08-07 04:37
@sasivarnan you're welcome :smiley:

**Comment by patrickbense** [comment] 2016-08-12 03:31
I seem to be running into something similar, but on OSX. 

When changing into my projects directory I get this message:
```
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /Users/username/Documents/Projects/blog/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore all Gemfiles'.

Unknown ruby interpreter version (do not know how to handle): RUBY_VERSION.
```

I can build and serve the website and it appears to run just fine. The strange part is that there is no `_layouts` or `_includes` folders. It correctly builds the layout html into the static pages, but I can't for the life of me figure out where it's coming from.

Is this related at all? I can't find anything when searching for missing `_layouts` folder.

**Comment by envygeeks** [comment] 2016-08-12 03:33
@patrickbense There is no "_layouts" because Jekyl uses Gem based themes now. That is not a bug.

**Comment by patrickbense** [comment] 2016-08-12 03:53
Oops, I deleted my comment before I saw your response. Thanks @envygeeks, my bad!

**Comment by mvaneijgen** [comment] 2016-08-13 17:29
@envygeeks is there somewhere explained how everything works now? Because I like to overwrite certain layouts and includes, but I have no Idea where they are or how to edit them.

**Comment by DirtyF** [comment] 2016-08-13 23:58
@mvaneijgen it is supposed to be detailed on https://jekyllrb.com/docs/themes/ but I guess it's hard to know what files to overwrite without seeing the default structure. 'bundle show minima`may help  before you add your own files to Jekyll's root directory in order to overwrite them.

**Comment by sandys** [comment] 2016-08-15 05:06
+1 - this is the same issue we are facing. we are unable to create a new blog because of this :(

**Comment by rrongcheng** [comment] 2016-08-28 15:27
+1 I got same issue on my win8.1, and get it works now via the temporary fix provided by ashmaroli. Thanks @ashmaroli!

**Comment by lgh06** [comment] 2016-08-31 08:45
the same issue
`Error reading file C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layout
s/default.html: No such file or directory @ rb_sysopen - /tools/ruby23/lib/ruby/
gems/2.3.0/gems/minima-1.0.1/_layouts/default.html
Error reading file C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layout
s/page.html: No such file or directory @ rb_sysopen - /tools/ruby23/lib/ruby/gem
s/2.3.0/gems/minima-1.0.1/_layouts/page.html
Error reading file C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/minima-1.0.1/_layout
s/post.html: No such file or directory @ rb_sysopen - /tools/ruby23/lib/ruby/gem
s/2.3.0/gems/minima-1.0.1/_layouts/post.html`
windows 10 64bit cmd.exe

**Comment by lgh06** [comment] 2016-08-31 08:56
copy _layouts directory works for me...
I would use Mac instead....

**Comment by benbalter** [comment] 2016-08-31 13:12
This is being worked on, and should be fixed by https://github.com/jekyll/jekyll/pull/5256.

**Closed** 2016-10-05 18:34 UTC
Labels: bug, windows
