### ISSUE TITLE
[Bug]: Obsolete nodeJS version 

### ISSUE THREAD

**Issue by cryptrz** [jekyll/jekyll#9568] opened 2024-03-27 13:40 UTC
### Operating System

Github hosted

### Ruby Version

ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

### Jekyll Version

jekyll 4.3.3

### GitHub Pages Version

latest

### Expected Behavior

I expected the website to show the new blog post. It appears on te localhost version hosted on WSL, it doesn't on github-pages

### Current Behavior

After a git push for the website below, I get these messages: 
Website: https://cryptrz.github.io/
Github repo: https://github.com/[cryptrz/cryptrz.github.io](https://github.com/cryptrz/cryptrz.github.io)

Messages: 
![2024-03-27 14_37_30-Restore config · cryptrz_cryptrz github io@4ec8b9c and 7 more pages - Personal -](https://github.com/jekyll/jekyll/assets/68272257/14f2d0ac-3e34-4457-9522-5334f5a8b5ac)

It works perfectly on localhost, the new blog post appears. The git push failed many times

**Comment by mkasberg** [comment] 2024-03-29 02:30
This is not a bug in Jekyll.

Looking at [your logs](https://github.com/cryptrz/cryptrz.github.io/actions/runs/8459656881/job/23176393627#step:3:43), the reason for the failure is this:

```
nokogiri-1.16.3-x86_64-linux requires ruby version < 3.4.dev, >= 3.0, which is
incompatible with the current version, ruby 2.7.8p225
```

Your repository is [configured to use ruby 2.7](https://github.com/cryptrz/cryptrz.github.io/blob/0e35317ff4ef8e4ad1859f9c2f771fa0f4e72079/.github/workflows/pages-deploy.yml#L25). If Ruby 3.0.2 is working for you locally, updating your GitHub Action to use the same version of Ruby is likely to resolve the problem.

The warnings about deprecated NodeJS versions are similarly related to your own GitHub Actions config.

**Comment by mattr-** [comment] 2024-05-23 15:23
What @mkasberg says is correct. Since this isn't a bug in Jekyll itself, I'll close this issue.

**Closed by mattr-** 2024-05-23 15:23 UTC
