### ISSUE TITLE
Single word post title 'yes' causes: Liquid Exception: no implicit conversion of true into String in /_layouts/post.html

### ISSUE THREAD

**Issue by timhutton** [jekyll/jekyll#7514] opened 2019-02-02 22:30 UTC
## Environment

OS: Windows 10
Jekyll: 3.7.4
github-pages: 193

Code: https://github.com/timhutton/timhutton.github.io

## Behavior

With this post file:

```
---
layout: post
title: yes
---

Words go here.
```

I get an error:

```
C:\Tim\timhutton.github.io>bundle exec jekyll serve
Configuration file: C:/Tim/timhutton.github.io/_config.yml
            Source: C:/Tim/timhutton.github.io
       Destination: C:/Tim/timhutton.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Liquid Exception: no implicit conversion of true into String in /_layouts/post.html
jekyll 3.7.4 | Error:  no implicit conversion of true into String
```

If I change the title of the post, as follows:

```
---
layout: post
title: yes is not an allowed title
---

Words go here.
```

Then the build succeeds:

```
C:\Tim\timhutton.github.io>bundle exec jekyll serve
Configuration file: C:/Tim/timhutton.github.io/_config.yml
            Source: C:/Tim/timhutton.github.io
       Destination: C:/Tim/timhutton.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
                    done in 4.72 seconds.
 Auto-regeneration: enabled for 'C:/Tim/timhutton.github.io'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

Other post titles that cause amusing issues: ```false```, ```true```, ```no```, numbers (see #6319).

**Comment by pathawks** [comment] 2019-02-02 22:39
I am sure that our YAML parser is converting `yes` to a boolean. You can fix this by quoting the value: `"yes"`.

Why it is trying to cast it to a boolean is a more interesting/difficult question.

**Comment by timhutton** [comment] 2019-02-02 23:33
I notice that it doesn't happen if I have this line in my Gemfile:

```
gem "jekyll", "3.7.4"
```
instead of
```
gem "github-pages", group: :jekyll_plugins
```

**Comment by ashmaroli** [comment] 2019-02-03 07:36
The issue is independent of Jekyll version.
```
$ irb
irb(main):001:0> require 'yaml'
  => true
irb(main):002:0> YAML.load("layout: post\ntitle: yes\n")
  => {"layout"=>"post", "title"=>true}
```
```
$ irb
irb(main):001:0> require 'jekyll'
  => true
irb(main):002:0> SafeYAML.load("layout: post\ntitle: yes\n")
  => {"layout"=>"post", "title"=>true}
```

**Comment by ashmaroli** [comment] 2019-02-03 07:40
@timhutton Can you post the `--trace` output for the error?
It's possible that we can "coerce" `page.title` to be a string at all times internally.

**Comment by pathawks** [comment] 2019-02-03 07:43
> It's possible that we can "coerce" page.title to be a string at all times internally.

I’m not sure that would be a great solution to this problem if `safe_yaml` has already decided that `yes` actually meant `true`.
(Though at least the site would build)

It seems to me that this would need to be changed by the YAML parser.

**Comment by ashmaroli** [comment] 2019-02-03 07:49
@pathawks I agree that it is not the best solution. But then it is not `safe_yaml` that is behind the conversion. It's from Ruby's `yaml` itself. (See my comment above again)

Besides, the "break" is most probably in our plugins' Liquid templates where we're interpolating
`{{ page.title }}`. So, there's every chance that this ticket has to be transferred to elsewhere.

**Comment by ashmaroli** [comment] 2019-02-03 10:41
Based on the specs at https://yaml.org/type/bool.html, it looks like this behavior is intended from YAML.
So, I'm closing this ticket.

**Closed by ashmaroli** 2019-02-03 10:41 UTC
