### ISSUE TITLE
jekyll 3.2.1 | Error:  Operation not permitted -

### ISSUE THREAD

**Issue by hyesun03** [jekyll/jekyll#5419] opened 2016-09-26 15:28 UTC
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## The Output I Wanted
I was entered this command: `jekyll serve --watch --increment`
This is output:
`Configuration file: /Users/choehyeseon/Documents/hyesun03.github.io/_config.yml
            Source: /Users/choehyeseon/Documents/hyesun03.github.io
       Destination: /Users/choehyeseon/Documents/hyesun03.github.io/_site
 Incremental build: enabled
      Generating...
jekyll 3.2.1 | Error:  Operation not permitted - /Users/choehyeseon/Documents/hyesun03.github.io/_site/versions/lib/python2.7/UserDict.py`

**Comment by pathawks** [comment] 2016-09-26 15:46
I have cloned [your repository](https://github.com/hyesun03/hyesun03.github.io) locally and am unable to reproduce this issue; the site builds fine for me.

Have you successfully built the site in the past? Have you changed anything recently?

**Comment by hyesun03** [comment] 2016-09-26 16:13
recently I have reinstalled mac os. yesterday it was fine. I don't know what's wrong.. hmm

**Comment by hyesun03** [comment] 2016-09-26 22:44
1. reinstall mac os again. 
2. I rollbacked my repo. 

and now jekyll works well. hmm..

**Comment by pathawks** [comment] 2016-09-27 03:23
It sounds like things are working for you now.

I sm going to close this issue, but please do report back if you figure out what was causing the trouble.

**Closed by pathawks** 2016-09-27 03:23 UTC
