### ISSUE TITLE
Image produces 'invalid byte sequence in UTF-8' error

### ISSUE THREAD

**Issue by jputrino** [jekyll/jekyll#4276] opened 2015-12-21 20:23 UTC
This may duplicate #2592. Jekyll appears to be incorrectly interpreting images again (or still?).

Here's the trace:

```
Configuration file: /Users/putrino/openstack/f5-openstack-docs/_config.yml
            Source: /Users/putrino/openstack/f5-openstack-docs
       Destination: /Users/putrino/openstack/f5-openstack-docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: invalid byte sequence in UTF-8 in _includes/f5-os-lbaasv1/assets/lbaas-agent-status.png, included in m_install_lbaas_plugin_agent.md
/usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/tags/include.rb:133:in `rescue in render': invalid byte sequence in UTF-8 (Jekyll::Tags::IncludeTagError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/tags/include.rb:125:in `render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:112:in `render_liquid'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:255:in `do_layout'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/page.rb:116:in `render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:179:in `block in render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:177:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:177:in `render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:59:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:60:in `build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:35:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment] 2015-12-21 20:47
Please provide the corresponding Liquid.

**Comment by jputrino** [comment] 2015-12-21 21:01
This is the Liquid that threw the error:

{% include f5-os-lbaasv1/assets/lbaas-agent-status.png %}

**Comment by pathawks** [comment] 2015-12-21 22:50
Why are you including a PNG in Liquid?

**Comment by jputrino** [comment] 2015-12-21 23:06
I pretty much create images as PNG by default. I'm using Liquid for content re-use (I'm a tech writer) and figured it would work for images as well as text files. If that's not the case, no biggie, but I wanted to report it in case others tried to do the same and ran into the same error.

**Comment by pathawks** [comment] 2015-12-21 23:07
I am not asking why you have chosen the PNG format for images, I am asking why you are including a binary file in a text file.

**Comment by envygeeks** [comment] 2015-12-21 23:30
I'm going to assume this is about scopable assets, and include was not meant to solve that.  And if this is not about that, I have the same question: what is the end-game here? I'm going also throw in and say that the error here is not that it didn't work, it's that we didn't throw ourselves and ask what are you trying to do? Include is not meant to do that.  That's the bug IMO.

**Comment by parkr** [comment] 2015-12-22 01:05
> figured it would work for images as well as text files.

The `include` tag brings text files into other Liquid files – binary files are out of scope. It's not meant to bring in binary files and link to them in any way. I think the intended behaviour would be to output an `img` tag or something. If that is the case, the `include` tag will not be the proper tool to accomplish this job. Generally, folks create an image directory and bring it in using either the Markdown syntax or straight up HTML.

Thanks!

**Closed by parkr** 2015-12-22 01:05 UTC
