### ISSUE TITLE
YAML front matter block getting rendered

### ISSUE THREAD

**Issue by ilicmarko** [jekyll/jekyll#5576] opened 2016-11-14 09:01 UTC
Hi,

I encountered a really strange problem with Jekyll.

I wrote a post and it worked grate, then I send the document over facebook for linting, when I got the post back, downloaded it and placed it in my `_posts` folder.

When I ran the preview, the YAML block was render 

```
— title: Modeliranje CSS-a kao softverski inžinjer category: CSS date: 2016-11-13 14:44:00 excerpt: Videćemo da je vrlo bitno planirati svoj CSS kao što rade i softverski inženjeri. Crtanje UML dijagrama za CSS nije baš tako suludo. —
```
So I tried every single thing... **Please note: All other posts are normal...**

I copied the YAML from the other post (that was working)... Nothing...
All other markdown content was working normal.

Using _kramdown_
```
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
```

## Solution

I created a new file with same filename (renamed the old one), copied the **WHOLE** content to the new file ... **It worked!!!**

I really don't know how...

## Analysis

I was really happy that it worked, but I wanted to know why that original file didn't.
Things I ruled out:

- File name (same as the old one)
- File extension
- YAML block (copied the whole content)
- Content (as I said copied the whole content)

So the file worked before Facebook transfer, I took a look at metadata, because I know FB injects some:
```
_kMDItemOwnerUserID            = 501
kMDItemContentCreationDate     = 2016-11-14 01:51:57 +0000
kMDItemContentModificationDate = 2016-11-14 08:16:05 +0000
kMDItemContentType             = "public.data"
kMDItemContentTypeTree         = (
    "public.data",
    "public.item"
)
kMDItemDateAdded               = 2016-11-14 01:52:17 +0000
kMDItemDisplayName             = "2016-11-13-modeliranje-css-a-kao-softverski-inzinjer"
kMDItemDownloadedDate          = (
    "2016-11-14 01:51:57 +0000"
)
kMDItemFSContentChangeDate     = 2016-11-14 08:16:05 +0000
kMDItemFSCreationDate          = 2016-11-14 01:51:57 +0000
kMDItemFSCreatorCode           = ""
kMDItemFSFinderFlags           = 16
kMDItemFSHasCustomIcon         = (null)
kMDItemFSInvisible             = 0
kMDItemFSIsExtensionHidden     = 1
kMDItemFSIsStationery          = (null)
kMDItemFSLabel                 = 0
kMDItemFSName                  = "2016-11-13-modeliranje-css-a-kao-softverski-inzinjer"
kMDItemFSNodeCount             = (null)
kMDItemFSOwnerGroupID          = 20
kMDItemFSOwnerUserID           = 501
kMDItemFSSize                  = 4117
kMDItemFSTypeCode              = ""
kMDItemKind                    = "Document"
kMDItemLogicalSize             = 4117
kMDItemPhysicalSize            = 8192
kMDItemWhereFroms              = (
    "https://cdn.fbsbx.com/ ... really log link ...",
    "https://www.facebook.com/"
)
```
**Please not that I removed .md extension before getting meta data, because I didn't won't to render it on my blog.**

The new file I made, has much simpler metadata: 

```
_kMDItemOwnerUserID            = 501
kMDItemContentCreationDate     = 2016-11-14 08:18:48 +0000
kMDItemContentModificationDate = 2016-11-14 08:20:11 +0000
kMDItemContentType             = "dyn.ah62d4rv4ge8043a"
kMDItemContentTypeTree         = (
    "dyn.ah62d4rv4ge8043a",
    "public.data",
    "public.item"
)
kMDItemDateAdded               = 2016-11-14 08:18:48 +0000
kMDItemDisplayName             = "2016-11-13-modeliranje-css-kao-softverski-inzinjer.md"
kMDItemFSContentChangeDate     = 2016-11-14 08:20:11 +0000
kMDItemFSCreationDate          = 2016-11-14 08:18:48 +0000
kMDItemFSCreatorCode           = ""
kMDItemFSFinderFlags           = 0
kMDItemFSHasCustomIcon         = (null)
kMDItemFSInvisible             = 0
kMDItemFSIsExtensionHidden     = 0
kMDItemFSIsStationery          = (null)
kMDItemFSLabel                 = 0
kMDItemFSName                  = "2016-11-13-modeliranje-css-kao-softverski-inzinjer.md"
kMDItemFSNodeCount             = (null)
kMDItemFSOwnerGroupID          = 20
kMDItemFSOwnerUserID           = 501
kMDItemFSSize                  = 4114
kMDItemFSTypeCode              = ""
kMDItemKind                    = "Markdown"
kMDItemLogicalSize             = 4114
kMDItemPhysicalSize            = 8192
```

What do you people think about this, is it maybe the FB tags that broke the file?

**Comment by pathawks** [comment] 2016-11-14 16:08
What exactly do you mean when you talk about “Facebook transfer?” Can you describe this process?

Can you provide more detail? I'm not sure there is enough information here to reproduce the issue.
I suspect it may have something to do with character encoding.

**Comment by ilicmarko** [comment] 2016-11-14 17:20
I wrote an article, which worked full, then I sent it in facebook chat (drag & drop) to my friend to check the language... When she finish linting it, send it back the same way, and I didn't won't to work.

As I said its not the text it self because I copied everything from it (cmd + A) to a new file with same name and it worked.

**Comment by pathawks** [comment] 2016-11-14 18:04
Can you post the two files: the one that didn't work and the one that did?

**Comment by ilicmarko** [comment] 2016-11-14 18:18
Copy is the not working one... 
As you can see the above one is working great, but the bottom one (copy, from FB) not...

<img width="639" alt="screen shot 2016-11-14 at 19 11 16" src="https://cloud.githubusercontent.com/assets/2827249/20276979/0aa5df7a-aa9f-11e6-8cf7-b359ab28e813.png">


[Articles.zip](https://github.com/jekyll/jekyll/files/590126/Archive.zip)

**Comment by pathawks** [comment] 2016-11-17 03:45
`2016-11-13-modeliranje-css-kao-softverski-inzinjer\ copy.md` a byte order mark at the beginning of the file.

Duplicate of #2853

**Closed by pathawks** 2016-11-17 03:45 UTC

**Comment by ilicmarko** [comment] 2016-11-25 09:35
That is not the case, I added the copy because of the upload... 
If you change the name to: `2016-11-13-modeliranje-css-kao-softverski-inzinjer2.md` still doesn't work. As I said this file was named like the new one, as a matter of fact I  **copied** the file name from not working file to the new working.

**Comment by pathawks** [comment] 2016-11-25 17:22
But it has a BOM at the beginning of the file.
Nothing to do with filename.

**Comment by ilicmarko** [comment] 2016-11-29 21:07
Oh ok, I tough you said in the file name. Sorry closed!
