### ISSUE TITLE
Second configuration file is being ignored with --config _config.yml,_second_config.yml

### ISSUE THREAD

**Issue by danott** [jekyll/jekyll#4850] opened 2016-04-28 00:34 UTC
###### What version of Jekyll are you using (`jekyll -v`)?

`3.0.5`

###### What operating system are you using?

OSX

###### What did you do?

I have two configuration files. `_config.yml` and `_development.yml`. `_development.yml` includes the configuration `port: 1337`.

I'm running the command `jekyll serve --config _config.yml,_development.yml`

###### What did you expect to see?

I expected the command `jekyll serve --config _config.yml,_development.yml` to serve the site from `http://localhost:1337`

###### What did you see instead?

The `port` configuration is ignored, and the site is served from the default `http://localhost:4000`

###### Notes

I noticed this after running `bundle update github-pages`. Previously I was on Jekyll `3.0.3` which worked as expected. On `3.0.5`, the `port` configuration is still honored from yaml if it is in the first configuration file, but not in the second.

**Comment by parkr** [comment] 2016-04-29 19:21
Hey @danott, I just tried this but couldn't get replicate it. Is your site public? I can take a closer look there.

**Comment by opattison** [comment] 2016-05-04 17:07
@danott Is this your source? https://github.com/danott/today-i-learned

@parkr I tried the above source and the behavior is different between Jekyll 3.0.5 and 3.1.3.

Using `bundle exec` (Jekyll 3.0.5 with github-pages gem, with `port: 1337` in `_development.yml`):

`$ bundle exec jekyll s --config _config.yml,_development.yml`

```
Configuration file: _config.yml
Configuration file: _development.yml
            Source: /Users/op/repos/forks/today-i-learned
       Destination: /Users/op/repos/forks/today-i-learned/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.507 seconds.
 Auto-regeneration: enabled for '/Users/op/repos/forks/today-i-learned'
Configuration file: /Users/op/repos/forks/today-i-learned/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

Notice what's missing? `_development.yml` being read as a configuration file.

Same, **working as expected** (with Jekyll 3.1.3 instead of github-pages):

```
Configuration file: _config.yml
Configuration file: _development.yml
            Source: /Users/op/repos/forks/today-i-learned
       Destination: /Users/op/repos/forks/today-i-learned/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.328 seconds.
 Auto-regeneration: enabled for '/Users/op/repos/forks/today-i-learned'
Configuration file: _config.yml
Configuration file: _development.yml
    Server address: http://127.0.0.1:1337/
  Server running... press ctrl-c to stop.
```

---

`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`

**Comment by envygeeks** [comment] 2016-05-04 18:11
If it works without the github-pages gem in 3.0.5 this ticket belongs downstream.

**Comment by opattison** [comment] 2016-05-04 18:21
@envygeeks I just tested it *without* the github-pages gem with Jekyll 3.0.5 and the same issue is there. I think it’s Jekyll-specific and not directly related to the github-pages gem.

@danott If you want an immediate fix, change your `rake` task for serving to specify the option `--port 1337` instead of in the `_development.yml` file.

**Comment by envygeeks** [comment] 2016-05-04 18:24
This should probably get a triage then. /cc @parkr @jekyll/core

**Comment by danott** [comment] 2016-05-04 18:30
@opattison Thanks for going out of your way to confirm what I was experiencing!

https://github.com/danott/today-i-learned isn't the specific repo I discovered this behavior on, but it does have the same setup as a private repo where I discovered the unexpected behavior.

I'll use the `--port` option via command line while we get this sorted out properly. 😎

**Comment by parkr** [comment] 2016-05-12 15:57
@danott 3.0.x is being retired in a few weeks and we're pushing forward with 3.1.3/3.1.4. Can you try repro-ing on 3.1.3?

**Comment by parkr** [comment] 2016-05-18 22:46
I cannot reproduce on the `3.1-stable` branch.

**Comment by tfe** [comment] 2016-05-21 00:16
I am seeing this exact issue on 3.1.6, for what it's worth.

**Comment by egor-tensin** [comment] 2016-05-21 00:16
I'm observing the same behaviour after upgrading Jekyll from 3.0.3 to 3.1.5. I'm not sure as to what you guys mean by testing with or without `github-pages`, so can't contribute much to the conversation I'm afraid.
The funny thing is my custom configuration keys seem to apply properly from the second configuration file (even though it's not listed in a `Configuration file: ` line), while the much more important `baseurl` key (set to an empty string for local development) is not applied.
Meanwhile... A workaround, please?

**Comment by opattison** [comment] 2016-05-21 19:07
Also have the issue on 3.1.6 after upgrading from 3.1.3.

**Comment by parkr** [comment] 2016-05-23 20:35
Could someone please create a sample repo? I can't get this to fail.

**Comment by egor-tensin** [comment] 2016-05-23 22:05
https://github.com/egor-tensin/jekyll-issue4850. See README for details. I feel like I should also mention I'm doing this on Windows.

**Comment by egor-tensin** [comment] 2016-05-23 22:09
Also, I discovered that the actual values from the second configuration file are included to the output. For me, it's just that the site is not being served from a proper URL. And the `_config.yml` renaming thing. Anyway, it's all in README.md really.

**Comment by Crunch09** [comment] 2016-05-26 15:07
@parkr @egor-tensin  Hi, i could reproduce it on current master and i'll submit a PR later today 🎇

**Comment by ctubbsii** [comment] 2016-05-26 21:43
Another way this seems to manifest is when you simply do something simple like:
`bundle exec jekyll serve --config _config-asf.yml --safe`

The output is:
```
Configuration file: _config-asf.yml
            Source: /home/christopher/git/apache/accumulo
       Destination: /home/christopher/git/apache/accumulo/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 3.398 seconds.
 Auto-regeneration: enabled for '/home/christopher/git/apache/accumulo'
Configuration file: /home/christopher/git/apache/accumulo/_config.yml
    Server address: http://127.0.0.1:4000/accumulo/
  Server running... press ctrl-c to stop.
```

Notice the use of `_config.yml`, which was never specified.
(I'm using version 3.0.5, dependency of github-pages 78, but behaves the same when not using github-pages; version 3.0.3 worked fine)

The result (for me) is that relative paths are all broken (because the only difference I have is `baseurl`).

**Comment by tim-bradley** [comment] 2016-05-29 15:51
FWIW a suspiciously _similar_ problem has arisen for me today. 

Although it does seem different (my problem doesn't persist following a regen), I am reporting it here  because it is similar and the cause may be related and my investigations may or may not help resolve your issue.

**MY _SIMILAR_ ISSUE:**

When I serve with my usual command, 'my _config_dev.yml' is shown in both build and serve steps but its contents seem to be ignored - like what is described above. 

My usual command is: `jekyll serve --draft --host=0.0.0.0 --config _config.yml,_config_dev.yml`

However, if I edit, change and save a file, then on regeneration it works again!

BUT, if I start the serve skipping the initial build with `--skip-initial-build` then:
1. it initially loads correctly as expected (ie - without livereload, GA, etc);
2. but then the next build it doesn't;
3. then on all subsequent builds it seems to load correctly again.

I only noticed this issue today. 

The only recent environmental change I recall making prior to _noticing_ this problem was that I upgraded node.js from v4.5 to 6.2 yesterday. 

I haven't tried rolling back node.js because:
1. rolling back node is a pain on Windows; and 
2. its easy for me to work around  the issue by simply causing a regen by editing and saving a file.

So _for me_ the issue seems to only be with the FIRST build following the server being started. Although it seems unlikely to me, the cause may be related to changes in node.js core? It may not either.

**A SUGGESTION?**

I realise that my problem is sufficiently different that it is probably NOT related. Much more likely I have stuffed my setup somewhere. I am also on Windows and, well, we know how that plays with others.

But if someone has node versioning setup, they could test rolling it back to v4.5 (the version I was using before updating and noticing the the problem) to see if the problem persists? 

My apologies if this is a red herring, but I thought it worth mentioning because of similarities and lest it helps identify the issue the OP and others are experiencing.

**ABOUT MY DEV SETUP:**
I am developing locally on Windows 10 with Jekyll 2.5.3, and use Chrome.
I upload files direct to my web host, I don't push them to github.
I am not using a github-pages gem nor bundler.
I am not using any plugins.
I don't have a repository to point you to.

**Comment by envygeeks** [comment] 2016-05-29 16:01
What has node to do with a Jekyll bug?

**Comment by envygeeks** [comment] 2016-05-29 16:04
Let me elaborate, if Node breaks your Jekyll builds, we won't fix that unless it's a direct problem with Jekyll and/or Ruby (if it's a Ruby problem we can work around.) Otherwise your node.js setup is really on you to manage, and I hate to say that but you are doing something we don't support and shouldn't support because we didn't build the product.

**Comment by tim-bradley** [comment] 2016-05-29 17:17
@envygeeks, my apologies upfront. 
Yes. I understand this is a bug logged for jekyll and is not the place for node.js feedback. 
No. No need to elaborate. I am not logging a node.js error nor need help with that. Node is not broken and I use it with other applications (which is actually why I updated it).
I am sorry I did not make myself clear. 
I commented in case my feedback could _help_ identifying and dealing with _this jekyll bug_ as:
1. my jekyll problem is very similar that I thought they may share a root cause;
2. using the '--skip-first-build' command helped show me that my problem at least related to the first build following the serve process; and
3. the only change I made before I noticed my problem was a node update - jekyll runs on ruby and ruby runs on node - which could be ruled out as a cause by performing a rollback.
My feedback probably doesn't help!
Please do feel free to ignore it - I openly admit I no expert at anything relevant to this.
[_creeps away in shame_]

**Closed** 2016-06-02 23:59 UTC
Labels: bug
