### ISSUE TITLE
site.posts.size = 0, although there are posts in the folder

### ISSUE THREAD

**Issue by obendevski** [jekyll/jekyll#5849] opened 2017-02-01 15:09 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.

---
- [x] I am on (or have tested on) ***macOS*** 10+

- [x] It was another bug.

Previously i created a custom collection blog_posts and I came to realize later that pagination doesnt work with custom collections. When I tried to switch back to the "factory" settings and created a _posts folder, site.posts.size returns 0.

**Comment by pathawks** [comment] 2017-02-01 15:34
Do any of the posts appear in the generated site?

Is your source public?

**Comment by obendevski** [comment] 2017-02-01 15:37
the blog_posts do appear, the posts not. no, i'm afraid it's not public.

I followed the naming convention 2015-01-01-hello.md, still nothing.

When I do site.posts | inspect, it appears [].

**Comment by pathawks** [comment] 2017-02-01 16:25
Can you provide a way for me to recreate this issue? Maybe provide a minimal site that exhibits this behavior?

**Comment by pnn** [comment] 2017-02-02 13:21
can't reproduce either: 

https://pnn.github.io/jekyll-test/

https://github.com/pnn/jekyll-test/blob/master/_layouts/test.html

**Comment by obendevski** [comment] 2017-02-02 13:34
The thing is the project was already in late stages.I created a new project yesterday and its working good. But the "old" one is still not working.

**Comment by pathawks** [comment] 2017-02-02 13:59
> When I tried to switch back to the "factory" settings and created a _posts folder, site.posts.size returns 0.

> the blog_posts do appear, the posts not.

Wait, did you actually move all of your posts into the `_posts` directory? What is in the `_posts/` directory?

**Comment by obendevski** [comment] 2017-02-02 14:01
i put some random 2015-01-01-hello-world.md files with frontmatter 

---
title: Hello world
---
random text.

Still nothing.

**Comment by pathawks** [comment] 2017-02-02 14:39
What does your `_config.yml` look like?

**Comment by obendevski** [comment] 2017-02-02 14:54
```
collections:
  blog_posts:
    output: true
    permalink: /blog/:path/
  jobs:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: jobs
    values:
      layout: job
  - scope:
      path: ""
      type: blog_posts
    values:
      layout: blog
```

**Comment by parkr** [comment] 2017-02-03 16:07
If they have YAML front matter and no BOM, they should be read. Can you confirm that they have YAML front matter?

**Comment by obendevski** [comment] 2017-02-07 12:20
Yes, the filenames are as you said. They have frontmatter, still nothing. Is it maybe because my custom collection is named _blog_posts (it contains the name posts) ?

**Comment by obendevski** [comment] 2017-02-10 10:16
Even more, if i start a new branch from my master branch, and try to create a folder _posts, again, same behavior..So i guess the problem is in the jobs collection somehow?

**Comment by ashmaroli** [comment] 2017-02-10 10:44
Since you yourself couldn't reproduce this issue with a new project, and the old project being publicly inaccessible, I guess there's nothing much we can do to help.

**Comment by parkr** [comment] 2017-02-11 02:51
Going to close this as not-reproduced. More help can be found at https://talk.jekyllrb.com!

**Closed by parkr** 2017-02-11 02:51 UTC
Labels: not-reproduced
