### ISSUE TITLE
Allow valid YAML Documents as front-matter, Don't Start A New YAML Document

### ISSUE THREAD

**Issue by joobus** [jekyll/jekyll#3674] opened 2015-04-23 23:13 UTC
In YAML, three dashes, `---`, indicate the start of a document.  [Reference](http://www.yaml.org/spec/1.2/spec.html#id2760395)

Three periods, `...`, indicate the end of a document.  With the Jekyll version of front-matter, which has apparently become a de facto standard, the formatting indicates the start of a second YAML document where there is none.

I propose also supporting `...` as the ending to the YAML front-matter, because at this point too many people would have to change stuff otherwise.

**Comment by parkr** [comment] 2015-04-23 23:56
Duplicate of #3134

**Closed by parkr** 2015-04-23 23:56 UTC

**Comment by Jmuccigr** [comment] 2015-10-13 16:30
(Happy to start a new issue, if that's preferable.)

It's not clear to me where it is that the logic @ghost presents is faulty and so why Jekyll shouldn't use dots instead of hyphens to close front matter when the rest of the document is not YAML.

I note that pandoc and gitit both apply this logic to their use of YAML front matter and so close it with dots...which Jekyll therefore doesn't recognize.

I did have a look at #3134 and the goal there seems to be to keep Jekyll simple. #3138 talks about pandoc and the breaking of the YAML spec. Pandoc does indeed accept the hyphens, but it generates the dots, so pandoc-created front matter doesn't parse correctly in Jekyll.

**Comment by adunning** [comment] 2015-10-15 11:37
I feel as if I am missing something, but doesn't Jekyll already support the dots as an option? (It's working for me in 2.5.3, and appears to be in the [current](https://github.com/jekyll/jekyll/blob/7c4f319442b6b7a457d35cef2fc1b7a480b30850/lib/jekyll/document.rb#L9) [source](https://github.com/jekyll/jekyll/blob/2807b8a012ead8b8fe7ed30f1a8ad1f6f9de7ba4/lib/jekyll/convertible.rb#L48).)

**Comment by Jmuccigr** [comment] 2015-10-15 18:21
I see it there and apologize if I was wrong about this. It certainly looks like it's in there, despite this and the other threads I pointed to.

**Comment by pathawks** [comment] 2015-10-17 15:06
> It certainly looks like it's in there, despite this and the other threads I pointed to.

All closed ;)
