### ISSUE TITLE
Null characters being written to CSS files.

### ISSUE THREAD

**Issue by Ashwinning** [jekyll/jekyll#5035] opened 2016-06-26 12:40 UTC
My css code keeps being overwritten with null characters on running `jekyll build`.

I am not using sass/scss etc. Just pure css.

Encountering the same issue when I put my css files in the `assets` folder.

![](https://i.gyazo.com/5896214898e609a27e73216a562c0130.gif)

What I am doing :

- I create a css file, add some code to it.
 
 ![](https://i.gyazo.com/23178dba7d5849e5d00578f23ffa1bef.png)

- Build
 ```bash
  $ jekyll build
  ```

- And this is what Jekyll outputs to `_site/css`

 ![](https://i.gyazo.com/21e4fff91a72b399ede39175debb6ab5.png)
 
 Running on the [official Jekyll docker image](https://hub.docker.com/r/jekyll/jekyll/) on Windows 10.

---
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## How to reproduce
- Run a container with Jekyll from the docker image
```bash
 $ docker run jekyll/jekyll
```

- Inside the container, at `srv/jekyll` create a new jekyll project
```bash
 $ jekyll new . --force
```

- In `srv/jekyll/index.html` add
```html
<div class="NewDiv">
Some other text.
</div>
```
between the lines
```html
<h1 class="page-heading">Posts</h1>
```
and
```html
<ul class="post-list">
```

- Add a class called `underline` to the `ul`
```html
 <ul class="post-list underline">
 ```

- Now create a css file `rules.css` at `css/rules.css` which contains the following

```css

.underline {
    text-decoration: underline;
}

.NewDiv {
    text-align: center;
}
```

- Now we build the project
```bash
$ jekyll build
```

- On building the project, `_site/css/rules.css` looks like the following 

```css
.underline {
    text-decoration: underline;
}

```

Where the css code for `NewDiv` at has been replaced with [null characters](https://en.wikipedia.org/wiki/Null_character).

**Comment by parkr** [comment] 2016-06-27 16:49
@envygeeks have you ever seen this before between Windows & Linux (docker)? I can only imagine that the linux newline LF is being represented as `NUL` by the Docker sync to Windows.

**Comment by envygeeks** [comment] 2016-06-27 20:00
@parkr @Ashwinning I've not seen Docker do anything like that but I do have a few questions that might help me track down where the problem is coming from:

1. Are you using Native Docker?
1. OR Are you using Docker through Ubuntu GNU term on Linux?
1. Are you using Docker Toolbox with Docker Machine?
 

I noticed a lack of there being anything like docker-machine in there so I assume maybe not but that assumption might be wrong some people create wrappers (I know we do for our Window's users.)  The null-characters makes me think that Jekyll isn't even getting a proper copy of the file at all to begin with, which would make that Docker problem (or more or less probably a bug between the native FS and the FS within whatever lays between Docker and Docker Image (if using Ubuntu GNU term in Windows.)

**Comment by Ashwinning** [comment] 2016-06-28 05:23
@envygeeks sorry I forgot to mention, I'm using Docker Toolbox with Docker Machine - (Kitematic + Virtualbox).
New to docker here so still learning about it, I'll try to eliminate some more variables to see if I can still replicate the issue outside of Jekyll.
Thanks!

**Comment by Ashwinning** [comment] 2016-06-28 05:25
@parkr I still got the issue on forcing LF line endings though my IDE and the setting in `.gitattributes`.

**Comment by parkr** [comment] 2016-06-29 05:36
@Ashwinning Are you able to test on another supported platform? I am not sure how to isolate the issue to Docker, Virtualbox, or Jekyll.

**Comment by envygeeks** [comment] 2016-06-29 05:39
It can't be Jekyll.  If Jekyll does not behave like that outside of Docker or Virtualbox it's one of those.  To isolate it between those you'll need to install Docker Native and see if it still happens.  If it does then it's Docker and the ticket will need to go there.  If it doesn't then it's probably one of the many many many (literally there are hundreds) of issues that VirtualBox has that has forced Docker to go Native on OS X and Windows.

**Comment by parkr** [comment] 2016-06-29 05:45
Ok cool, that's what I thought. I'm going to close this but feel free to keep working on the issue if you wish :)

**Closed by parkr** 2016-06-29 05:45 UTC
Labels: undetermined
