### ISSUE TITLE
jekyll 3.0.0 build now exits with rc=1 ... always

### ISSUE THREAD

**Issue by fcassirer** [jekyll/jekyll#4147] opened 2015-11-16 20:22 UTC
Just upgraded to gem 3.0.0 and now jekyll build exits with rc=1, which fails my wrapper script ... 

It appears to work just fine otherwise.  Tried with and without --incremental

Thanks!

**Comment by fcassirer** [comment] 2015-11-17 14:33
My environment is a bit complex, but I've been able to narrow it down to my use of a trap('EXIT') call in one of my plugins.  Basically, I have a "bootstrap" generator plugin that gathers up site specific info after all my other generators have run (it is the only one at low priority).  I build a 'sitemap' which is a yaml payload of data about this specific site and load the sitemaps of a number of related sites (making the data available to this one for aggregation during this sites generation).  I then 'schedule' the writing of this sites site.yml file to occur at EXIT.  The reason is that even though this plugin runs last (or close to last), there are still other operations, tags, etc that can effect the sites final state.  I need to write out this final state when jekyll has finished.  There is apparently some new behavior at end of process for 3.0.0 vs 2.5.3 that causes my final writing of the site to fail.  The exact failure occurs when I take my datastructure and try to convert it to YAML, i.e.,

siteinfo.to_yaml
exception:  can't dump anonymous class: #<Class:0x000000036a23b0>

I am sure there is a better way to do this, i.e., if there was an exit hook in jekyll, or maybe I need to write some kind of command wrapper to wrap build.

Thanks in advance for any insight.
Fred

**Comment by envygeeks** [comment] 2015-11-17 15:09
I still need more information.  I don't need the error from your software, I need the error from ***our*** software.  When you build did it have an error? If it did then the status is legtimate and this is a WONTFIX, if it didn't have an error building the site and it exited 1 then we have a bug (and this will probably have to be filed up stream -- @parkr can tell you where -- I don't remember.)

If you are having problems with your plugin outside of those two contexts then you should probably ask your question on https://talk.jekyllrb.com because this medium is not for helping with software we 1.) Do not provide and 2.) is not a bug in our software. 

If you still think it's a bug out of those contexts then provide us the *complete terminal output* so we can go from there because I think everybody is getting lost in translation here.

On a side note: If you wish to have an at exit hook, please add your hook to this list at https://github.com/jekyll/jekyll/issues/3829 and we'll go from there if we can facilitate it.

**Comment by fcassirer** [comment] 2015-11-17 15:39
So I think I see the problem.  There appears to be a new collection file entry tag, 'excerpt'

 "excerpt"=><Excerpt: /design/toc#excerpt>,

When I try to to_yaml this, it fails:
...['excerpt'].to_yaml
TypeError: can't dump anonymous class: #<Class:0x00000003cbb3a0>
from .../jekyll/local/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:329:in `visit_Class'

this error was masked in the trap('EXIT') processing and caused what is likely a legitimate 'exit 1'.

I have just rewritten the trap handler to instead use a :site, :post_write hook and while I get the same error, I suspect this is a more supportable design choice.

I just need to dig in an better understand why 'excerpt' is now showing up and/or has changed to a non yaml dumpable object.

This appeared to be a change in behavior between jekyll 2.5.3 and 3.0.0 which is why I originally wrote the post.  I guess it boils down to the question of what are allowed operations by a plugin to the site.collections structure and below if indeed there has been a change here.

Thanks for the help and apologies if this was not an appropriate post for the site.
-Fred

**Comment by parkr** [comment] 2015-11-18 16:15
`excerpt` is an instance of `Jekyll::Excerpt`: https://github.com/jekyll/jekyll/blob/cae8bd31c2a9dc976e2c0313739d00f8cca7554a/lib/jekyll/document.rb#L322

We could add an `#to_yaml` method if you want.

**Closed** 2015-12-16 01:43 UTC
Labels: Pending Feedback
