### ISSUE TITLE
The YAML tag is not an array if I use it on a page

### ISSUE THREAD

**Issue by jwillmer** [jekyll/jekyll#4987] opened 2016-06-05 21:32 UTC
I have created a question about [why a tag works different in a page](https://talk.jekyllrb.com/t/why-is-tag-not-an-array-on-a-page/2468) in the Jekyll forum but the more I research I come to the conclusion that this might be a bug. This is the content of my post:

If I add the markup `tags` in a page instead of a post I noticed that the `join` operator does not work because it is treated as a string.

```
---
layout: page
tags: a b c
---

{{page.tags | join: ', '}}
```

result: `a b c`

```
---
layout: post
tags: a b c
---

{{page.tags | join: ', '}}
```

result: `a, b, c`

The [jekyll docs](https://jekyllrb.com/docs/frontmatter/#predefined-global-variables) do not differentiate between global  post or page variables but they still work different:

> There are a number of predefined global variables that you can set in the front matter of a page or post.

---

I am using jekyll version 3.1.6

**Comment by pathawks** [comment] 2016-06-05 21:41
> Also like categories, tags can be specified as a YAML list or a comma-separated string.

The disparity between the code and the docs, it is that Jekyll is splitting tags for posts with a _space_, presumably in addition to a comma.

idk. weird.

The easy solution is just to use a YAML list for your tags instead of a string.

**Comment by parkr** [comment] 2016-06-05 23:00
Hey @jwillmer! Thanks for opening this issue.

This is not a bug, but rather intended behaviour. Pages have never integrated with tags and categories to the same degree that posts do. You'll notice that your posts with tag `foo` will be in the array `{{ site.tags.foo }}`. Pages are not included here, so the convenience of defining tags as a string and Jekyll rendering them as an array is not applied.

I will update the documentation to move them down to `Predefined variables for Posts`.

**Closed** 2016-06-05 23:02 UTC

**Comment by jwillmer** [comment] 2016-06-05 23:14
Some background why I encountered it:
I use tags in my head file to add them as keywords. Now I created a new variable called keywords that I use in pages but if someone adds tags to the page it will favor them and that makes problems because they are not comma separated and I have no idea how I can check if it is an array or a string.
