### ISSUE TITLE
Can't get jekyll install 

### ISSUE THREAD

**Issue by KammiO** [jekyll/jekyll#3991] opened 2015-09-23 21:24 UTC
This is the error message I get when I try to install Jekyll:

Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20150923-8016-1q5vz1q.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14/ruby/config.h', needed by `porter.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/fast-stemmer-1.0.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/fast-stemmer-1.0.2/gem_make.out

**Comment by parkr** [comment] 2015-09-23 21:27
Duplicate of #3984.

**Closed by parkr** 2015-09-23 21:27 UTC

**Comment by jaybe-jekyll** [comment] 2015-09-23 21:28
Not exactly a duplicate. Compiling and installing things under any environment, OS X included, requires development libraries and build tools.

Install, at least, the OS X command line utilities. This can usually be invoked by calling a command provided by the utilities, such as `git`.

Then please reference #3984 for additional information about installing on OS X.

**Comment by KammiO** [comment] 2015-09-23 21:37
I tried the homebrew install and the longer install command suggested at #3984 and it still doesn't work.   
This isn't a duplicate problem, as far as I can tell.


Current error message: ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
extconf failed, exit code 1

Gem files will remain installed in /Users/MediaComputer/.gem/ruby/2.0.0/gems/ffi-1.9.10 for inspection.
Results logged to /Users/MediaComputer/.gem/ruby/2.0.0/extensions/universal-darwin-14/2.0.0/ffi-1.9.10/gem_make.out
BunnellComputer:~ MediaComputer$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install ruby
gem install jekyll
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
BunnellComputer:~ MediaComputer$ brew install ruby
Error: Cannot write to /usr/local/Cellar
BunnellComputer:~ MediaComputer$ gem install jekyll
Fetching: fast-stemmer-1.0.2.gem (100%)
ERROR:  While executing gem ... (Errno::ENOTSUP)
    Operation not supported - /home/private
