### ISSUE TITLE
Not be able to install Jekyll on OSX El Capitan 10.11.6

### ISSUE THREAD

**Issue by etiennedesign** [jekyll/jekyll#5563] opened 2016-11-08 21:54 UTC
- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [X] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [X] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [X] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

1- Install jekyll latest version 3.3.0
2- `cd desktop`
3- `jekyll new mywebsite`
4- i got the message: 

> New jekyll site installed in /Users/etienne/Desktop/mywebsite. 
>   Dependency Error: Yikes! It looks like you don't have bundler or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- bundler' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 

When i do `bundler` i get the message

> Could not locate Gemfile or .bundle/ directory

When i do `gem install bundler` i get

> ERROR:  While executing gem ... (Errno::EACCES)
>     Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/.codeclimate.yml
> 

I tried several tips i found on help forums but no success for now.
I did all the troubleshooting tips here https://jekyllrb.com/docs/troubleshooting/#installation-problems, still no sucess.
I also tried to install jekyll again using this checklist
- [X] Install Xcode command line utilities xcode-select --install
- [X] Install Homebrew (instructions at http://brew.sh)
- [X] Modify $PATH to use Homebrew export PATH=/usr/local/bin:$PATH
- [X] Install the latest Ruby brew install ruby
- [X] Install the latest Jekyll gem install jekyll

Is anyone has ever met this issue?

**Comment by DirtyF** [comment] 2016-11-08 22:19
@etiennedesign FWIW I tend to prefer to [install jekyll with rbenv](https://gist.github.com/DirtyF/5d2bde5c682101b7b5d90708ad333bf3)

**Comment by etiennedesign** [comment] 2016-11-09 14:38
@DirtyF thanks for your reply.
I got the same permission issue.

```
Last login: Wed Nov  9 09:22:57 on console
etienne:~ etienne$ curl https://gist.githubusercontent.com/DirtyF/5d2bde5c682101b7b5d90708ad333bf3/raw/0d5af07d3e6faa18992cb472d7bb015f775f5e8f/setup-rbenv.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   331  100   331    0     0   1137      0 --:--:-- --:--:-- --:--:--  1141
+ brew install rbenv ruby-build
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
gmic                                     treefrog
==> Updated Formulae
armor           citus           kotlin          osmosis         webkitgtk
bitrise         filebeat        librdkafka      rust

==> Installing dependencies for rbenv: autoconf, pkg-config, ruby-build
==> Installing rbenv dependency: autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.el_capitan.bo
######################################################################## 100.0%
==> Pouring autoconf-2.69.el_capitan.bottle.4.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/autoconf
==> Summary
🍺  /usr/local/Cellar/autoconf/2.69: 70 files, 3.0M
==> Installing rbenv dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.1_2.el_capi
######################################################################## 100.0%
==> Pouring pkg-config-0.29.1_2.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.1_2: 10 files, 627.4K
==> Installing rbenv dependency: ruby-build
==> Using the sandbox
==> Downloading https://github.com/rbenv/ruby-build/archive/v20160913.tar.gz
==> Downloading from https://codeload.github.com/rbenv/ruby-build/tar.gz/v201609
######################################################################## 100.0%
==> ./install.sh
🍺  /usr/local/Cellar/ruby-build/20160913: 304 files, 165.1K, built in 2 seconds
==> Installing rbenv
==> Downloading https://homebrew.bintray.com/bottles/rbenv-1.0.0.el_capitan.bott
######################################################################## 100.0%
==> Pouring rbenv-1.0.0.el_capitan.bottle.tar.gz
==> Caveats
Rbenv stores data under ~/.rbenv by default. If you absolutely need to
store everything under Homebrew's prefix, include this in your profile:
  export RBENV_ROOT=/usr/local/var/rbenv

To enable shims and autocompletion, run this and follow the instructions:
  rbenv init
==> Summary
🍺  /usr/local/Cellar/rbenv/1.0.0: 36 files, 62K
+ rbenv install 2.3.1
Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...
Installed ruby-2.3.1 to /Users/etienne/.rbenv/versions/2.3.1

+ rbenv global 2.3.1
+ rbenv shell 2.3.1
rbenv: no such command `shell'
etienne:~ etienne$ gem install jekyll bundler
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.3.0/.rubocop.yml
etienne:~ etienne$ 
```

**Comment by pathawks** [comment] 2016-11-09 15:01
I am sorry you are having trouble installing Jekyll.

This issue tracker is only for bugs related to Jekyll, rather than a general forum to provide support. Instead, you might try looking for help at https://talk.jekyllrb.com/

Closing this issue, as it is not a bug in Jekyll.

**Closed by pathawks** 2016-11-09 15:01 UTC
