### ISSUE TITLE
Windows - working install script for Ruby 2.6 - feedback

### ISSUE THREAD

**Issue by MSP-Greg** [jekyll/jekyll#7483] opened 2019-01-19 17:49 UTC
I believe the following is a script that correctly installs Jekyll on Windows.  EventMachine will be built with OpenSSL support.

Requirements:
1. Assumes a Ruby install >= 2.4, and properly installed 'DevKit' (MSYS2/MinGW) build tools.
2. Path to Ruby or gem install folder should have no spaces (working on that, not a Jekyll issue).
3. `C:/Greg/Jekyll` is 'project' folder, change to suit...
4. For testing, change $env:GEM_HOME to a new path, which will leave the Ruby installation untouched.
5. Shown for a PowerShell windows, changes needed for a cmd window.

I have no idea where to post this, and I am not familiar with Jekyll.  A user posted an issue in a dependent gem repo, so I did some testing.

```ps1
gem install jekyll --platform=ruby
gem install minima tzinfo-data wdm --platform=ruby

jekyll new C:/Greg/jekyll

# cd to  project folder
cd C:/Greg/jekyll

bundle lock --add-platform=x64-mingw32  # change to x86-mingw32 if 32 bit
bundle install

bundle exec jekyll serve --livereload
```

**Comment by ashmaroli** [comment] 2019-01-19 17:54
@MSP-Greg Hi :wave:
Can you post a link to the "issue in a dependent gem repo" you're referring to above, so that there's an idea regarding what exactly the user was looking about for..?

**Comment by ashmaroli** [comment] 2019-01-19 18:35
I use Ruby on Windows via RubyInstaller 2 myself
```
ruby --version
ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
```
And all I need to do regarding Jekyll is:
```bash
$ gem install jekyll bundler
$ jekyll new project_name # runs `bundle install` automatically
$ cd project_name
$ bundle exec jekyll serve --livereload
```
You can direct your user to the following docs link for further information: https://jekyllrb.com/docs/installation/windows/

Closing as this is not a bug report.

**Closed by ashmaroli** 2019-01-19 18:35 UTC

**Comment by MSP-Greg** [comment] 2019-01-19 18:43
@ashmaroli 

Due to bugs/issues in Bundler/RubyGems and some of the dependent gems, I don't believe that will work for Ruby 2.6, possibly 2.5...

**Comment by ashmaroli** [comment] 2019-01-19 18:49
> I don't believe that will work for Ruby 2.6

I'm waiting for AppVeyor to ship support for Ruby 2.6 and we'll have CI test it through.

**Comment by MSP-Greg** [comment] 2019-01-19 18:54
Want to test ruby-head/trunk?

**Comment by MSP-Greg** [comment] 2019-01-20 18:13
@ashmaroli

The original issues was https://github.com/eventmachine/eventmachine/issues/869

Conversation moved to https://github.com/MSP-Greg/jekyll/issues/1.  You're welcome to join.

It involves several issues that are really not caused by Jekyll...
