### ISSUE TITLE
Jekyll build takes minutes to complete

### ISSUE THREAD

**Issue by motymichaely** [jekyll/jekyll#4297] opened 2015-12-28 16:15 UTC
For some reason, after migrating to Jekyll 3.0, site build takes way longer than it was before the migration (from ~10 seconds to ~300 seconds). 

I do have multiple custom made plugins (custom page generators, filters and more) but my baseline of 10 seconds should suffice to indicate a problem.

What type of info should I provide to diagnose this?

Ruby version: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
Gemfile.lock:
```
GIT
  remote: https://github.com/imathis/guard-jekyll-plus.git
  revision: 26e1426fb0972613d80dd5f0acf38ffcc1046a2c
  specs:
    guard-jekyll-plus (2.0.2)
      guard (~> 2.10, >= 2.10.3)
      guard-compat (~> 1.1)
      jekyll (>= 1.0.0)

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    autoprefixer-rails (6.2.1)
      execjs
      json
    bootstrap-sass (3.3.6)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    charlock_holmes (0.7.3)
    coderay (1.1.0)
    colorator (0.1)
    colored (1.2)
    concurrent-ruby (1.0.0)
    daemons (1.2.3)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    escape_utils (1.1.0)
    ethon (0.8.0)
      ffi (>= 1.3.0)
    eventmachine (1.0.8)
    execjs (2.6.0)
    fastimage (1.8.1)
      addressable (~> 2.3, >= 2.3.5)
    ffi (1.9.10)
    formatador (0.2.5)
    github-linguist (4.7.3)
      charlock_holmes (~> 0.7.3)
      escape_utils (~> 1.1.0)
      mime-types (>= 1.19)
      rugged (>= 0.23.0b)
    github-markdown (0.6.9)
    googl (0.7.1)
      httparty (~> 0.10)
      json (>= 1.4.6)
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-livereload (2.5.1)
      em-websocket (~> 0.5)
      guard (~> 2.8)
      guard-compat (~> 1.0)
      multi_json (~> 1.8)
    html-pipeline (1.11.0)
      activesupport (>= 2)
      nokogiri (~> 1.4)
    html-proofer (2.6.1)
      activesupport (~> 4.2)
      addressable (~> 2.3)
      colored (~> 1.2)
      mercenary (~> 0.3.2)
      nokogiri (~> 1.5)
      parallel (~> 1.3)
      typhoeus (~> 0.7)
      yell (~> 2.0)
    http_parser.rb (0.6.0)
    httparty (0.13.7)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.7.0)
    jekyll (3.0.1)
      colorator (~> 0.1)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-assets (2.1.2)
      fastimage (~> 1.8)
      jekyll (~> 3.0)
      sprockets (~> 3.3)
      sprockets-helpers (~> 1.2)
      tilt (~> 2.0)
    jekyll-html-pipeline (0.1.4)
      html-pipeline (~> 1.0)
      jekyll (>= 2.0)
    jekyll-paginate (1.1.0)
    jekyll-redirect-from (0.9.1)
      jekyll (>= 2.0)
    jekyll-sass-converter (1.3.0)
      sass (~> 3.2)
    jekyll-watch (1.3.0)
      listen (~> 3.0)
    json (1.8.3)
    kramdown (1.9.0)
    liquid (3.0.6)
    liquid-c (3.0.0)
      liquid (>= 3.0.0)
    listen (3.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    lumberjack (1.0.9)
    mercenary (0.3.5)
    method_source (0.8.2)
    mime-types (3.0)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2015.1120)
    mini_portile2 (2.0.0)
    minitest (5.8.3)
    multi_json (1.11.2)
    multi_xml (0.5.5)
    nenv (0.2.0)
    nokogiri (1.6.7.1)
      mini_portile2 (~> 2.0.0.rc2)
    notiffany (0.0.8)
      nenv (~> 0.1)
      shellany (~> 0.0)
    parallel (1.6.1)
    posix-spawn (0.3.11)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pygments.rb (0.6.3)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.2.0)
    rack (1.6.4)
    rake (10.4.2)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rouge (1.10.1)
    rugged (0.24.0b11)
    safe_yaml (1.0.4)
    sass (3.4.20)
    shellany (0.0.1)
    slop (3.6.0)
    sprockets (3.5.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-helpers (1.2.1)
      sprockets (>= 2.2)
    thin (1.6.4)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0, >= 1.0.4)
      rack (~> 1.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    typhoeus (0.8.0)
      ethon (>= 0.8.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    yajl-ruby (1.2.1)
    yell (2.0.5)
    yui-compressor (0.12.0)

PLATFORMS
  ruby

DEPENDENCIES
  bootstrap-sass
  github-linguist
  github-markdown
  googl
  guard-jekyll-plus!
  guard-livereload
  html-pipeline
  html-proofer
  jekyll
  jekyll-assets
  jekyll-html-pipeline
  jekyll-paginate
  jekyll-redirect-from
  jekyll-watch
  liquid-c
  pygments.rb
  rack
  rake
  sass
  thin
  tzinfo
  yui-compressor (~> 0.12.0)

BUNDLED WITH
   1.11.2
```

Config file used (reduced any sensitive info):
```
name: My Blog
company_name: My Blog
markdown: HTMLPipeline
html_pipeline:
  filters:
    - "markdownfilter"
    - "imagemaxwidthfilter"
    - "syntaxhighlightfilter"
    - "ImageAltFilter"
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
collections:
  docs:
    output: true
    permalink: /:collection/:path/
lsi: false
baseurl: http://localhost:4000
encoding: UTF-8
permalink: /blog/:year/:month/:title/
url: http://localhost:4000
domain: localhost:4000
paginate: 10
paginate_path: "/blog/page:num"
# Blog configuration
env: staging
language: en-US
timezone: GMT
future: false
gems:
  - jekyll-watch
  - jekyll-paginate
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-html-pipeline
exclude:
- CNAME
- .gitignore
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
- .ruby-version
- Guardfile
- .jekyll-assets-cache
- .sass-cache
- .editorconfig
- .idea
- .ruby-version
- .asset-cache
#
# Plugin: jekyll-assets
#
assets:
  cache_assets: false
  dirname: assets
  baseurl: http://localhost:4000/assets
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  features:
    automatic_img_size: false
    automatic_img_alt: false
  cachebust: none
  gzip: false
  debug: false
```

Any suggestion would be highly appreciated.

**Comment by pathawks** [comment] 2015-12-28 17:26
There is no way for you to share the dource of your site, so that this can be reproduced?

**Comment by motymichaely** [comment] 2015-12-28 17:36
@pathawks -  I wish I could. It's quite reproducible on my entire team machines. It would be great if you could guide me to get any helpful information.

I do suspect it has something todo with jekyll-assets but I can't really eliminate it as the source code includes multiple asset_path calls.

**Comment by parkr** [comment] 2015-12-29 01:08
Have you run with the new --profile flag?

**Comment by envygeeks** [comment] 2015-12-29 03:02
Make sure you also add `--verbose --trace` as well because we extensively log in Jekyll Assets.  If you see no output from Jekyll Assets it means it's probably not us because we don't log cached assets, however, if we compile an asset on the fly, we do let you know the asset, where it is caching to, how long it took to build it and other stuff.

That said, half your Jekyll Assets configuration is invalid anyways, it's like a mixture of legacy Jekyll Assets and Jekyll Assets stable, so in theory we are caching heavily on your behalf (even in development, which is ***exactly what we want since Sprockets will bust the asset itself if it changes***)

Lets update your Jekyll Assets to 2.0 and fix your options:
```yaml
assets:
  cache: false # You should leave this enabled probably.
  # dirname: assets - Not necessary and not even an option anymore.  It's prefix now and the default.
  # baseurl: http://localhost:4000/assets - Not necessary and will actually cause double assets.
  # sources: - Not necessary these are already the default sources.
    # - _assets/javascripts
    # - _assets/stylesheets
    # - _assets/images
  features:
    automatic_img_size: false
    automatic_img_alt:   false
  # cachebust: none # This is no longer an option, we bust whether you like it or not.
  # gzip: false # We no longer offer GZIP, this is invalid, your server does it better than us.
  # debug: false # This isn't an option, we decide our logging from Jekyll, we use it's logger.
```

And cleaned up:

```yaml
assets:
  features:
    automatic_img_size: false
    automatic_img_alt:   false
```

1. We no longer offer cache busting because we let sprockets deal with that and we (and by we I mean it was my sole decision) decided it was a robust enough solution.  It will bust when it wants to, which is normally based on whether the file's contents have changed and been modified.  We no longer do our own caching at all, it's all done through Sprockets entirely.  Since Sprockets will bust and generate an asset again if you enforce digests in development I took the stance that there is no need to offer another busting solution.

2. WE do not offer a baseurl option, we use Jekyll's own baseurl.  There is a prefix option, but that is only to be used if you want us to write your assets to something other than "/assets", so if you want it in "/my-stuff" then you set the prefix to that and we will write there instead of "/assets".  There is also a `cdn` option and two options that come with that `skip_baseurl_with_cdn` and `skip_prefix_with_cdn` the former again, only uses Jekyll's own baseurl and is ignored if Jekyll has no baseurl, the latter only affects our helpers, we will still write to your prefix folder.

3. You should probably leave caching enabled, Sprockets deals with caching, and if you use a lot of images through our proxies it will help you a lot, in that if you disable caching and you have a ton of images using the same filters it will overwite itself tons of times, if you enable caching, it only writes once (and only if it's not cached.) We determine this cache solely on your asset + asset tag options + Sprockets digest.

4. GZIP is removed entirely, like Sprockets, we think your server does it better.
5. debug is not an option, we use Jekyll's own logger through a wrapper that adds the necessary logging utilities that enable Sprockets to use Jekyll's logger.  So if you tell Jekyll to go all out debug mode, we will comply and start logging, otherwise it's up to Jekyll whether or not it spits out the data we tell it to.

**Comment by envygeeks** [comment] 2015-12-29 03:14
Let me note, if it turns out to be Jekyll Assets going slow, please close this ticket and file your issue on https://github.com/jekyll/jekyll-assets and provide as much information as you can such as the logs, list of optional features we let you use and we'll go from there.

**Comment by motymichaely** [comment] 2015-12-29 06:05
@parkr - Yes, i've used `--profile` flag to get some insights on the build time.

Here's a snippet of the top 15 records of the build command. Please note that my dev configuration (_config_dev.yml) disables several plugins that will make the build time 10 times longer, if enabled:

```
$ time JEKYLL_ENV=development jekyll build --profile --config _config_dev.yml
Configuration file: _config_dev.yml
            Source: /Users/moty/dev/test
       Destination: /Users/moty/dev/test/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 

Filename                           | Count |     Bytes |   Time
-----------------------------------+-------+-----------+-------
_layouts/base.html                 |   404 | 10760.82K | 27.129
_includes/favicon.html             |   408 |   455.81K |  8.981
_layouts/post.html                 |   139 |  1367.04K |  1.730
_includes/post_hero.html           |   139 |   241.97K |  1.400
_includes/post_snippet.html        |   139 |   300.16K |  1.287
_includes/twitter_card.html        |   408 |   232.52K |  1.086
_includes/google_kg.html           |   405 |   223.46K |  0.956
_includes/fb_og.html               |   408 |   196.36K |  0.945
_layouts/default.html              |   400 |  5567.42K |  0.771
_includes/footer.html              |   403 |  2333.39K |  0.508
_includes/post_author.html         |   278 |    50.43K |  0.351
_includes/social_links.html        |   403 |   549.40K |  0.256
(jekyll:assets)                    |  6804 |   152.04K |  0.232
_layouts/doc.html                  |   226 |   402.77K |  0.158
_includes/header.html              |   403 |   883.14K |  0.142

done in 37.19 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
JEKYLL_ENV=development jekyll build --profile --config _config_dev.yml  33.06s user 3.88s system 95% cpu 38.737 total
```

When removing the following lines from the base.html file it reduces ~25s from this build time:

```jekyll
{% stylesheet style %}
{% javascript application %}
```

Since these lines are the main entry point for the site assets, they can't be removed :).

**Comment by motymichaely** [comment] 2015-12-29 06:09
@envygeeks - Thanks for the heads up with regards the jekyll-assets configuration!

I didn't notice any jekyll-assets output when using `--verbose`. Am I missing something?

**Comment by motymichaely** [comment] 2015-12-29 06:26
Let me note one more thing - Seems like with `--watch` the build takes way longer on its second round. My suspects are the cache folders being regenerated:

```
06:21:47 - INFO - Jekyll Files changed:  building...
| 
|  ~ _layouts/base.html
| 
06:23:34 - INFO - Jekyll build completed in 106.89s /Users/moty/dev/myblog → _site
06:23:34 - INFO - Reloading browser: _layouts/base.html
06:23:34 - INFO - Jekyll updating files
| 
|  → _site/.asset-cache/sprockets/v3.0/-12TAGKeSRQupSMOzD-CGG4Gms57OAo1LAu_sAAOgEs.cache
|  → _site/.asset-cache/sprockets/v3.0/-i9DJzqoTY7A32mWtY4jwTSbWrTUpS-oTanWnYdPy1k.cache
|  → _site/.asset-cache/sprockets/v3.0/-lRUGJyQT1G2MeOwbXpkXI9rKM1zhkv3aKr_j-kNeYs.cache
... and so long
```

But I do have all the folders excluded. Any chance jekyll ignores my exclude setting?
```
exclude:
- CNAME
- .gitignore
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
- .ruby-version
- Guardfile
- .jekyll-assets-cache
- .sass-cache
- .editorconfig
- .idea
- .ruby-version
- .asset-cache
```

Any idea?

**Comment by envygeeks** [comment] 2015-12-29 06:34
Please file your ticket at https://github.com/jekyll/jekyll-assets/issues/new this issue is officially out of scope for Jekyll Core.

**Closed by envygeeks** 2015-12-29 06:34 UTC

**Comment by motymichaely** [comment] 2015-12-29 06:38
@envygeeks - It would be great if you could share your insights on why this is out of Jekyll Core's scope..?

**Comment by envygeeks** [comment] 2015-12-29 06:39
If Jekyll Assets causes the problem and the slow down, it's not Jekyll cores problem.

**Comment by motymichaely** [comment] 2015-12-29 06:43
@envygeeks - I understand. Where do you find an indication that Jekyll Assets causes the problem? I didn't notice anything special on verbose level logs, the `--profile` listed jekyll:assets as non time consuming. And the main culprit I could notice is Jekyll not excluding the assets cache folder.
