### ISSUE TITLE
URL and baseurl -help

### ISSUE THREAD

**Issue by CarlasHub** [jekyll/jekyll#6943] opened 2018-04-21 14:51 UTC
The paths  on the  yml file seem to be in conformity with  the repository name and url. I cannot  find the reason why is not loading the pages  or recognizing the  baseurl and subpaths. I would appreciate if some information  could be provided to solve this issue.  in particular :https://carlashub.github.io/carla/casestudies/case-one.html
https://carlashub.github.io/programming/2018/04/13/which-framework/

 Thanks

**Comment by pathawks** [comment] 2018-04-21 16:27
Closing, as this is not a bug in Jekyll, but thank you @DirtyF for getting to the bottom of this 👍🏼

**Closed** 2018-04-21 16:26 UTC
Labels: support

**Comment by CarlasHub** [comment] 2018-04-22 10:12
@DirtyF This was so helpful, tanks so much for taking your time to help me solve this issue in the next project i need to have a proper read on the documents so this doesn't happen again. I'll use the forum for non bug related questions.  Thanks
