### ISSUE TITLE
Jekyll does not find it's working directory in docker container(s)

### ISSUE THREAD

**Issue by Gitward** [jekyll/jekyll#5902] opened 2017-02-24 14:26 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [x] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

* I set up a GitLab runner as described on https://github.com/sboekhoff/jekyll-asciidoc-docker
* I used to run jekyll in the script-phase of the CI-job by using `jekyll build -d public -s website`
* After the Jekyll Docker image was updated to `3.4.0`, Jekyll did not find the config file (and the source files)
* Running `jekyll build -d ${PWD}/public -s ${PWD}/website --config ${PWD}/website/_config.yml` solved the problem.
* It seems that Jekyll does have the correct working directory.
* It seems that other users have the same problem: http://stackoverflow.com/questions/42142369/after-updating-gitlab-version-jekyll-build-reports-configuration-file-none

This might be also a problem of the Docker Image @envygeeks

* The actual working directory seems to be `/srv/jekyll`
* In the `Dockerfile` `WORKDIR` is set to `/srv/jekyll`, but that was the case already before the update to `3.4.0` https://github.com/jekyll/docker/blame/master/repos/jekyll/Dockerfile#L40

/cc @jekyll/build @jekyll/ecosystem

**Comment by parkr** [comment] 2017-02-24 15:32
If you run just our docker container, does it improve? It could be that the CI runner is changing the working directory before being reset properly.

**Comment by parkr** [comment] 2017-02-27 19:15
Closing due to lack of information. We can open back up if the information I requested above is provided. 😄

**Closed** 2017-02-27 19:15 UTC

**Comment by envygeeks** [comment] 2017-02-27 20:37
Our `WORKDIR` wouldn't affect any `cd` that Jekyll does since the WORKDIR is just the initial directory so AFAIW this is not a bug in the Jekyll Docker Image, if this did turn out to be the case it would either be a bug in Docker or a change in behavior (perhaps? Doubtful to me though.)

**Comment by fefrei** [comment] 2017-05-28 14:10
There is definitely something weird about this. Running `bash -c "ls -al"` before `jekyll build` does show the `_config.yml` file, still the following `jekyll build` fails to find it.
Running `jekyll build -d ${PWD}/_site -s ${PWD} --config ${PWD}/_config.yml` does work fine, however.
