### ISSUE TITLE
LoadError: cannot load such file -- kramdown

### ISSUE THREAD

**Issue by mskian** [jekyll/jekyll#8059] opened 2020-03-17 06:16 UTC
I follow the **Official steps** to install and Configure the Gem, Bundle, and Jekyll
but I am getting this below error while build and serve

```bash
LoadError: cannot load such file -- kramdown
  /home/groot/.gem/ruby/2.5.0/gems/jekyll-4.0.0/lib/jekyll.rb:36:in `require'
  /home/groot/.gem/ruby/2.5.0/gems/jekyll-4.0.0/lib/jekyll.rb:36:in `<top (required)>'
  /home/groot/.gem/ruby/2.5.0/gems/jekyll-4.0.0/exe/jekyll:8:in `require'
  **/home/groot/.gem/ruby/2.5.0/gems/jekyll-4.0.0/exe/jekyll:8:in** `<top (required)>'
  /home/groot/gems/bin/jekyll:23:in `load'
  /home/groot/gems/bin/jekyll:23:in `<top (required)>'
```

OS: Ubuntu 18.04 LTS

**Comment by ashmaroli** [comment] 2020-03-17 06:21
Are you running `bundle exec jekyll build` or just `jekyll build`?

**Comment by mskian** [comment] 2020-03-17 06:24
also get this error while check the version

```bash
$ jekyll --version

Traceback (most recent call last):
	7: from /home/groot/gems/bin/jekyll:23:in `<main>'
	6: from /home/groot/gems/bin/jekyll:23:in `load'
	5: from /home/groot/.gem/ruby/2.5.0/gems/jekyll-4.0.0/exe/jekyll:8:in `<top (required)>'
	4: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /home/groot/.gem/ruby/2.5.0/gems/jekyll-4.0.0/lib/jekyll.rb:36:in `<top (required)>'
	1: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- kramdown (LoadError)

```

**Comment by mskian** [comment] 2020-03-17 06:25
> Are you running `bundle exec jekyll build` or just `jekyll build`?

```bash
bundle exec jekyll build
```

**Comment by mskian** [comment] 2020-03-17 06:26
```bash
$ gem list jekyll

*** LOCAL GEMS ***

jekyll (4.0.0)
jekyll-admin (0.10.0, 0.8.1)
jekyll-paginate (1.1.0)
jekyll-sass-converter (2.1.0)
jekyll-seo-tag (2.6.1)
jekyll-sitemap (1.4.0, 1.2.0)
jekyll-watch (2.2.1)
```

**Comment by ashmaroli** [comment] 2020-03-17 06:27
Try running `bundle install`  and then `bundle list`

**Comment by mskian** [comment] 2020-03-17 07:14
> Try running `bundle install` and then `bundle list`

Done  but same error

```bash
$ bundler list

Gems included by the bundle:
  * addressable (2.7.0)
  * colorator (1.1.0)
  * concurrent-ruby (1.1.6)
  * em-websocket (0.5.1)
  * eventmachine (1.2.7)
  * ffi (1.12.2)
  * forwardable-extended (2.6.0)
  * http_parser.rb (0.6.0)
  * i18n (1.8.2)
  * jekyll (4.0.0)
  * jekyll-paginate (1.1.0)
  * jekyll-sass-converter (2.1.0)
  * jekyll-seo-tag (2.6.1)
  * jekyll-watch (2.2.1)
  * kramdown (2.1.0)
  * kramdown-parser-gfm (1.1.0)
  * liquid (4.0.3)
  * listen (3.2.1)
  * mercenary (0.3.6)
  * pathutil (0.16.2)
  * public_suffix (4.0.3)
  * rb-fsevent (0.10.3)
  * rb-inotify (0.10.1)
  * rouge (3.17.0)
  * safe_yaml (1.0.5)
  * sassc (2.2.1)
  * terminal-table (1.8.0)
  * unicode-display_width (1.7.0)
Use `bundle info` to print more detailed information about a gem
```

**Comment by ashmaroli** [comment] 2020-03-17 07:27
The issue is probably due to some discrepancy that occurred when you installed Ruby.
- Running `bundle info kramdown` will give you the path to where `kramdown` has been installed.
- Run `gem env` to get an insight on all paths Ruby is concerned about.
- If **the directory** where `kramdown` got installed from above isn't listed in the `gem env` output, you'll have to manually add that path.
(OS specific instructions can be found on the internet e.g. *Add directory to PATH on macOS*..).

**Comment by DirtyF** [comment] 2020-05-09 12:13
Closing as it's not a Jekyll core bug.

**Closed by DirtyF** 2020-05-09 12:13 UTC
Labels: education
