### ISSUE TITLE
{% highlight language %} with empty line throws an exception

### ISSUE THREAD

**Issue by pixelastic** [jekyll/jekyll#6762] opened 2018-02-09 14:58 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

- Create a new Jekyll project with `jekyll new my-project` (`jekyll -v` gives `jekyll 3.7.2`)
- Create a new post with the following content:
```
---
title: "Liquid error"
---
{% highlight ruby %}
# Any code to highlight that contains an empty line...

# ...will throw a Liquid exception
{% endhighlight %}

```
- Run `jekyll build`
- Got following error:
```
  Liquid Exception: Liquid syntax error (line 4): 'highlight' tag was never closed in /home/tim/local/www/forks/liquid-error/_posts/2018-02-09-liquid-error.md/#excerpt
  Liquid Exception: Liquid syntax error (line 4): 'highlight' tag was never closed in feed.xml
```

No matter what is added to the block, if there is an empty line, it will throw an error.

## The Output I Wanted

No actual errors and markup rendered. New lines in code snippets is quite common.

**Comment by ashmaroli** [comment] 2018-02-09 15:02
Hi @pixelastic :wave:
This is a known issue (ref #5596)
I've submitted a PR to resolve this (#6724)

Feel free to point to that PR's branch and see if it resolves your issue.

**Comment by pathawks** [comment] 2018-02-09 15:12
Duplicate of #5596

A quick workaround is to define an excerpt for that post.

**Closed by pathawks** 2018-02-09 15:12 UTC
