### ISSUE TITLE
Server watching not reloads when _config.yml was changes

### ISSUE THREAD

**Issue by iBobik** [jekyll/jekyll#3981] opened 2015-09-19 02:09 UTC
I am not sure if it is bug or just a "feature", but it is confusing.

While working I have `jekyll s` started, so it nicely regenerate site when I change some file in it. But when I change something in `_config.yml` file, it don't reload this file.

**Comment by parkr** [comment] 2015-09-19 02:55
This has been discussed countless times -- please search the repo's issues and pull requests before opening something new.

In any event, duplicate of https://github.com/jekyll/jekyll-watch/issues/8, where we're tracking this.

**Closed by parkr** 2015-09-19 02:55 UTC

**Comment by iBobik** [comment] 2015-09-19 04:53
I searched, I promise :-)

Anyway, sorry and thanks for link.



Jan Pobořil

2015-09-18 21:56 GMT-05:00 Parker Moore <notifications@github.com>:
