### ISSUE TITLE
ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by cable2T17** [jekyll/jekyll#3593] opened 2015-03-19 03:06 UTC
> I tried to install jekyll on fedora 21 with gem, but i get this result:

$ gem install jekyll
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/caleb/.gem/ruby/gems/posix-spawn-0.3.10 for inspection.
Results logged to /home/caleb/.gem/ruby/extensions/x86_64-linux/posix-spawn-0.3.10/gem_make.out

**Comment by pathawks** [comment] 2015-03-19 03:17
May I humbly suggest moving this issue to [jekyll/jekyll-help](https://github.com/jekyll/jekyll-help)?

**Comment by envygeeks** [comment] 2015-03-19 09:53
Install [ruby-devel](https://apps.fedoraproject.org/packages/ruby-devel) and next time for problems like this that aren't caused by bugs in Jekyll please use [Jekyll Talk](https://talk.jekyllrb.com) the new preferred method for generic questions unrelated to bugs.

**Closed by envygeeks** 2015-03-19 09:53 UTC
