### ISSUE TITLE
Support for Ruby version 2.7

### ISSUE THREAD

**Issue by BasJan81** [jekyll/jekyll#8049] opened 2020-03-07 22:15 UTC
Hello 👋

I just upgraded Ruby to version 2.7 _(release dec. 2019)_ and I noticed some deprecated warnings.

`
/usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated

/usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecated
`

Maybe it's time for little Jekyll 4.0.1 patch?   😊🍒

**Comment by Lominean** [comment] 2020-03-08 01:45
Duplicate of https://github.com/jekyll/jekyll/issues/7947

**Comment by ashmaroli** [comment] 2020-03-08 05:30
@BasJan81 As mentioned in https://github.com/jekyll/jekyll/issues/7947#issuecomment-587935866, please use the `master` branch until we ship a `v4.1.0`:
```ruby
gem "jekyll", github: "jekyll/jekyll"
```

**Closed** 2020-03-08 05:30 UTC
