### ISSUE TITLE
erro:our SCSS file `Lapada-ifce/css/main.scss` has an error on line 47: 

### ISSUE THREAD

**Issue by kaline** [jekyll/jekyll#6728] opened 2018-01-30 16:19 UTC
File to import not found or unreadable: base. Load path: /hoosegow/.bundle/ruby/2.4.0/gems/jekyll-theme-primer-0.5.2/_sass. For more information, see https://help.github.com/articles/page-build-failed-invalid-sass-or-scss/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

**Comment by ashmaroli** [comment] 2018-01-30 16:48
closing as this is definitely not a bug in Jekyll

**Closed by ashmaroli** 2018-01-30 16:48 UTC
