### ISSUE TITLE
 Liquid Exception: Unknown tag 'endfor' in index.html

### ISSUE THREAD

**Issue by adenseeley** [jekyll/jekyll#3802] opened 2015-06-18 20:23 UTC
The terminal is outputting: 
   
Liquid Exception: Unknown tag 'endfor' in index.html

Here is the code exibiting the problem, I cant seem to find where it is coming from I'm assuming its on the jekyll end because I cant find anything wrong with the code, at least that is relevent to the problems, though I am new therefore It may be my fault, anyhow here is the code 

```html
---
layout: default
---
<section class="hero">
    <h1>Freespace Creative!</h1>
</section>
<article class="row homepage-content">
    <section class="columns four">
        <ul class="posts">
            <h3>Latest Posts</h3> 
            {% for posts in site.posts %}
            <li>
                <a href="#">{{posts.title}}</a>
                <p>{{posts.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
     <section class="columns four">
        <ul class="posts">
            <h3>New Toutorials</h3> 
            {% for news in site.categories.events %}
            <li>
                <a href="#">{{news.title}}</a>
                <p>{{news.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
     <section class="columns four">
        <ul class="posts">
            <h3>Recent Events & Upcoming Projects</h3> 
            {% for news in site.categories.events %}
            <li>
                <a href="#">{{news.title}}</a>
                <p>{{news.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
</article>

<section class="mini-hero">
</section>

<article class="row homepage-content">
    <section class="columns four">
        <ul class="posts">
            <h3>New in Sculpture</h3> 
            {% for posts in site.posts %}
            <li>
                <a href="#">{{posts.title}}</a>
                <p>{{posts.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
     <section class="columns four">
        <ul class="posts">
            <h3>New in Drawing & Painting</h3> 
            {% for news in site.categories.events %}
            <li>
                <a href="#">{{news.title}}</a>
                <p>{{news.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
     <section class="columns four">
        <ul class="posts">
            <h3>New in Music</h3> 
            {% for news in site.categories.events %}
            <li>
                <a href="#">{{news.title}}</a>
                <p>{{news.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
</article>

<section class="mini-hero">
</section>

<article class="row homepage-content">
    <section class="columns four">
        <ul class="posts">
            <h3>New in Preforming Arts</h3> 
            {% for posts in site.posts %}
            <li>
                <a href="#">{{posts.title}}</a>
                <p>{{posts.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
     <section class="columns four">
        <ul class="posts">
            <h3>New in Writing</h3>            <li>
                <a href="#">{{news.title}}</a>
                <p>{{news.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
     <section class="columns four">
        <ul class="posts">
            <h3>New in Coding</h3> 
            {% for news in site.categories.events %}
            <li>
                <a href="#">{{news.title}}</a>
                <p>{{news.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
</article>

<section class="mini-hero">
</section>

<article class="row homepage-content">
    <section class="columns four">
        <ul class="posts">
            <h3>New in Design</h3> 
            {% for posts in site.posts %}
            <li>
                <a href="#">{{posts.title}}</a>
                <p>{{posts.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
     <section class="columns four">
        <ul class="posts">
            <h3>New in Photography</h3> 
            {% for news in site.categories.events %}
            <li>
                <a href="#">{{news.title}}</a>
                <p>{{news.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
     <section class="columns four">
        <ul class="posts">
            <h3>New in Coding</h3> 
            {% for news in site.categories.events %}
            <li>
                <a href="#">{{news.title}}</a>
                <p>{{news.meta}}</p>
            </li>
            {% endfor %}
        </ul>
    </section>
</article>
    
```

**Comment by envygeeks** [comment] 2015-06-18 20:26
Hi! While I hate to do this to you; I must ask that you ask your question on https://talk.jekyllrb.com because your problem is not directly related to Jekyll and this medium (ticket system) is for Jekyll bugs only. It seems that you have a question about a syntax error you are experiencing in Liquid (this is most likely not a bug.)  At this time we believe that this is not directly related to Jekyll or Liquid and is not a bug so I am closing this issue in favor of you sourcing a discussion and help from https://talk.jekyllrb.com.

Thanks and I'm sorry but I hope to see you at https://talk.jekyllrb.com

**Closed by envygeeks** 2015-06-18 20:26 UTC

**Comment by kleinfreund** [comment] 2015-06-18 20:43
Have a look at this. There is no for loop for that `{% endfor %}` in this part of the code you posted.


```html
<ul class="posts">
    <h3>New in Writing</h3>            <li>
        <a href="#">{{news.title}}</a>
        <p>{{news.meta}}</p>
    </li>
    {% endfor %}
</ul>
```

**Comment by envygeeks** [comment] 2015-06-18 20:45
Kinda just defeated the purpose of us trying to push people onto the help site and off this medium for non-bugs.  :disappointed:

**Comment by kleinfreund** [comment] 2015-06-18 20:57
Might as well just post the answer, but oh well.

**Comment by envygeeks** [comment] 2015-06-18 21:04
By that logic why is anybody paying for the forum that everybody wanted in the first place?  If you answer one persons question without asking them to ask in the proper place then everybody can invoke that one situation that one time and ask why is that person so special.  Why is this person more special than everybody else we've pushed onto the forum so we keep this medium clean?
