### ISSUE TITLE
Moving from Octopress to vanilla Jekyll: URLs with a trailing / go to GH's 404 error page

### ISSUE THREAD

**Issue by olalonde** [jekyll/jekyll#3310] opened 2015-01-15 14:40 UTC
Hi all.

I just moved my blog from Octopress to vanilla Jekyll and I have the following problem. Google indexed a bunch of my URLs with a trailing slash. e.g.:

http://syskall.com/some-crazy-and-not-so-crazy-startup-and-proje/index.html/

This was working with Octopress but it gives a 404 error with Jekyll.  http://syskall.com/some-crazy-and-not-so-crazy-startup-and-proje/index.html without the slash works though.

My question is: is there any way to make the URL with a trailing slash work so I don't break links?

The source code of my Jekyll site is here: https://github.com/olalonde/olalonde.github.com

**Comment by olalonde** [comment] 2015-01-15 15:34
I tried to set the permalink in the file:

```
permalink: /some-crazy-and-not-so-crazy-startup-and-proje/index.html/
```

That doesn't work however. For some reason, Jekyll won't create a folder called `index.html`.

**Comment by parkr** [comment] 2015-01-15 19:41
That's by design. Any html/htm extension will be interpreted as a file, not as a folder. Why do you have `index.html` folders?

**Comment by olalonde** [comment] 2015-01-15 19:44
That's what Octopress did for some reason: https://github.com/olalonde/olalonde.github.com/tree/47af20ede6eb7b2ce5cc2aef75616574aaede613

Now I'd just like to find a way to replicate this behaviour for those old links to not break external links.

**Comment by parkr** [comment] 2015-01-15 19:49
@imathis Have you ever seen this before?

**Comment by imathis** [comment] 2015-01-15 21:15
@parkr @olalonde I don't see how this could happen without some jiggery-pokery on the permalink setting. I don't do anything with generated posts in Octopress.

**Comment by parkr** [comment] 2015-01-17 23:04
Support ticket, not a bug. Closing.

**Closed by parkr** 2015-01-17 23:04 UTC
Labels: Question
