### ISSUE TITLE
Jekyll outputting css sourcemap as .css file

### ISSUE THREAD

**Issue by cmcnicholas** [jekyll/jekyll#8052] opened 2020-03-11 23:53 UTC
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Windows 10 |
| `jekyll`         | Latest     |
| `github-pages`   | No   |

---

## Expected Behaviour

Sass files should be built into the correct .css files

## Current Behavior

When running `bundle exec jekyll serve --drafts` the generated output for my Sass file is a css sourcemap with the extension .css

My gemfile specifies `gem "jekyll-sass-converter"`

My `assets` folder contains a css directory with a single `main.scss` (see image):

![image](https://user-images.githubusercontent.com/41394833/76474266-fe6ccc80-63f2-11ea-97fe-e78662fa6b41.png)

This `main.scss` looks like:

```
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@import 'minima';
```

I have a `_sass` directory that looks like:

![image](https://user-images.githubusercontent.com/41394833/76474311-22301280-63f3-11ea-8646-6cc886375650.png)

When serving my sites content I am using `<link rel="stylesheet" href="{{ "/assets/css/main.css" | relative_url }}" />` which renders to `<link rel="stylesheet" href="/assets/css/main.css" />` correctly. However the file that is served `/assets/css/main.css` from the `_site` directory is a CSS sourcemap, it looks like it is generated correctly however my styles are never served.

```
{
	"version": 3,
	"file": "main.css",
	"sources": [
		"main.scss",
		"_sass/minima.scss",
		"_sass/alloy/reset.scss",
		"_sass/alloy/position.scss",
		"_sass/alloy/color.scss",
		"_sass/alloy/elements/box.scss",
		"_sass/alloy/elements/list.scss",
		"_sass/alloy/elements/text.scss",
		"_sass/alloy/elements/button.scss",
		"_sass/alloy/elements/input.scss",
		"_sass/alloy/elements/alert.scss",
		"_sass/alloy/foundation.scss",
		"_sass/alloy/app.scss",
		"_sass/alloy/media-phone.scss",
		"_sass/alloy/media-tablet.scss",
		"_sass/alloy/media-desktop.scss",
		"_sass/magpie/styles.scss",
		"_sass/magpie/_base.scss",
		"_sass/magpie/_layout.scss",
		"_sass/magpie/components/index.scss",
		"_sass/magpie/components/_ikon.scss",
		"_sass/magpie/components/_note.scss",
		"_sass/magpie/components/_tip.scss",
		"_sass/magpie/components/_dropdown.scss",
		"_sass/magpie/components/_faq.scss",
		"_sass/magpie/components/_related-articles.scss",
		"_sass/magpie/components/_image-box.scss",
		"_sass/magpie/components/_tables.scss",
		"_sass/magpie/_other.scss",
		"_sass/magpie/_shame.scss"
	],
	"sourcesContent": [
		"@import 'minima';\n",
		"@charset \"utf-8\";\r\n@import 'alloy/reset', 'alloy/position', 'alloy/color', 'alloy/elements/box',\r\n  'alloy/elements/list', 'alloy/elements/text', 'alloy/elem
```

**Comment by ashmaroli** [comment] 2020-03-12 05:36
@cmcnicholas Are you able to reproduce this issue with a bare-bones site initialized by running
`jekyll new <path>`? If yes, could you commit the source and push it to a public repository on GitHub so that i can just clone the repo and check it out.

I'll transfer this ticket to the `jekyll-sass-converter` repository if I can confirm that this issue is not because of Jekyll 4.0

**Comment by cmcnicholas** [comment] 2020-03-12 09:21
I've managed to hunt this issue down, it is a problem with the `jekyll-polyglot` plugin, thanks for the help https://github.com/untra/polyglot/issues/107

**Comment by ashmaroli** [comment] 2020-03-12 09:24
Closing this then..

**Closed** 2020-03-12 09:24 UTC
