### ISSUE TITLE
URL Structure changes

### ISSUE THREAD

**Issue by medicart** [jekyll/jekyll#3463] opened 2015-02-14 18:41 UTC
How about having the option to remove the **trailing slash** from the url? 

This will make life easier for guys like us **migrating from Drupal** and want to keep the URL structure of the site without drowning in hundreds of 301s for search engines sake.

Look at example here: http://medicart.co.il

To achieve that, we had to use some tricky workarounds using **Amazon S3** capabilities and some unconventional usage of Jekyll pages rather than posts.

I can see how it can turn to be a big headache if one of the tricks will no longer function.

I think users will find this feature useful, and why not in the upcoming **version 3**? it shouldn't be that hard to add this, right?

**Comment by penibelst** [comment] 2015-02-14 19:28
Related to #3345 and many others.

@jekyll/owners I propose to introduce a new label for permalink design issues.

**Comment by benbalter** [comment] 2015-02-14 21:26
> How about having the option to remove the trailing slash from the url?... This will make life easier for guys like us migrating from Drupal and want to keep the URL structure of the site without drowning in hundreds of 301s for search engines sake.

In general, I'd rather Jekyll starts from the right way of doing things, and then working backward into functionality, rather than looking at how one piece of software does things, and working in backwards compatibility (that may or may not be right).

In this particular case (without starting a CMS flame war), other than those coming from Drupal, what's the value of slash-less URLs? Intuitively, and logically, it seems [trailing slashes are both the default and more defensible](https://cdivilly.wordpress.com/2014/03/11/why-trailing-slashes-on-uris-are-important/).

As for those migrating from Drupal, at least on GitHub Pages, we can see how hard it would be to redirect from `foo` to `foo/`, but I'm not sure how to do that without breaking at least some sites.

**Comment by medicart** [comment] 2015-02-14 21:45
@benbalter  agreed about the right way of doing things, I hated Drupal for forcing me to use that URL structure, however, I can think about at least one defensible reason for adding the trailing slash option:

I turns out that a lot of people will leave out the trailing slash when typing a url, even if exists, and unless you have a redirect rule in place, this will create 404. Nowadays, when many people turns to S3 or similar solutions for site hosting, **htaccess** will not be a viable solution. Shouldn't it be at least in a form of an option in Jekyll?

**Comment by benbalter** [comment] 2015-02-14 21:50
> I[t] turns out that a lot of people will leave out the trailing slash when typing a url

Great point. Under that same logic, however, wouldn't then, some users (presumably more, given the design pattern's widespread adoption) include the trailing slash? It seems the issue is not trailing slash or not, but providing a 301 redirect from one to the other, which is not something Jekyll can do technically, AFAIK.

**Comment by willnorris** [comment] 2015-02-14 21:51
the current jekyll 3 beta is actually pretty close to fully supporting post URLs without trailing slashes or extensions.  You can already specify a permalink setting with no trailing slash and jekyll will generate the correct URLs.  The main remaining issue is that generated files on disk also don't have extensions.  I've been arguing on #2294 that the files on disk should always include extensions, and I believe @parkr agrees.

@benbalter: note that the article you linked to is talking about including trailing slashes on URLs that identify **collections** of resources, not the individual resources themselves.  Even the example post mentioned in the article does not include a trailing slash: `http://some-blog.gbee.io/blog/posts/holiday`.  I actually completely agree with the article for all of the reasons he talks about, but that argument doesn't apply here (in my mind at least).  An individual blog post is not a collection, it's an individual resource and therefore doesn't need a trailing slash.  Of course, if you like trailing slashes, that's fine, but I don't think there's a strong argument that jekyll should enforce them (implicitly or explicitly).

**Comment by medicart** [comment] 2015-02-15 00:10
@willnorris That's good news. I could live with the extension-less files on disk. My main concern was that I'm using Jekyll in a way that is not naturally supported( #3345) in order to achieve the extension-less option and that way may not work in future updates.

In general, I think Jekyll grew way beyond a simple blogging platform to a full fledged website management system so it's probably time to ditch the paradigm of content revolving around posts as the default and have other option readily available.

To date I have 10 production websites running on Jekyll, none of them are blogs or contain blogs and most of them migrated from Drupal so I'm stuck with this URL structure for the near future. The sites migrated from Wordpress felt right at home though :).

**Comment by parkr** [comment] 2015-02-15 06:10
> The main remaining issue is that generated files on disk also don't have extensions. I've been arguing on #2294 that the files on disk should always include extensions, and I believe @parkr agrees.

@willnorris: I'm glad you brought up current `master` work. We can either always write the file with an extension when the `permalink` template doesn't include the `:output_ext` key (this ensures `page.url` works as expected), or we allow the manipulation of the filesystem output independent from the configuration of `page.url`. The former makes more sense to me. In this scenario:

- `permalink: /:year/:name`
- `page.url` = `/2015/content-negotiation`
- creates `_site/2015/content-negotiation.html`

Look right?

**Comment by willnorris** [comment] 2015-02-15 07:05
:+1: yep

**Comment by willnorris** [comment] 2015-03-09 07:40
Fixed in #3490.  You can see draft docs for how to use this in #3556.

**Closed by willnorris** 2015-03-09 07:40 UTC
Labels: Discussion
