### ISSUE TITLE
 Unable to download data from https://rubygems.org/

### ISSUE THREAD

**Issue by BUPT-CS** [jekyll/jekyll#3946] opened 2015-08-29 13:26 UTC
When I use <em>gem Install XXX</em> in China, I find the source library are forbidden.
And I get the following:

> ERROR:  Could not find a valid gem 'jekyll' (>= 0), here is why:
>Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer >- SSL_connect (https://rubygems.org/latest_specs.4.8.gz)

I know you've got a solution, but I hope you can post it on the page: http://jekyll.bootcss.com/docs/troubleshooting/
Thank You!

**Comment by parkr** [comment] 2015-08-29 21:14
Duplicate of #1409.

**Closed by parkr** 2015-08-29 21:14 UTC
