### ISSUE TITLE
Markdown code blocks not being rendered as <pre>s

### ISSUE THREAD

**Issue by malyw** [jekyll/jekyll#4515] opened 2016-02-12 23:45 UTC
I have **jekyll 3.1.0**
**markdown: kramdown** (which would be only one working on Github after May 1st)
and code
<pre>```javascript
var url = 'https://api.github.com/users/malyw';
fetch(url);
```</pre>
produces
```html
<p><code class="highlighter-rouge">javascript
var url = 'https://api.github.com/users/malyw';
fetch(url);
</code></p>
```
Only changing to 
```
{% highlight javascript %}
...
{% endhighlight %}
```
helps, but in this case I cannot use any 3rd party Markdown editors as they don't understand Liquid syntax.

**Comment by envygeeks** [comment] 2016-02-13 06:59
This is a duplicate of https://github.com/jekyll/jekyll/issues/4448 and is already resolved.

**Closed by envygeeks** 2016-02-13 06:59 UTC

**Comment by fkpwolf** [comment] 2016-09-04 10:13
I have Jekyll 3.2.1 and still had this issue. Spend half of day and found I have to add new line before ````javascript`
