### ISSUE TITLE
feat: OpenBSD support

### ISSUE THREAD

**Issue by igor-petruk** [jekyll/jekyll#9493] opened 2023-11-19 13:41 UTC
## Summary

Installing a gem on OpenBSD fails

```
rake aborted!
NotImplementedError: dart-sass for x86_64-openbsd7.4 not available at https://github.com/sass/dart-sass/releases/tag/1.69.5


Caused by:


Tasks: TOP => default => install => cli.rb => dart-sass
(See full trace by running task with --trace)
rm -rf /usr/local/lib/ruby/gems/3.2/gems/sass-embedded-1.69.5/ext/sass/ruby
```

## Motivation

It would be nice to use Jekyll on OpenBSD

## Unresolved Questions

I am reporting it here, because there is maybe a way to install it without this dependency or use some mitigation. OpenBSD support in `dart-sass` could be another issue

**Comment by ntkme** [comment] 2023-11-19 16:42
You can pin jekyll-sass-converter to previous sassc based version by add the following to `Gemfile`:

``` ruby
gem 'jekyll-sass-converter', '~> 2'
```

**Comment by igor-petruk** [comment] 2023-11-19 18:47
> You can pin jekyll-sass-converter to previous sassc based version by add the following to `Gemfile`:
> 
> ```ruby
> gem 'jekyll-sass-converter', '~> 2.2'
> ```

Thank you, I will try

**Comment by whitemossyoak64** [comment] 2023-11-30 08:44
> ## Summary
> Installing a gem on OpenBSD fails
> 
> ```
> rake aborted!
> NotImplementedError: dart-sass for x86_64-openbsd7.4 not available at https://github.com/sass/dart-sass/releases/tag/1.69.5
> 
> 
> Caused by:
> 
> 
> Tasks: TOP => default => install => cli.rb => dart-sass
> (See full trace by running task with --trace)
> rm -rf /usr/local/lib/ruby/gems/3.2/gems/sass-embedded-1.69.5/ext/sass/ruby
> ```
> 
> ## Motivation
> It would be nice to use Jekyll on OpenBSD
> 
> ## Unresolved Questions
> I am reporting it here, because there is maybe a way to install it without this dependency or use some mitigation. OpenBSD support in `dart-sass` could be another issue

**Comment by fpusersuggest** [comment] 2023-12-02 04:19
hello guys, I installed jekyll on year 2022 without any problems on openbsd. But now I have the same problem as Igor.
To be honest I don't understand where should I have to add that string.. you say about a Gemfile.. 
so I have to create a random Gemfile and insert that string ?
anyway, I tried to install jekyll but as local user because if I install everything with root gem install files around and they conflict with the OS packages.. so I tried the following:

`$ /usr/local/bin/gem32 install jekyll bundler --user-install`

and the following are the errors I get:
```
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: /home/my_user/.local/share/gem/ruby/3.2/gems/sass-embedded-1.69.5/ext/sass
/usr/local/bin/ruby32 -rrubygems /usr/local/lib/ruby/gems/3.2/gems/rake-13.0.6/exe/rake RUBYARCHDIR\=/home/my_user/.local/share/gem/ruby/3.2/extensions/x86_64-openbsd/3.2/sass-embedded-1.69.5 RUBYLIBDIR\=/home/my_user/.local/share/gem/ruby/3.2/extensions/x86_64-openbsd/3.2/sass-embedded-1.69.5
gem install --force --install-dir /home/my_user/.local/share/gem/ruby/3.2/gems/sass-embedded-1.69.5/ext/sass/ruby --no-document --ignore-dependencies --platform x86_64-openbsd-7.4 --version 1.69.5 sass-embedded
rake aborted!
NotImplementedError: dart-sass for x86_64-openbsd7.4 not available at https://github.com/sass/dart-sass/releases/tag/1.69.5
/home/my_user/.local/share/gem/ruby/3.2/gems/sass-embedded-1.69.5/ext/sass/Rakefile:310:in `default_dart_sass'
/home/my_user/.local/share/gem/ruby/3.2/gems/sass-embedded-1.69.5/ext/sass/Rakefile:27:in `block (2 levels) in <top (required)>'
/home/my_user/.local/share/gem/ruby/3.2/gems/sass-embedded-1.69.5/ext/sass/Rakefile:27:in `fetch'
/home/my_user/.local/share/gem/ruby/3.2/gems/sass-embedded-1.69.5/ext/sass/Rakefile:27:in `rescue in block in <top (required)>'
/home/my_user/.local/share/gem/ruby/3.2/gems/sass-embedded-1.69.5/ext/sass/Rakefile:21:in `block in <top (required)>'

Caused by:

/home/my_user/.local/share/gem/ruby/3.2/gems/sass-embedded-1.69.5/ext/sass/Rakefile:207:in `gem_install'
/home/my_user/.local/share/gem/ruby/3.2/gems/sass-embedded-1.69.5/ext/sass/Rakefile:23:in `block in <top (required)>'
Tasks: TOP => default => install => cli.rb => dart-sass
(See full trace by running task with --trace)
rm -rf /home/my_user/.local/share/gem/ruby/3.2/gems/sass-embedded-1.69.5/ext/sass/ruby

rake failed, exit code 1

Gem files will remain installed in /home/my_user/.local/share/gem/ruby/3.2/gems/sass-embedded-1.69.5 for inspection.
Results logged to /home/my_user/.local/share/gem/ruby/3.2/extensions/x86_64-openbsd/3.2/sass-embedded-1.69.5/gem_make.out
Successfully installed bundler-2.4.22
Parsing documentation for bundler-2.4.22
Done installing documentation for bundler after 0 seconds
1 gem installed
```

My openbsd version is 7.4. I also tried ruby30, ruby31 and ruby32. But always I get the same issue.

**Comment by fpusersuggest** [comment] 2023-12-02 10:51
Hello again,
I solved the problme installing that gem in this way:

`$ gem install jekyll-sass-converter -v 2.2  --user-install`

the only error I found is an "unknown encoding name"

```
Installing ri documentation for concurrent-ruby-1.2.2
Parsing documentation for i18n-1.14.1
Installing ri documentation for i18n-1.14.1
Parsing documentation for http_parser.rb-0.8.0
unknown encoding name "chunked\r\n\r\n25" for ext/ruby_http_parser/vendor/http-parser-java/tools/parse_tests.rb, skipping
Installing ri documentation for http_parser.rb-0.8.0

```

Now I try to build a new site. Thanks.

**Comment by whitemossyoak64** [comment] 2023-12-02 23:39
Thanks

**Comment by mattr-** [comment] 2024-05-23 16:47
Treating this as a duplicate of #9462 since it would seem all the BSDs are affected.

**Closed by mattr-** 2024-05-23 16:47 UTC
Labels: feature
