### ISSUE TITLE
issue with the jekyll installation

### ISSUE THREAD

**Issue by jbh225** [jekyll/jekyll#5647] opened 2016-12-08 19:56 UTC
Hello,

I started to install jekyll on my pc with windows 10 and I had a problem nevertheless I followed the quick start guide. When I'm on my C drive, when I get into the folder I created, I do not have thoss following folders "includes" file "css" "layouts" "sass". And I do not understand why. Can you help me?

**Comment by novoNagu** [comment] 2016-12-08 20:12
What version of jekyll are you using? New Jekyll uses gemified themes which will not have those folders unless you create them

**Comment by jbh225** [comment] 2016-12-08 20:20
I am using the version 3.3.1.
So do I have to create them? but I don't know how. This is the first time I use this...

**Comment by Crunch09** [comment] 2016-12-08 21:23
Hi @jbh225 ,

you can just create these folders in the main folder of your Jekyll project. Right now you're probably using `minima` as your theme which is the default theme gem bundled with Jekyll.
[Here](https://github.com/jekyll/minima#customization) is an explanation on how to customise your theme. Hope this helps!

**Comment by pathawks** [comment] 2016-12-08 21:32
Closing, as this is not a bug in Jekyll.

Our documentation, however, could possibly be clearer about the file structure of a new site when using a theme. Would be happy to review a PR :+1:

**Closed by pathawks** 2016-12-08 21:32 UTC
Labels: support, windows
