### ISSUE TITLE
Generating files without extension

### ISSUE THREAD

**Issue by ujovlado** [jekyll/jekyll#4418] opened 2016-01-28 15:43 UTC
With `jekyll -v 3.1.0` `jekyll-redirect-from` plugin generates files without ".html" suffix.

With `jekyll -v 3.0.0` it works.

Steps to reproduce:
```bash
jekyll -v
# jekyll 3.0.0
jekyll b
# your files with html extension
gem install jekyll -v 3.1.0
jekyll -v
# jekyll 3.1.0
jekyll b
# your files without html extension
```

(same issue: https://github.com/jekyll/jekyll-redirect-from/issues/95)

**Comment by envygeeks** [comment] 2016-01-28 15:44
Please cross post your entire posts so we don't have to traverse back and forth. Thanks.

**Comment by parkr** [comment] 2016-01-28 15:45
I believe this is fixed in master.

**Comment by ujovlado** [comment] 2016-01-28 15:54
@envygeeks updated

**Comment by parkr** [comment] 2016-01-28 22:35
This is a duplicate of https://github.com/jekyll/jekyll/issues/4397

```irb
>> File.extname("/redirect-from/me/")
=> ""
```

**Closed by parkr** 2016-01-28 22:35 UTC
