### ISSUE TITLE
feat: Should unknown tags perhaps be handled as warnings instead of errors?

### ISSUE THREAD

**Issue by dmalan** [jekyll/jekyll#7579] opened 2019-03-18 19:30 UTC
## Summary

Because Jekyll is often run in safe mode (as on GitHub Pages), it's not always possible to add support for custom tags, even if those custom tags could be rendered client-side, as via JavaScript-based "polyfills." It would be convenient to be support custom tags like

```
{% foo %}
```

that could be rendered server-side in non-safe mode or, if need be, client-side via JavaScript, a la a JavaScript template, a React component, etc.

## Motivation

To make it easier for teachers to generate homework assignments using Markdown, we currently use Jekyll in non-safe mode so as to support tags like:

```
{% video "https://youtu.be/dQw4w9WgXcQ" %}
```

that, when parsed, yields HTML like:

```
<iframe allowfullscreen src="https://www.youtube.com/embed/dQw4w9WgXcQ"></iframe>
```

thereby making it more convenient to add content without falling back on raw HTML. It'd be ideal, though, if teachers could use these same plugins on platforms like GitHub Pages, but Jekyll builds fail when tags are unrecognized (cf. https://help.github.com/en/articles/page-build-failed-unknown-tag-error), as with:

```
Liquid Exception: Liquid syntax error (line 1): Unknown tag 'video' in README.md
```

If unknown tags were instead treated as warnings (or if it were possible to suppress those errors via some key in `_config.yml`), any Liquid tags that can't be parsed server-side by plugins could instead be parsed by client-side JavaScript.

We'd hoped that `error_mode: warn` might do the trick, per https://jekyllrb.com/docs/configuration/liquid/, but seems that's only "applicable to syntax errors within tags" (cf. https://github.com/Shopify/liquid/issues/533#issuecomment-94305036).

By contrast, when Kramdown doesn't recognize a custom Kramdown extension (e.g., `{::foo}`), it ignores the unrecognized tag (i.e., outputs it unchanged), without erring. Cf. https://kramdown.gettalong.org/syntax.html#extensions.

## Reference-level explanation

The source of this sort of `Liquid Exception` is https://github.com/jekyll/jekyll/blob/master/lib/jekyll/renderer.rb#L121-L133, and the `Liquid::SyntaxErrror` exception raised only seems to have two fields:

```
message: Unknown tag 'video'
line_number: 1
```

## Drawbacks

Barring changes to Liquid, it seems the only way to distinguish an `Unknown tag` from another `SyntaxError` might be string comparison.

It'd be a bit hackish to "polyfill" missing plugins.

But with Jekyll's safe mode and whitelist pretty stringent, it would let authors stick with one templating language (Liquid) rather than employ another just for custom tags (that can be rendered safely enough but just aren't whitelisted by, e.g., @benbalter's [pages-gem](https://github.com/github/pages-gem)).

**Comment by ashmaroli** [comment] 2019-03-19 02:42
@dmalan Unfortunately, there's very little Jekyll can do to help in this case. The problem is not with Jekyll's `safe` mode per se.

The issue ticket you've linked makes a mention of "`rescue`-ing the exception".
While that is possible, the main issue is that **`Liquid` does not "process"** a document once the error has been raised. So we'll be forced to **output the raw source code of the document** (which in turn may or may not cause further issues with `kramdown` and HTML validators.)

**Comment by ashmaroli** [comment] 2019-03-19 02:45
I'm closing this since this feature is best requested at Liquid's repository.

**Closed by ashmaroli** 2019-03-19 02:45 UTC
Labels: feature, upstream-issue

**Comment by ashmaroli** [comment] 2019-03-19 02:59
@dmalan However, I do have a workaround for you:
Wrap your tag within Liquid's `raw` tags. Then, continue rendering the tag with JavaScript.
### Markdown source document:
```
{% raw %}{% video "https://youtu.be/dQw4w9WgXcQ" %}{% endraw %}
```
### Generated HTML file:
```html
<p>{% video "https://youtu.be/dQw4w9WgXcQ" %}</p>
```
### Final HTML at client-side (JS-enabled browser):
```html
<p><iframe allowfullscreen src="https://www.youtube.com/embed/dQw4w9WgXcQ"></iframe></p>
