### ISSUE TITLE
Add filter for generating URL paths which are relative to the current document

### ISSUE THREAD

**Issue by BigBlueHat** [jekyll/jekyll#7185] opened 2018-08-16 19:20 UTC
Currently there is no way to generate a path (intended for an `href` or `src`) which is relative to the output documents location within the site tree.

Right now, there are two filters available:
 - `absolute_url` = `http://example.com/path/to/thing`
 - `relative_url` = `/path/to/thing`

What's missing is the ability to create a path which is relative to the current page (when generated) such as `to/thing` when referenced from a document in `/path/`. This would be especially useful when dealing with sites published to multiple locations where the use of `baseurl` would cause inconsistencies across domains (i.e. `example.com/projects/subsite/` vs. `example.github.io/subsite/`).

I'd like to propose the addition of a `relative_path` filter which could be used from pages and *templates* which would create such relative paths.

This name comes from terminology used in the URI spec [RFC 3986](https://tools.ietf.org/html/rfc3986#section-4.2)'s section on Relative Reference:
> A relative reference that does not begin with a slash character is termed a relative-path reference.

The current `relative_url` could be *optionally* aliased (and eventually removed?) as `absolute_path` to make the outputs clearer. Again, quoting from the URI spec:
> A relative reference that begins with a single slash character is termed an absolute-path reference.

The end result would be these three filters for creating URLs throughout templates and Liquid-enhanced content:
 - `absolute_url` = `http://example.com/path/to/thing`
 - `absolute_path` = `/path/to/thing` (currently `relative_url`)
 - `relative_path` = `to/thing` (when used from `/path/` for instance)

Thanks for considering this!
🎩 

---
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.
- [x] I am on (or have tested on) ***Windows*** 10+

**Comment by BigBlueHat** [comment] 2018-08-16 19:27
Also, I'm aware this is a perennial request (re: #6360 and #6362), but as noted in both those threads there are many Jekyll deployment scenarios (such as GitHub Pages) where adding Plugins is not an option. Additionally, the expectation is that relative paths would be core to any content system dealing in tree structures, so having this "on hand" all the time (without any additional installation) would be invaluable (and appreciated).

**Comment by DirtyF** [comment] 2018-08-16 20:41
Rather than another filter, this could be a global (config) option that when set would rewrite all relative URLs (not the absolute ones), e.g. a relative link to `/about/` would become a  relative path to `../../about/`.

**Comment by pathawks** [comment] 2018-08-17 13:54
> there are scenarios when you might want to generate either or both, so I'm not sure doing this globally…

Like what? When would I want some links to be “relative” to the current page and other links on the same page to simply be relative to root?

**Comment by BigBlueHat** [comment] 2018-08-20 15:32
If image assets (etc) are deployed to a separate server/URL (or CDN) than from the main site, then generating URLs for those could benefit from the current `relative_url` (proposed `absolute_path`) as it would be an absolute path from the CDN's domain (or base URL).

Regardless, having the output of a method change based on a config parameter seems very confusing. I'd rather have all the options available for creating paths and URLs at my disposal.

**Comment by pathawks** [comment] 2018-08-20 16:34
> I'd rather have all the options available for creating paths and URLs at my disposal.

Which one will themes use? If an asset is being served from a CDN such that you do not want a relative URL, wouldn’t you just use the existing absolute URL filter?

I’m unconvinced that this additional complexity would provide benefit to a significant number of users.

**Comment by DirtyF** [comment] 2018-08-20 17:57
Dealing with responsive images is more than just changing a domain's name. Have you checked if there's already a plugin for your CDN provider like https://github.com/nhoizey/jekyll-cloudinary?

**Comment by pathawks** [comment] 2018-08-20 18:06
Closing as duplicate of #6360

**Closed by pathawks** 2018-08-20 18:06 UTC

**Comment by BigBlueHat** [comment] 2018-09-05 15:03
Here's another scenario to consider. I have one Jekyll site that lives at 3 different URLs:
 - https://www.w3.org/2018/json-ld-wg/
 - https://w3c.github.io/json-ld-wg/
 - http://localhost:4000/

If there were a "relative to root" function in Jekyll, all would be well. However, since there isn't, I have to pick and set a `baseurl` in the `_config.yml` and break one of them. Since the `github.io` link isn't the primary one, that's the one I've broken currently. *But I shouldn't have to pick.*

The conversations on #6360 seem to show great interest in this feature, and it's concerning that it continues to be dismissed and that issues have been locked. Please reconsider. Thanks.

**Comment by BigBlueHat** [comment] 2018-09-27 14:52
Currently working on a site that *will* be the root site (i.e. at `/`), but for now it's hosted at `/sub-dir/` on GitHub. If I had this feature, I could avoid ever setting `baseurl` and (more importantly) having to *change* it when going into production. Regardless, when I change it, it's going to break either the testing site or the production site.

I'd love to know why adding this is seen as such a bad idea given the reasons listed here and the requests made in #6360.

**Comment by ashmaroli** [comment] 2018-09-27 15:44
@BigBlueHat #6360 Are you willing to send a PR towards implementing this..? It should have a robust set of tests accompanying it too..

**Comment by BigBlueHat** [comment] 2018-09-27 19:44
Thanks, @ashmaroli! A friend of mine and I are working on resurrecting #6362, but with the `relative_path` terminology mentioned here. PR forthcoming! 😁

**Comment by svnpenn2** [comment] 2018-11-15 23:18
https://github.com/jekyll/jekyll/pull/7281
