### ISSUE TITLE
push, pop, shift, unshift deeply unintuitive [jekyll/docs/_docs/templates.md]

### ISSUE THREAD

**Issue by swizca** [jekyll/jekyll#5806] opened 2017-01-22 08:46 UTC
- [x] This is a feature request.
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

Re: http://jekyllrb.com/docs/templates/ `Array Filters` - `Push, pop, shift, and unshift elements from an Array.`

These are *deeply unintuitive*

push and pop are *stack* commands.

*push* puts the new element at the *beginning* of the stack (array), returning the new array.

*pop* removes the element from the *beginning* of the stack (array), returning that element.

Apparently push and pop ***do not*** mean these usual things.

*shift*, well, turns out to do the expected, but the confusion of the above makes one not trust they're understanding what they're reading correctly. Same for unshift.

As well, the reader is left wondering ... *where* is the *element*, and *where* is the *array*?
- i.e. one might like to further or individually process the resulting element and/or (remainder of?) the resulting array.

Could the help article expand the brevity of the description, or link to some other page that does so?

Ultimately, I did find https://github.com/jekyll/jekyll/pull/2895/files which explains things.

push - add element to end (== append)
pop - remove last element (== truncate [?])
shift - remove first element (== pop, or rather, pop gets [results in] the element, this is the result [impact] upon the array.)
unshift - add element to beginning (== push)

In *theory*, one should then be able to iterate through an object, *however*, it seems unlikely that the operations are *non-destructive*. Could the other page expand on that and affirm non-/destructive examples.

e.g. (pseudo)
```
while page.first
{
  element = page.first
  page.shift
  element processing
}
```

Thanks for listening.
~~~~

**Comment by pathawks** [comment] 2017-01-23 00:03
> Apparently push and pop **_do not_** mean these usual things

It is not unconventional to use an array as the data structure backing a stack; this is what Ruby does. In fact, our filters are just a very thin wrapper on top of [Ruby's stack methods](https://ruby-doc.org/core-2.2.0/Array.html#method-i-push), and the behavior is exactly what Ruby's documentation (as well as [our own documentation](http://jekyllrb.com/docs/templates/#filters)) claim.

> it seems unlikely that the operations are non-destructive

You may verify that these filters are non-distructive by [examining the code](https://github.com/jekyll/jekyll/blob/6fb05e07999e9dcd69eaf0597cb33ce10bda1b01/lib/jekyll/filters.rb#L283-L309). Before we do anything else, we make a duplicate of the input object.

**Comment by swizca** [comment] 2017-01-23 00:30
> >Apparently push and pop do not mean these usual things
> It is not unconventional to use an array as the data structure backing a stack;

I didn't say it was.

> this is what Ruby does

That assumes one knows Ruby.

push and pop and stacks long pre-date Ruby. What I mean with:
> Apparently push and pop do not mean these usual things

then, is that even Ruby is not using push and pop the usual way.

Which reinforces my point and request of a touch less brevity on the page.

> You may verify that these filters are non-distructive by examining the code. Before we do anything else, we make a duplicate of the input object.

I think you mis-take me. I don't doubt they are non-destructive. What I doubt is that one will intuitively get where one expects to go in likely scenarios.

e.g.
`
{% while page%}
{% process page.first %}
{% page | shift %}
{%endwhile %}
`

I suspect one will endlessly process the first element. (As things are non-destructive.)

Regardless, I don't mean to start a debate here ... all I have asked is that the pages have a titch more explanation.

**Comment by pathawks** [comment] 2017-01-23 00:59
PRs are always welcome :+1:

**Comment by swizca** [comment] 2017-01-23 01:41
D'OH!

Of course, you're right. And it's just documentation, so easy enough.

Just wish one didn't have to fork the project to add a sentence to the docs.

Not today, but I take your point, and thanks for the reminder.

**Comment by pathawks** [comment] 2017-01-23 05:18
@swizca You seem to have a keen sense of how to explain things in a way that makes them seem approachable; I wouldn't be surprised if you contributed more than just “a sentence” to our docs. :wink:

Or, put another way, I would love it if you could find some time to contribute some of your talents to our documentation :+1:

**Comment by HuStmpHrrr** [comment] 2017-01-23 23:22
i first heard of push, pop, shift, unshift in perl5. this is totally intuitive. even in python,

```python
[1, 2, 3].pop() // gives 3
```
so the top 3 most popular scripting languages share the same convention. maybe you can briefly discuss how you get your intuition.

**Comment by swizca** [comment] 2017-01-24 09:30
:-) Well    @HuStmpHrrr  ... if I go back to the '70's and my first computer courses ... working with the basics of processors (or x86, at least) - which is to say, the basis for most everything else we use today, certainly long before perl ...

Y'know ... *machine language* and *assembler* ...

You have a *block of memory* for your *program*. (Approximately) *compiling* would *allocate* the necessary number of *data bytes* for the variables (*data*), and assign them from the **top** of the block working down. (*Code* [i.e. assembler / machine language] working up from the **bottom** - byte 1 [0].) Assigned immediately below this *data pointer* [DP, IIRC] is the *stack pointer* [*SP*]. Think of a nail embedded in the ceiling, pointy end down, and storing paid food order tickets by sticking them through the nail.

So you *PUSH* a *value* *on*to the *stack*, (effectively) *decrementing the SP*. Note: values, there is no knowledge of the stack / length. i.e. there is no concept of array (of bytes) here. (It's accurate, but not in the ecosystem.) i.e. no array is returned or provided or mentioned.

Or you *POP* a value *off* the stack - returning the pop'ped value, (effectively) *incrementing the SP*.

[Misbehaving programs, or running out of (stack) space were a frequent cause of the ubiquitous '*stack fault*'s.]

*This is the very basis of stacks, pushing and popping, for many decades - they mean just that and are immutable. In the same way 'byte' is.* [Don't get me started on 'word's! :-) ]

IIRC, '*shift*' used to mean a simple rotation of elements. Moving elements left or right, to the end or beginning, even, IIRC. Think of the array as a circle of bytes. Shifting really just moves the pointer to the start of the circle of bytes left or right - effectively changing the address of [0]. (Think circular linked list.)

Granted, since, shift means to move an element *off* the array. Thus shifting something onto the array makes no sense / is unintuitive.

Which was my point of the OP - the article is a little too brief.

(Bearing in mind @pathawks excellent reminder. :-) )

**Comment by ashmaroli** [comment] 2017-01-24 11:07
@swizca Do you have a blog online, by any chance? Your write-ups make a delightful read.. :smiley:  :+1:

**Comment by swizca** [comment] 2017-01-24 12:01
@ashmaroli , no blog. Sorry. :blush:

**Comment by HuStmpHrrr** [comment] 2017-01-24 13:21
@swizca OK that explains. However, assembly works in this way for an implementation aware reason, while other languages work more in a consistent manner. It's a different mindset so I won't call that *counter-intuitive*. In maths, index starts with 1, but in most of the languages it starts with 0. Is that counter-intuitive for mathematician? Yes, but that doesn't make a fair claim.

**Comment by swizca** [comment] 2017-01-24 16:12
@HuStmpHrrr um ... you misunderstand ...
> However, assembly works in this way for an implementation aware reason, while other languages work more in a consistent manner.

*By definition* ALL OTHER LANGUAGES COME FROM ASSEMBLY. If other languages differ ... **`they` are *`by definition`* inconsistent**.

This is like saying the sky is not blue. :grin:

>  languages it starts with 0

'cause of assembler. The [x] is the offset of size() length from 0 of the address at which a variable points.  So the first element of the data is at 0. Much the same for stacks, push, and pop. *It just **is**.*

> "please tell me what the first element of the array is", do I mean 1st or 0th?
- you mean the first. Full stop. (You did not ask for the initial, or the 2nd.)

Let's just leave this with, as originally and simply requested:
> Could the help article expand the brevity of the description, or link to some other page that does so?

And let this thread go.

**Comment by pathawks** [comment] 2017-01-24 16:23
A PR to update documentation would certainly be welcome.

This is not the place for general CS debates.

**Closed by pathawks** 2017-01-24 16:23 UTC
Labels: documentation, support
