### ISSUE TITLE
Problem installing Jekyll 3 on OS X 10.11.6 according to website instructions

### ISSUE THREAD

**Issue by strawhead** [jekyll/jekyll#5486] opened 2016-10-15 16:00 UTC
I am running Jekyll 3.2.1 on OS X 10.11.6. It isn't working well at all, and after several hours trying to figure out what the problem is, I am not much closer. There are a bunch of different problems with almost every aspect of Jekyll on my computer.

#### Relevant Software Versions
* OS X 10.11.6
* Ruby 2.3.1p112
* Bundler 1.13.2
* Ruby 2.3.1p112
* gem 2.5.1
* Jekyll 3.2.1

When I create a new site with `jekyll new blahblah`, the resulting folder doesn't have all of the expected directories inside, like `_includes`. I am *not* concerned with directories created by `jekyll build` here. Jekyll can still build the site. When it does, the site seems to have additional problems. For example: 

* It has an absolute URL for CSS so that `jekyll serve` shows a local site that doesn't have any styling.
* Setting pagination doesn't work. Errors or no errors and no pagination.

Installing themes results in an error about pygments. I can install pygments.rb, bundle, etc., and still get the same error.

I originally had trouble upgrading because of System Integrity Protection. I'm not sure if SIP or the latest version of Jekyll is the problem. I have 3.0.? on a virtual machine (running Ubuntu 14.10) that still works as expected. I got it working with rbenv.

I have uninstalled and re-installed Ruby under homebrew, and completely removed and reinstalled Jekyll and related gems. This is the *best* I have had it work. It's been a little while since I used Jekyll last, and it worked fine on my machine prior to upgrade. I'm not familiar enough with Jekyll yet to pinpoint the source of the problem except to say that installing Jekyll according to the instructions on the Jekyll website under OS X 10.11.6 doesn't really work.

**Comment by ashmaroli** [comment] 2016-10-15 17:52
Hello @strawhead, Jekyll has been upgraded to v3.3.0 now.. In short, 
- Since `v3.2.0`, Jekyll no longer expects to find `_layouts`|`_includes`|`_sass` directories at the `source_dir` as its **included** inside the theme gem **minima**
- With v3.3.0, 
  - it no longer expects to see a `css` directory with `main.scss` inside it, at the `source_dir` either.. its **included** inside the theme gem within a new `assets` folder.
  - `index.html` is now an empty `index.md` rendered by a new `home` layout. If _jekyll-pagination_ throws an error regarding missing index.html, simply rename `index.md` to `index.html`
  - minima no longer sets an absolute url for its CSS
  - _and lots more..._

So go ahead and give Jekyll 3.3.0 a try.. :smiley:

**Comment by strawhead** [comment] 2016-10-17 10:15
Thanks! I'll check it out. I haven't had time to spend several consecutive hours with Jekyll recently, and that's made it harder to pinpoint problems... hopefully they're all solved by the updates.

**Comment by pathawks** [comment] 2016-10-17 14:21
If you have specific questions about themes, you can try https://talk.jekyllrb.com/

Closing this issue, as it is not a bug in Jekyll.

**Closed by pathawks** 2016-10-17 14:21 UTC

**Comment by strawhead** [comment] 2016-10-17 15:45
Thanks @pathawks, I found enough answers here that I wouldn't have needed to report a bug. A few links for others who find this:
* [Directories that aren't in a new Jekyll site now](https://talk.jekyllrb.com/t/incomplete-directory-structure-generated-with-new-command/2714)
* [Jekyll not rendering styles](https://talk.jekyllrb.com/t/my-jekyll-github-website-doesnt-render-any-styles/2906/2)
* [Installation problems on El Capitan](https://github.com/met-office-lab/blog/issues/338) because of System Integrity Protocol (SIP)
