### ISSUE TITLE
Segfault on Build in Yosemite

### ISSUE THREAD

**Issue by qguv** [jekyll/jekyll#3606] opened 2015-03-22 03:45 UTC
Hi there,

I get a segfault when installing Jekyll on Yosemite. Here's a [trace][] from `jekyll build -t`. Some time in the past, maybe last year, I had Jekyll working just fine.

I've recompiled ruby and all gems using an unset `$CC`, `CC="llvm-gcc"`, and `CC="gcc"` as well as providing the direct paths of each of those. I've tried gcc-4.2 and 4.9.

I found past posts pointing to posix-spawn as the culprit, but uninstalling and reinstalling didn't help.

Using rbenv with 2.0.0-p643 but not wed to it.

Any theories as to what's going on here? Cheers.
[trace]: https://gist.github.com/qguv/848b225888bc3a9f3bdb

**Comment by parkr** [comment] 2015-03-22 04:22
segfaults are usually because you're loading a library compiled for a different ruby version. try uninstalling those gems and re-installing them. looks like posix-spawn / pygments.rb.

**Comment by parkr** [comment] 2015-03-22 04:23
Also :metal: for linguistics!

**Comment by qguv** [comment] 2015-03-22 04:34
> I've recompiled ruby and all gems
Yep

**Comment by envygeeks** [comment] 2015-03-22 08:21
Can we have you cross-file this on https://github.com/rtomayko/posix-spawn since it's their library that is segfaulting and if you don't mind, can you please tell me the version you have of posix-spawn you have so I can (or somebody else with a Macbook) can test it and see if they can get it to segfault.  It would be nice if you provide the complete steps to your build process to both us and them so that we can both try and replicate it.

It's true that segfaults can be caused (sometimes) by using the wrong Ruby version but most of the time it's caused by a library not handling something inside of the code properly and even if posix-spawn does not support Ruby 2.0.0 (I'm not saying if it does or doesn't) a segfault should not happen.

**Comment by envygeeks** [comment] 2015-03-22 08:24
Sorry I just noticed you were trying to build 0.3.10 can you try to build with a locked 0.3.9.

**Comment by envygeeks** [comment] 2015-03-24 15:07
I'm closing this issue as there has been no answer, if you have this problem again please feel free to post back in here or create a new issue and it will be reopened or investigated again.

**Closed by envygeeks** 2015-03-24 15:07 UTC
Labels: Pending Comments

**Comment by qguv** [comment] 2015-03-28 14:45
After switching to rvm and wrestling my environment together, I'm not getting this error. I have no explanation. I ended up using ruby 2.1.1, for what it's worth. Thanks for the responses, everyone.
