### ISSUE TITLE
New blog can't serve css

### ISSUE THREAD

**Issue by bradley-curran** [jekyll/jekyll#5448] opened 2016-10-05 21:50 UTC
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

- Use ruby 2.2.0
- Create a new gemdir
- Install bundler and jekyll 3.2.1
- Create a new blog
- Serve the site using jekyll
- Note the page loads with an invalid `.css` file

## The Output I Wanted

A fully functioning new site

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by pathawks** [comment] 2016-10-05 21:57
I’m so sorry this is happening.

Unfortunately, this is a known issue. The good news is that this will be fixed very soon in v3.3.0.

Closing this as a duplicate of #5404. Check out that issue for a more detailed explanation of what is happening and how to fix it.

**Closed by pathawks** 2016-10-05 21:57 UTC
