### ISSUE TITLE
lambdas.json does not exist

### ISSUE THREAD

**Issue by dlo** [jekyll/jekyll#3796] opened 2015-06-18 02:10 UTC
I saw a few other issues around the web where Jekyll builds have been failing due to this error. Could the error message be improved for this? It's very confusing since it's not actually an error with Jekyll itself. Thanks!

**Comment by envygeeks** [comment] 2015-06-18 02:13
It could be, if it was actually being caused by us, but we don't have a file called "lambdas.json" and this error is probably literally caused by something you are doing or using.  I've never heard of, seen or even witnessed that file in any of our source or seen that error.

**Comment by dlo** [comment] 2015-06-18 02:17
See #3405

**Comment by envygeeks** [comment] 2015-06-18 02:18
And look through the ticket comments, ultimately it was caused by something not even related to us.

**Comment by dlo** [comment] 2015-06-18 02:20
@envygeeks I don't think it's fair to say it was caused by something unrelated, since the Jekyll command is the one that ultimately spit out this error message. Jekyll is expecting subdirectories (or code in subdirectories?) to behave a certain way, and somehow it's causing a problem. I think it might make sense to figure out what this problem is and why Jekyll is complaining about random directories in an incredibly obtuse way.

**Comment by dlo** [comment] 2015-06-18 02:22
Just to add on to the list of potential fixes, I had an "npm_modules" directory in my Jekyll product. "rm -rf"'ing it fixed the issue (in case this helps anyone else). Fortunately nothing in there was needed for the project to run.

**Comment by envygeeks** [comment] 2015-06-18 02:26
I understand it's not fair, but we can't solve problems we don't know about in your source before we know about them, and we can't solve problems you create in your source because we aren't your sources keeper, what you put in your source directory is really on you to manage.

We don't off the hinge search for that file, it was added to your source by you in some way.  The most we could do is detect that error and spit out a "did you forget to ignore a folder?" message but that doesn't resolve the fact that we didn't go looking for that file until you tolds us to :/

**Comment by dlo** [comment] 2015-06-18 02:30
Gotcha. Thanks for the explanation.

I think what would be helpful is a more user-friendly error message. As a user of Jekyll, I have no idea what I need to do to resolve a message in the form of "xxx doesn't exist". Do I need to delete something? Is Jekyll the one expecting the file? Why would it expect it to exist? Etc.

**Comment by envygeeks** [comment] 2015-06-18 02:31
Well, if you can recreate the exact error you got (since I do not wish to rely on theirs as yours might be different in some way) I'm sure @jekyll/core could discuss in some way just spitting out a side message to the affect of what I said to hint at what might actually be the problem.

**Comment by dlo** [comment] 2015-06-18 02:35
Perfect, just got it. I'm not an NPM expert, but this is after running `npm install` on a fairly simple (I think?) package.json.

#### package.json

```json
{
  "name": "dlo-me",
  "author": "Dan Loewenherz",
  "repository": {
    "type": "git",
    "url": "https://github.com/dlo/dlo.github.com"
  },
  "version": "0.0.1",
  "devDependencies": {
    "bower": "~0.9.2",
    "grunt": "^0.4.5",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-jslint": "^1.1.12",
    "js-beautify": "1.5.5"
  }
}
```

#### Error

```
$ jekyll serve --trace
/Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
Configuration file: /Users/dan/Documents/Projects/dlo.github.com/_config.yml
            Source: /Users/dan/Documents/Projects/dlo.github.com
       Destination: ./_site
      Generating...
/Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll.rb:146:in `expand_path': user lambdas.json doesn't exist (ArgumentError)
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll.rb:146:in `sanitized_path'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:104:in `block in in_source_dir'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:103:in `each'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:103:in `reduce'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:103:in `in_source_dir'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:173:in `block in read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `each'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:176:in `block in read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `each'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:176:in `block in read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `each'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:176:in `block in read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `each'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:176:in `block in read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `each'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:176:in `block in read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `each'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:176:in `block in read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `each'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:176:in `block in read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `each'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in `read_directories'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:151:in `read'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:49:in `process'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by mattr-** [comment] 2015-06-18 02:40
Plain and simple, Jekyll has a set list of things it ignores by default. the `npm_modules` directory is not one of them. Much like @envygeeks said, if you want Jekyll to ignore something, you need to tell it so via the `_config.yml` file. If you've already done that, then this would be a bug that we should fix, but based on your explanation, I don't believe you have, so the fix in this case is to configure Jekyll to proper ignore that directory and you should stop seeing that error. Since this isn't a bug in Jekyll, I'll go ahead and close it. We'll see any further comments that come in. Thanks! :smiley:

**Closed by mattr-** 2015-06-18 02:40 UTC
Labels: ¯\_(ツ)_/¯

**Comment by dlo** [comment] 2015-06-18 02:48
@mattr- I appreciate the response. I don't think suggested fix properly addresses the original problem, but if you do feel everything is working as expected, I am ok with that. My complaint is more that the current error message is very not user-friendly or helpful (and that the messaging should be improved), _not_ that things aren't working as expected.

If you are a user of Jekyll, and you are presented with the error I pasted above--what would you think to do? How would you know how to fix it? The error that Jekyll presents doesn't make this very clear.

**Comment by dlo** [comment] 2015-06-18 02:49
Here is the shortened form of the error for reference sake:

```
$ jekyll serve
/Users/dan/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
Configuration file: /Users/dan/Documents/Projects/dlo.github.com/_config.yml
            Source: /Users/dan/Documents/Projects/dlo.github.com
       Destination: ./_site
      Generating...
jekyll 2.5.3 | Error:  user lambdas.json doesn't exist
```

**Comment by mattr-** [comment] 2015-06-18 02:50
I don't disagree with you, but Jekyll operates under the assumption that
things you put there should be processed by it unless you tell it not too.
I'm happy to have the error message improved, but what do we say when this
sort of thing happens?

**Comment by envygeeks** [comment] 2015-06-18 02:52
@mattr- exactly what I suggested, detect the error and simply output the error with a Jekyll.logger.error message that says "did you forget to ignore something? See insert page about ignores here"

**Comment by dlo** [comment] 2015-06-18 02:53
@envygeeks yep, great idea! And perhaps display the `base_directory` variable in the jekyll.rb as well so maybe the user knows where to look?

**Comment by walutisme** [comment] 2015-06-18 04:56
Separating Jekyll source folder maybe better. I use Jekyll with my build tools and I never get this error. Also separated Jekyll source folder make everything easier to maintain.

**Comment by dlo** [comment] 2015-06-18 14:56
@envygeeks @mattr- Would you merge a PR with this change? Happy to contribute if so. :)

**Comment by envygeeks** [comment] 2015-06-18 14:58
I'd be happy to review a pull request to the effect of what you would like to do.
