### ISSUE TITLE
Please update Rouge version

### ISSUE THREAD

**Issue by yefim** [jekyll/jekyll#5874] opened 2017-02-10 04:03 UTC
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

Currently, jekyll is on Rouge 1.7. It would be nice to get that bumped to at least 2.0. 2.0 supports more syntaxes. (I would really like Dockerfiles to be highlighted.) Please and thank you!

**Comment by pathawks** [comment] 2017-02-10 04:53
Duplicate of #5230

**Closed by pathawks** 2017-02-10 04:53 UTC
