### ISSUE TITLE
'pretty' permalinks do not match URL TEMPLATE

### ISSUE THREAD

**Issue by bcomnes** [jekyll/jekyll#2691] opened 2014-08-04 23:46 UTC
These two configuration settings do not result in the same behavior as indicated by the docs:
```yaml
#./_config.yml
- permalink: pretty
```
Results in `./processed.html - > ./processed/index.html`

```yaml
-permalink: /:categories/:year/:month/:day/:title/
```
Results in `./processed.html - > ./processed.html`
where it should actually result in:
```
./processed.html - > ./processed/index.html
```

**Comment by fulldecent** [comment] 2015-01-29 17:04
This issue is closed, but it is still referenced at http://jekyllrb.com/docs/permalinks/

**Comment by adius** [comment] 2015-02-08 18:44
Why is this issue closed? It hasn't been fixed yet, or has it?

**Comment by jalcine** [comment] 2015-02-08 19:13
@adius Probably because a PR is still pending [1](https://github.com/jekyll/jekyll/issues/2691#issuecomment-51929552) [2](https://github.com/jekyll/jekyll-help/issues/138) that addresses this.

**Comment by adius** [comment] 2015-02-08 19:15
Ah. I guess the issues shouldn't be closed until the PRs are merged!

**Comment by bcomnes** [comment] 2015-02-15 20:20
As far as I know, nobody has submitted a PR to address this.  The issue, as it stands, is settled which is why this issue is closed.  If someone wants this open, the best way to do that would be to submit a PR that actually addresses the issue.

**Comment by adius** [comment] 2015-02-15 22:03
^^ Interesting understanding of closed issues.

**Comment by fulldecent** [comment] 2015-02-16 13:57
Reopen this issue, it is still referenced at http://jekyllrb.com/docs/permalinks/

**Comment by pathawks** [comment] 2015-02-16 14:17
> A PR would be welcome. :smile:

**Comment by fulldecent** [comment] 2015-02-16 14:20
Open issues beget PRs

**Comment by willnorris** [comment] 2015-03-01 02:59
I'm going to reopen this, as I'm taking a stab at implementing a fix, either as part of #3490 or a separate PR.  Rather than introduce any new config settings, my intent is to just make the current behavior a little smarter with regard to URL endings for pages and collections based on the `permalink` setting, which is the confusion that @bcomnes initially described.

So my intended behavior for page URLs is something like:

- if you have `permalink: pretty`, then use the current logic.  That is:
  - html index pages use `/:path/`
  - other html pages use `/:path/:basename/`
  - all other pages use `/:path/:basename:output_ext`
- if you have `permalink: none` or `permalink: date`, use the current logic for that, which means all pages use `/:path/:basename:output_ext`
- otherwise, page URLs should match the ending style specified in `permalink`.  That is:
  - if `permalink` ends with a trailing slash, then use `/:path/:basename/`
  - if `permalink` ends with `:output_ext`, then use `/:path/:basename:output_ext`
  - if `permalink` uses extensionless URLs (neither trailing slash or `output_ext`), then use `/:path/:basename`.

HTML index pages will continue to just use `/:path/`, and non-HTML pages will always use `/:path/:basename:output_ext`.

Default permalinks for collections follow the same basic logic, barring index pages and such where not applicable.

It sounds like a lot of logic, but it's really not too bad.  And honestly I think it's much more intuitive than the current behavior, and still only needs the single `permalink` config setting.  Please let me know if this sounds like a reasonable approach to you all.

**Comment by bcomnes** [comment] 2015-03-01 03:24
:+1: Awesome @willnorris!

**Comment by parkr** [comment] 2015-03-01 08:16
> Please let me know if this sounds like a reasonable approach to you all.

Sounds great to me!

**Closed** 2015-03-04 23:18 UTC
