### ISSUE TITLE
Collapsible block's arrows do not show on Firefox

### ISSUE THREAD

**Issue by S-B99** [jekyll/jekyll#7998] opened 2020-02-08 17:47 UTC
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Android 10 - Chrome / Windows 7 - Firefox / Arch - Firefox / Arch - Chrome | All latest |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |
| [live site](https://blue.bella.wtf/) | [repo](https://github.com/S-B99/kamiblueWebsite) |

---

## Expected Behaviour

Collapsible blocks arrows show on firefox like this 

This only works on chrome based browsers
![unknown](https://user-images.githubusercontent.com/17222512/74089584-a6981a00-4a70-11ea-99a1-b7d3140b7157.png)

## Current Behavior

It does this instead (on firefox)

![2020-02-08-124511_325x378_scrot](https://user-images.githubusercontent.com/17222512/74089615-0d1d3800-4a71-11ea-9f08-c61c1fc1dd6f.png)

## Code Sample

```html
<details>
    <summary>Gui</summary>
    <p><ul>
        <li>Capes<p><i>Shows a fancy cape for KAMI Blue donators, that all users can see. Donate or boost the Discord to unlock!</i></p></li>
        <li>ArmourHide<p><i>Hides the armour on selected entities</i></p></li>
        <li>CleanGUI<p><i>Modifies parts of the GUI to be transparent</i></p></li>
        <li>InfoOverlay<p><i>Configures the game information overlay</i></p></li>
        <li>InventoryViewer<p><i>View your inventory on screen</i></p></li>
        <li>Zoom<p><i>Configures FOV</i></p></li>
    </ul></p>
</details>
```

**Comment by ashmaroli** [comment] 2020-02-08 18:05
Closing as this is a browser-limitation and not because of Jekyll.

**Closed** 2020-02-08 18:05 UTC

**Comment by S-B99** [comment] 2020-02-11 14:51
Hi, I opened a bug report in bugzilla [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1614142), and during that discovered this only happens when using jekyll. Using my code example works with raw HTML, it only happens when rendering my page with jekyll.

**Comment by ashmaroli** [comment] 2020-02-11 15:58
@S-B99 I took a closer look at your repo since Bugzilla guys were sure that your case was not a valid bug. 
The issue is with the `normalize.css` in your site.

Look for a block that sets `summary { display: block }` and remove `summary` from the list.

**Comment by S-B99** [comment] 2020-02-11 16:07
Removing it causes this, though it does fix the issue with my summaries 
![image](https://user-images.githubusercontent.com/17222512/74254585-a3926900-4cbe-11ea-8e8e-53c1b4ad5f06.png)

**Comment by ashmaroli** [comment] 2020-02-11 16:17
You are to remove just `summary` from the list, not delete the entire rule.

**Comment by S-B99** [comment] 2020-02-11 16:18
All I did was remove summary from my list. It doesn't appear anywhere else in my normalise.

**Comment by ashmaroli** [comment] 2020-02-11 16:20
Hmm.. could you commit the change to a branch and open a pull request in your repo? Let us take this discussion there.

**Comment by S-B99** [comment] 2020-02-11 16:22
Yep, thank you c:
https://github.com/S-B99/kamiblueWebsite/pull/24
