### ISSUE TITLE
ConfigMap is deprecated

### ISSUE THREAD

**Issue by Kimwangqing** [jekyll/jekyll#8301] opened 2020-07-13 08:17 UTC
I cloned two jekyll themes, when I run "bundle exec jekyll serve", one is normal, but another one always got the deprecation warning. 
![image](https://user-images.githubusercontent.com/30616599/87279421-cef1dc00-c51a-11ea-8e81-5f084f2e6957.png)
Then, my action is to run "gem update jkeyll" and got the response "Nothing to update", run "gem update --system" and the response is "Latest version already installed. Done", run "bundle exec jekyll -v" and got the bug 
![image](https://user-images.githubusercontent.com/30616599/87279474-85ee5780-c51b-11ea-9416-5772b8701a40.png).
Here are my current environment details for the theme has bug:
$ gem env version
3.1.4
$ ruby --version
ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]
$ bundle -v
Bundler version 2.0.1
For the normal theme, It makes a difference:
$ gem env version
3.1.4
$ bundle -v
Bundler version 2.1.4
$ ruby --version
ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]
$ bundle exec jekyll -v 
jekyll 3.8.7
( no bug when I run the command on thr normal theme)

**Comment by ashmaroli** [comment] 2020-07-13 09:20
The difference like you suspected is because of the different versions of Bundler:
```
$ bundle -v
Bundler version 2.0.1
```
and
```
$ bundle -v
Bundler version 2.1.4
```
What you can do is:
- either manually edit the `BUNDLED WITH` in the `Gemfile.lock` file of theme with deprecations
- or delete the `Gemfile.lock` completely and run `bundle install`

---

Either ways, I'm closing this since it is not a bug in Jekyll
If you encounter similar issues in the future, you may approach our community forum at https://talk.jekyllrb.com/

**Closed** 2020-07-13 09:20 UTC

**Comment by Kimwangqing** [comment] 2020-07-13 11:00
Thanks for your response, but that doesn't work whichever 1 or 2 way you mentioned.  
 I manually edit the BUNDLED WITH in the Gemfile.lock file of theme with deprecations, then run "bundle exec jekyll serve" , it occurs another warning 
![image](https://user-images.githubusercontent.com/30616599/87297327-d32df180-c53a-11ea-949e-2d7264b473c8.png)
Then, I trie to delete gemfile.lock and run "bundle install", it tells me "Failed to build gem native extension"
![image](https://user-images.githubusercontent.com/30616599/87297452-02dcf980-c53b-11ea-9109-c244fe439e09.png)

**Comment by ashmaroli** [comment] 2020-07-13 11:13
You can try running the following:
```
ridk exec gem install http_parser.rb
```
If that works, try running `bundle install` again.

If none of the above works, try running `ridk install` and continue installation with default options when asked for.
Once that completes, try running `bundle install` again.

**Comment by Kimwangqing** [comment] 2020-07-14 03:12
When I run `ridk exec gem install http_parser.rb`, I got this `bash: ridk: command not found`, 
then run `ridk install`, also got `bash: ridk: command not found`. 
I tried the alternative `gem install http_parser.rb`, seems it is works
![image](https://user-images.githubusercontent.com/30616599/87378716-0d41d680-c5c1-11ea-90bd-228afb4dd480.png)
Then run `bundle install`, 
however got this:
![image](https://user-images.githubusercontent.com/30616599/87379040-e20bb700-c5c1-11ea-961e-e9b02e0a60da.png)
I replaced the source with `https://gems.ruby-china.com/..`, but that's not the point of the issue I think. 
Do I need delete ruby and reinstall again, if do so, will influence another theme's localhost?

**Comment by ashmaroli** [comment] 2020-07-14 07:03
For the theme with deprecation, Bundler is installing a *local set of gems* in the `./vendor/` directory. So even if `gem install ...` succeeds, Bundler will still try to install a local version.
You may find the config setting at the path `D:/Kim blog/Kimwangqing.github.io-master/.bundle`. Delete that `.bundle` directory and run `bundle install` again.

If issues still persist, try renaming your parent directory to not contain spaces. It is a well-known tenet that Ruby ecosystem doesn't install well in directory paths containing spaces.

**Comment by Kimwangqing** [comment] 2020-07-14 07:35
That works to delete `.bundle` and then run `bundle install`. Now, the localhost is normal. Thanks a lot!

**Comment by ashmaroli** [comment] 2020-07-14 07:36
You're welcome. Glad everything's sorted now.
