### ISSUE TITLE
Incompatible with forwardable 1.3.0

### ISSUE THREAD

**Issue by cryocz** [jekyll/jekyll#7916] opened 2019-12-01 15:57 UTC
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | 5.3.12-300.fc31.x86_64           |
| `jekyll`         | 4.0.0     |
| `forwardable`   | 1.3.0     |

---
It appears that yesterday a new version of [forwardable](https://github.com/ruby/forwardable) was released (version 1.3.0). I'm not entirely sure whether this is a issue with how the library is used in Jekyll or whether this is a bug in the new version of forwardable, but the method `Forwardable.def_delegator` no longer returns the names of generated methods. This is an issue because Jekyll uses the results of this method as the input of `private` (see `lib/jekyll/drops/document_drop.rb` for instance). 

Since the method newly returns just `nil`, ruby raises an exception (`'private': nil is not a symbol nor a string (TypeError)`), and as a result Jekyll crashes (when building/serving).

When I downgrade to `forwardable v1.2.0`, everything suddenly works.

## Steps to reproduce
Ensure `forwardable v1.3.0` is installed.
```sh
$ sudo gem install forwardable --version 1.3.0
```

Try to build any blog.
```sh
$ jekyll b
```

The build will fail and result in a similar message:
```
Traceback (most recent call last):
	12: from /usr/local/bin/jekyll:23:in `<main>'
	11: from /usr/local/bin/jekyll:23:in `load'
	10: from /usr/local/share/gems/gems/jekyll-4.0.0/exe/jekyll:8:in `<top (required)>'
	 9: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/local/share/gems/gems/jekyll-4.0.0/lib/jekyll.rb:198:in `<top (required)>'
	 6: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /usr/local/share/gems/gems/jekyll-4.0.0/lib/jekyll/drops/document_drop.rb:3:in `<top (required)>'
	 3: from /usr/local/share/gems/gems/jekyll-4.0.0/lib/jekyll/drops/document_drop.rb:4:in `<module:Jekyll>'
	 2: from /usr/local/share/gems/gems/jekyll-4.0.0/lib/jekyll/drops/document_drop.rb:5:in `<module:Drops>'
	 1: from /usr/local/share/gems/gems/jekyll-4.0.0/lib/jekyll/drops/document_drop.rb:17:in `<class:DocumentDrop>'
/usr/local/share/gems/gems/jekyll-4.0.0/lib/jekyll/drops/document_drop.rb:17:in `private': nil is not a symbol nor a string (TypeError)
```

**Comment by ashmaroli** [comment] 2019-12-01 16:49
Thank you for reporting this @cryocz 
I was not able to reproduce this with Ruby 2.4 on Windows.
I then re-ran our last Travis build (caches flushed). It did not install the `forwardable-1.3.0` but used the version shipped as part of Ruby core.
(ref: https://travis-ci.org/jekyll/jekyll/jobs/618955010)

Therefore, unless one of the maintainers here is able to reproduce this issue at their end locally, the only solution at the moment is to uninstall `forwardable-1.3.0` from your system.

**Comment by DirtyF** [comment] 2019-12-01 20:41
```

**Comment by DirtyF** [comment] 2019-12-01 20:50
@ashmaroli I can reproduce the issue: 

```

**Comment by ashmaroli** [comment] 2019-12-02 03:32
I've filed an issue at https://github.com/ruby/forwardable/issues/10 with a possible solution..

**Comment by ashmaroli** [comment] 2019-12-11 12:14
[forwardable-1.3.1](https://rubygems.org/gems/forwardable/versions/1.3.1) has been released with a patch to resolve this.

Please update the gem at your end.

**Closed by ashmaroli** 2019-12-11 12:14 UTC
Labels: upstream-issue
